kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/cache/LRUProjectDataModelOracleCache.java
kie-wb-common-services/kie-wb-common-services-backend/pom.xml
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/Builder.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/LRUBuilderCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/PackageNameWhiteList.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/project/ProjectServiceImpl.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/BuildServiceImplTest.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/BuilderTest.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/project/ProjectServiceImplNewProjectTest.java
pom.xml

@wmedvede @mswiderski 
This PR is for https://bugzilla.redhat.com/show_bug.cgi?id=1201853.
It sets the "package name white-list" to the default package created for new projects: https://github.com/droolsjbpm/kie-wb-common/commit/8125e298cb4f65787e688659afe58189cff70b85#diff-5043480836f5a8381d4aeced0fb90d8fR342
It also uses the "package name white-list" for filtering classes
(a) Added to the DataModelOracle - which contains the meta-data for classes available for authoring:
https://github.com/droolsjbpm/kie-wb-common/commit/8125e298cb4f65787e688659afe58189cff70b85#diff-37f1dae81fc151bee95c9e1ee6831b71R98
(b) Validated for integrity (i.e. the class can be loaded) - the source of the WARNs mentioned in the BZ:
https://github.com/droolsjbpm/kie-wb-common/commit/8125e298cb4f65787e688659afe58189 …

BZ1201853: Huge amount ClassNotFoundException WARNs on Project build

---

kie-wb-common-services/kie-wb-common-data-modeller-core/src/test/java/org/kie/workbench/common/services/datamodeller/driver/RoasterApiTest.java

I did some polishing when I was reviewing new tests related to [JBPM-4625](https://issues.jboss.org/browse/JBPM-4625):
* Added type parameters to resolve a few raw type warnings
* Added a few missing assertions to RoasterApiTest
* Excluded `errai-javax-enterprise` artifact from dependency tree
It contains custom implementation of `java.lang.reflect.Method`, which is used in `org.kie.workbench.common.services.datamodeller.util.DriverUtils`. `DriverUtils` uses `Method#getDefaultValue()`, which is missing in the class from `errai-javax-enterprise` and so I was unable to run the tests in my IDE due to this (depends on class loading order, probably).
Please **squash** the commits if you are going to merge this.

JBPM-4625 tests polishing

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java

- Complementary fix to Eder's "Hide docks when you put data modeler in background".

JBPM-4625 Generation of JPA enabled models

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/main/java/org/kie/workbench/common/screens/datamodeller/backend/server/PrimitivesAnnotation.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationlisteditor/AdvancedAnnotationListEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationwizard/CreateAnnotationWizard.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationwizard/SearchAnnotationPage.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationwizard/SearchAnnotationPageView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationwizard/SearchAnnotationPageViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/annotationwizard/SearchAnnotationPageViewImpl.ui.xml
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/ValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/booleans/BooleanValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/booleans/BooleanValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/booleans/BooleanValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/EnumValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/EnumValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/EnumValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/MultipleEnumValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/MultipleEnumValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/enums/MultipleEnumValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/generic/GenericValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/generic/GenericValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/generic/GenericValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/multiple/MultipleValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/multiple/MultipleValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/multiple/MultipleValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/numeric/NumericValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/numeric/NumericValuePairEditorView.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/numeric/NumericValuePairEditorViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/string/StringValuePairEditor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/advanceddomain/valuepaireditor/string/StringValuePairEditorViewImpl.java

- CreateAnnotationWizard
- It was not possible to type the annotation class name for searchinig
- String value pair editor permits enter null values when the value pair is required
- Some other fixes on the value pair editors are also included
- All value pair editors had the "*" required mark even when the value is not required
- AdvancedAnnotationListEditor
- Remove annotation didn't work

JBPM-4777-Data Modeller fixes after the BS3 migration

---

kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-backend/pom.xml
kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-backend/src/main/java/org/kie/workbench/common/screens/search/backend/server/SearchServiceImpl.java
kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-backend/src/test/java/org/kie/workbench/common/screens/search/backend/server/MockTypeRegister.java
kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-backend/src/test/java/org/kie/workbench/common/screens/search/backend/server/SearchServiceImplTest.java
kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider

See https://bugzilla.redhat.com/show_bug.cgi?id=1192831
The last piece of the equation was that Users could see (Search) assets in Repositories that did not explicitly have Groups assigned; but were contained in an OU to which the User lacked access. This change filters authorized Repositories first on the OUs to which the User has access and then the Repositories contained within those OUs.

BZ1192831: User with no privileges for Repository can view and modify assets in that Repository

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/wizard/NewServerTemplateWizard.java

Without this CDI fails to make an instance of the class and when running the UI the users sees a "loading" popup that never goes away.

Adds default constructor.

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/workbench/configuration/LanguageConfigurationHandler.java

See https://bugzilla.redhat.com/show_bug.cgi?id=1320813#c12
This PR fixes "ChineseSimplified" constant usage.
(cherry picked from commit 3d9836f8aaaed87f12614f20837d5317e62104cf)

[6.4.x] BZ1320813: [ru_RU][zh_TW] Please add Russian and Traditional Chinese to language list in workbench settings

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenter.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenView.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenViewImpl.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenterTest.java

This PR fixes the BuildOptionExtension feature that allows LiveSpark to add a custom button in the build drop-down list in the project authoring screen. Without this PR, the custom build button added by LiveSpark is rendered as a hyper-link beside the build drop-down list.

Render items from BuildOptionExtensions in (not beside) dropdown list

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/main/java/org/kie/workbench/common/screens/datamodeller/backend/server/DataModelerServiceImpl.java
kie-wb-common-services/kie-wb-common-data-modeller-core/src/main/java/org/kie/workbench/common/services/datamodeller/driver/SourceFilter.java
kie-wb-common-services/kie-wb-common-data-modeller-core/src/main/java/org/kie/workbench/common/services/datamodeller/driver/impl/JavaRoasterModelDriver.java
kie-wb-common-services/kie-wb-common-data-modeller-core/src/test/java/org/kie/workbench/common/services/datamodeller/driver/JavaRoasterModelDriverTest.java

This PR introduces a mechanism for filtering out Java classes in a project from being loaded by the DataModelerService. This feature is necessary for LiveSpark, where we generate Java classes with GWT dependencies that cannot be class-loaded (and these classes are not data models so there is no reason we would want them to be loaded as such).
There are also two commits with some minor house-keeping (removing unused private fields/methods, and fixing some compiler warnings).

Data modeller filter extension

---

kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/backend/builder/JavaSourceFilter.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/Builder.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/LRUBuilderCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/BuilderTest.java

This PR is required for LiveSpark, where we require the ability to prevent client-side classes with GWT dependencies from being compiled.

Filter out Java source files from compilation in KieBuilder

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-api/pom.xml
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-api/src/main/java/org/kie/workbench/common/screens/examples/model/ExamplesModel.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-api/src/main/java/org/kie/workbench/common/screens/examples/service/ExamplesService.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImplTest.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-client/src/test/java/org/kie/workbench/common/screens/examples/client/wizard/ExamplesWizardTest.java

See https://issues.jboss.org/browse/JBPM-5115
I changed the import of Examples to include the first imported Project in the ```ProjectContextChangeEvent``` event fired upon completion. I tested a few times with ```kie-drools-wb``` with clean installs and the newly imported Project was correctly selected in the Project Explorer.

JBPM-5115: Context of Project Editor is often not updated after importing project using ExamplesWizard

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/handlers/NewPackageHandler.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/handlers/NewPackageHandlerTest.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/validation/PackageNameValidator.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/validation/PackageNameValidatorTest.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/validation/ValidationServiceImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourceView.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/handlers/NewResourceViewTest.java

This time hopefully with correct license headers and without typos. :)
There are some small code changes - added `null` check, method made package private to enable testing, moving `NewPackageHandler` from field injection to constructor injection (as is already done for `NewProjectHandler`) and reusing `DefaultNewResourceHandler.getPackage()`.
Related BZs:
- 1006506 - File name validation broken
- 1062289 - Create new Package dialog displays no warning when using " in package name
(part n+1 in 'Moving tests to community', soon in your theaters)

Add test coverage for various filename validation related bits

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/menu/FileMenuBuilder.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/menu/FileMenuBuilderImpl.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorLockSyncHelper.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorLockSyncHelperTest.java

See https://issues.jboss.org/browse/GUVNOR-2548
This PR provides an implementation of ```LockSyncMenuStateHelper``` that only applies changes to ```MenuItem``` enabled state if change in lock is associated with the "active document".

GUVNOR-2548: Guided Decision Table Editor: BasicFileMenuBuilderImpl: Support overriding default lock-sync behaviour

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/EnhancedDependenciesManager.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/EnhancedDependenciesManagerTest.java

In fact, the dependencies were being saved correctly. However, in the dependency page load, a filter was removing the dependencies that had scope different from "compile". As "compile" is the default scope, this PR makes dependencies without scope be handled as a compile dependency.

RHBPMS-3997: [GSS](6.3.x) Project dependencies are not retained in BPM Suite 6.3.0

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/EnhancedDependenciesManager.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/EnhancedDependenciesManagerTest.java

In fact, the dependencies were being saved correctly. However, in the dependency page load, a filter was removing the dependencies that had scope different from "compile". As "compile" is the default scope, this PR makes dependencies without scope be handled as a compile dependency.

[6.4.x] RHBPMS-3997: [GSS](6.3.x) Project dependencies are not retained in BPM Suite 6.3.0

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/DomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/advanceddomain/AdvancedDomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/droolsdomain/DroolsDomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/jpadomain/JPADomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/maindomain/MainDomainHandler.java

Removes unused methods from `DomainHandler` class hierarchy.

PLANNER-618 Workbench: Use org.jboss.errai.ioc.client.api.ManagedInstance instead of BeanManager where possible

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/pom.xml
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/util/AnnotationUtils.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/ProjectDataModelFactAnnotationsTest.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/testclasses/annotations/JAXBSmurf.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/testclasses/annotations/JAXBSmurfFactory.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/PackageDataModelFactAnnotationsTest.java

See https://issues.jboss.org/browse/GUVNOR-2621
The solution contained in this PR is to use the ```toString()``` representation of any non-portable values.
```Class``` on the client has very little use, as it cannot be instantiated. I tested with ```drools-wb-webapp``` and Data Modeller and rules (with, for example, EVENTS) continue to work fine.. All tests pass (I had to change two assertions from ``` Role.Type.EVENT``` to ```"EVENT"``` however we do not use this to determine whether a Type is an event).

GUVNOR-2621: DataModelOracle: Does not handle annotations with member properties of type Class e.g. @XmlType

---

kie-wb-common-screens/kie-wb-common-social-home-page/kie-wb-common-social-home-page-client/src/main/java/org/kie/workbench/common/screens/social/hp/client/resources/i18n/Constants.java
kie-wb-common-screens/kie-wb-common-social-home-page/kie-wb-common-social-home-page-client/src/main/java/org/kie/workbench/common/screens/social/hp/client/userpage/side/SideUserInfoView.ui.xml
kie-wb-common-screens/kie-wb-common-social-home-page/kie-wb-common-social-home-page-client/src/main/resources/org/kie/workbench/common/screens/social/hp/client/resources/i18n/Constants.properties

cherry-pick fix from 6.4.x
For explanation see older PR https://github.com/droolsjbpm/kie-wb-common/pull/257

Fix i18ed label in User perspective

---

kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/utils/Utils.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/business/BusinessViewWidget.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/test/java/org/kie/workbench/common/screens/explorer/client/utils/UtilsTest.java

Use suffix of given resource type instead of determining it by the last occurrence of '.' character. This is motivated by the fact that solver configuration filenames use 'solver.xml' suffix, which leads to undesired behavior.

PLANNER-630 Workbench: Solver configuration names contain redundant 'solver' suffix

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/main/java/org/kie/workbench/common/screens/datamodeller/backend/server/indexing/JavaSourceVisitor.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/java/org/kie/workbench/common/screens/datamodeller/backend/server/indexing/JavaSourceVisitorTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/resources/org/kie/workbench/common/screens/datamodeller/backend/server/indexing/Enum2.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/resources/org/kie/workbench/common/screens/datamodeller/backend/server/indexing/Interface2.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/resources/org/kie/workbench/common/screens/datamodeller/backend/server/indexing/Pojo2.java

Constructors are included in the method list, however their return type is null. Avoid NPEs by adding null check.

JavaSourceVisitor - add null check for method return type

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/menu/ProjectMenu.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/menu/ProjectMenuTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourcesMenu.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/handlers/NewResourcesMenuTest.java

See https://issues.jboss.org/browse/RHBRMS-349
This PR ensures the ```MenuItems``` enabled/disabled state is initialised correctly when the Menu's items are requested (by, for example, navigating to the Authoring Perspective).

RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/menu/ProjectMenu.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/menu/ProjectMenuTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourcesMenu.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/handlers/NewResourcesMenuTest.java

See https://issues.jboss.org/browse/RHBRMS-349
(cherry picked from commit 903d0068908a59bb09ced6da9d2aa0a1165656cc)
This is the corollary of https://github.com/droolsjbpm/kie-wb-common/pull/437 for 6.5.x.

[6.5.x] RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset (#437)

---

kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/pom.xml
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/main/java/org/kie/workbench/common/screens/explorer/backend/server/ExplorerServiceImpl.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/ExplorerServiceImplTest.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/ExplorerServiceImplTestUtil.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/resources/META-INF/beans.xml

**Steps do reproduce the issue:**
1. Login User A on Host A (Chrome)
2. Login User B on  Host B (Safari)
3. Select a Project X on User B
4. Create a Project Y on User A (with != group)
5.  Folder from Project X (User B) is displayed instead of Folder of Project Y.
**Why?**
The issue begins here:
````
public void onProjectAdded( @Observes final NewProjectEvent event ) {
if ( view.isVisible() && event.getProject() != null ) {
if ( sessionInfo.getId().equals( event.getSessionId() )
&& isInActiveBranch( event.getProject() ) ) {
refresh( event.getProject() );
} else {
refresh();
}
}
}
````
When a project is added in Host A, Host A calls refresh( event.getProject() ); and Host B calls refresh().
Both calls are handled by ExplorerServiceImpl (ApplicationScoped) …

[GSS] project created by another user is displayed when multiple users create it concurrently

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/DependencyLoader.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/DependencyLoaderView.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/DependencyLoaderViewImpl.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/DependencyLoaderLoadFailureTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/DependencyLoaderTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/EnhancedDependenciesManager_onEchancedDependenciesLoadedTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/forms/dependencies/Util.java

RHBRMS-2516 : When importing external projects, the dependency are not taken and at application server also
(cherry picked from commit 0c4d7bb12678cfaffa1523a4f2416ba07d7ab029)
99% the same as the fix for GUVNOR-2508
https://issues.jboss.org/browse/RHBRMS-2516
https://issues.jboss.org/browse/GUVNOR-2508

[6.5.x] RHBRMS-2516 : When importing external projects, the dependency are not taken and at application server also

---

kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorTest.java

See https://issues.jboss.org/browse/GUVNOR-2707
Retrieve the version for the "Overview Screen" from the ```VersionRecordManager``` instead of from the active "Document". This is how regular ```KieEditors``` pass the Version to the "Overview Screen".

GUVNOR-2707: Guided Decision Table Editor: Overview Page throws an exception unless a Version is explicitly selected

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/widget/CachingEnumDropDownUtilities.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/widget/EnumDropDownUtilities.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/widget/CachingEnumDropDownUtilitiesTest.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/AbstractProxyPopupDropDownListBox.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDropDownEditCell.java

See https://issues.jboss.org/browse/RHBRMS-2610
This is the equivalent of https://github.com/droolsjbpm/drools-wb/pull/304 however due to the code-base differences between ```master``` and ```6.5.x``` the change is required in ```kie-wb-common``` (and was in essence a re-write of the fix!)

[6.5.x] RHBRMS-2610: Guided Decision Table Editor: Add support for caching enumeration lookups

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/validation/asset/ValidatorBuildService.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/validation/asset/DefaultGenericKieValidatorTest.java

See https://issues.jboss.org/browse/GUVNOR-2718
Note: This is a duplication of GUVNOR-2682 (which was fixed on master)
(cherry picked from commit 133dd6c60b7cd62eef56e70351d8fd06fa0c3d3e)

[6.5.x] GUVNOR-2718: Validate: Validating a rule with changes that have not been saved gives and error for duplicate rule name

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/pom.xml
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/pom.xml
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/pom.xml
kie-wb-common-screens/kie-wb-common-search-screen/kie-wb-common-search-screen-api/pom.xml
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
kie-wb-common-screens/kie-wb-common-social-home-page/kie-wb-common-social-home-page-client/pom.xml

The reason for these changes is that Maven 3.4.0 will fail the build in case of duplicated deps (instead of just logging WARNing message as previous versions).

Remove duplicated deps in POMs

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml

* the code does not import any classes from there and it is being
brought in transitively via kie-server-client

server-ui-backend: direct dependency on kie-remote-common is not needed

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/KieDefaultWorkbenchClient.gwt.xml

Fixes compilation issues after https://github.com/uberfire/uberfire/pull/541/ had been merged.
`[INFO]    Tracing compile failure path for type 'org.kie.workbench.common.workbench.client.admin.DefaultAdminPageHelper'
[INFO]          [ERROR] Line 50: No source code is available for type org.uberfire.ext.security.management.client.ClientUserSystemManager; did you forget to inherit a required module?
[INFO]          [ERROR] Line 64: No source code is available for type org.uberfire.ext.security.management.api.AbstractEntityManager<T,S>.SearchResponse<T>; did you forget to inherit a required module?
[INFO]          [ERROR] Line 68: No source code is available for type org.uberfire.ext.security.management.impl.SearchRequestImpl; did you forget to inherit a required module?`

kie-wb-common-workbench-client: Update module descriptor after UF-320

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/ruleselector/RuleSelector.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/ruleselector/RuleSelectorDropdown.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/ruleselector/RuleSelectorDropdownTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/ruleselector/RuleSelectorTest.java

See https://issues.jboss.org/browse/GUVNOR-2735
This PR adds ```HasEnabled``` to the ```RuleSelector``` widget.

GUVNOR-2735: Guided Decision Table Editor: When opening an empty 'Graph' the editor is not populated

---

kie-wb-common-stunner/pom.xml

Stunner Showcase causes a dependency of kie-wb-common on drools-wb, which is wrong.
See BSIG mailing list for details.

Ignore Stunner Showcase webapp

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/src/main/resources/org/kie/workbench/common/stunner/project/StunnerProjectShowcase.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/resources/org/kie/workbench/common/stunner/standalone/StunnerStandaloneShowcase.gwt.xml
kie-wb-common-stunner/pom.xml

Hi @csadilek @manstis @Rikkola ,
Here is the fix for the showcase modules. In fact the dependency to the drools-wb was not necessry, it was my mistake, sorry guys. I have done a complete review for the dependencies, fixed some and hope no more issues due to this will appear... sorry for the inconveniences again.
See https://issues.jboss.org/browse/JBPM-5394
Thanks!

JBPM-5394: Removing wrong dependencies to drools-wb assets.

---

pom.xml

This is the corollary of https://github.com/droolsjbpm/kie-wb-common/pull/555 for 6.5.x
(cherry picked from commit 8f7c1d49d1873c914e34cab44e91fb5f010fa4bf)

[6.5.x] Include 'zh_CN' locale in Replacer Plugin configuration

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/kmodule/converters/KModuleConverter.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/kmodule/KModuleContentHandlerTest.java

See https://issues.jboss.org/browse/RHBRMS-2689
See also https://github.com/droolsjbpm/drools/pull/1004 and https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/187
The Workbench also needs to use the "version-less" Name Space (for new Projects). Older Projects created in the Workbench are tied to 6.0.0 XSD and hence, if the fix for RHBRMS-2689 is needed in older versions, the old 6.0.0 XSD would need updating too :-(
See https://issues.jboss.org/browse/DROOLS-1023

RHBRMS-2689: Unable to build project if kbase and ksession names are identical

---

pom.xml

@mbiarnes Hi.. this should fix https://github.com/droolsjbpm/kie-wb-common/pull/554
I'd suggest closing https://github.com/droolsjbpm/kie-wb-common/pull/554, running the i18n again for ```kie-wb-common``` and submitting a new PR.

Include 'zh_CN' locale in Replacer Plugin configuration

---

kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-backend/src/test/java/org/kie/workbench/common/screens/datasource/management/backend/core/DataSourceManagementTestConstants.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-wildfly/src/main/java/org/kie/workbench/common/screens/datasource/management/backend/core/wildfly/DeploymentIdGenerator.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-wildfly/src/test/java/org/kie/workbench/common/screens/datasource/management/backend/core/wildfly/DeploymentIdGeneratorTest.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-wildfly/src/test/java/org/kie/workbench/common/screens/datasource/management/backend/core/wildfly/WildflyDriverProviderTest.java

- changes the deployment id separator to avoid WF conflicts in windows systems

JBPM-5233: Data source management

---

kie-wb-common-services/kie-wb-common-services-backend/pom.xml
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/helpers/AbstractInvalidateDMOPackageCacheDeleteHelper.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/helpers/AbstractInvalidateDMOPackageCacheDeleteHelperTest.java

See https://issues.jboss.org/browse/GUVNOR-2820
This PR adds a base class to invalidate the LRUDataModelOracleCache when certain files are deleted.

GUVNOR-2820: Enumerations are present even if they were deleted

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/pom.xml

We just need the annotations to satisfy WELD. No need to drag in
the whole gwt-user jar (which bundles the annotations as well).
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/347

[DROOLS-1391] no need to depend on gwt-user 

---

kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-api/src/main/java/org/kie/workbench/common/services/refactoring/model/index/ResourceReference.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/impact/ResourceReferenceCollectorTest.java

See https://issues.jboss.org/browse/GUVNOR-2831
Method ```addPartReference( Map )``` assumes method ```addPartReference( String, PartType )``` has been called to initialise the internal map instance. You know what is said about assuming things..

GUVNOR-2831: [Guided Decision Table] Two BRL Condition fragments throws Indexing Exception

---

kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorRestoreTest.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorTest.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditorTestBase.java

https://issues.jboss.org/browse/GUVNOR-2841
A bug I found while fixing a bug that was found when fixing a bug.
`KieMultipleDocumentEditor` has the one line fix. I split the `KieMultipleEditorest` to an abstract base to make the class a bit shorter. The only new test I actually added is `KieMultipleDocumentEditorRestoreTest.restoreMakesTheDocumentEditable()`

GUVNOR-2841 : Guided Decision Table: Restored dtable should not be read only

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/DataModelServiceConstructorTest.java

Further to https://github.com/droolsjbpm/kie-wb-common/pull/658
```droolsjbpm/master@kie-wb-common``` is failing in our CI environment at the moment.
```KieResourceResolver``` attempts to store Projects' permissions in ```system.git```. This fix simply overrides ```KieResourceResolver.addSecurityGroups()``` to avoid use of ```system.git```. The test demonstrates use of DMO outside a WELD evironment (for use with the Eclipse tooling integration by @bbrodt )

RHBPMS-4604: Fix DataModelServiceConstructorTest

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/widget/artifact/ArtifactListWidgetPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/widget/artifact/ArtifactListWidgetPresenterTest.java

There was inconsistency in searching of available artifacts. This PR inludes file extension to search criteria. Before this PR the file extension was replaced by null value what probably caused duplication of entries in list of available artifacts.

JBPM-5632: Search artifacts both by name and file extension

---

kie-wb-common-services/kie-wb-common-data-modeller-core/src/test/java/org/kie/workbench/common/services/datamodeller/codegen/GenerationEngineTest.java
kie-wb-common-services/kie-wb-common-data-modeller-core/src/test/java/org/kie/workbench/common/services/datamodeller/parser/JavaFileHandler1Test.java

When we run community tests against productized binaries on Windows, there are some Windows specific test failures. Most of these failures are caused by line separators and file paths. There will be some more fixes also in other repositories. 
This commit contains some minor changes in tests that replace \n separator by the OS specific separator.

fix Windows specific test failures

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-processors/src/main/java/org/kie/workbench/common/stunner/core/processors/AbstractAdapterGenerator.java

This should fix the the following error, sometimes seen in the build:
External error in org.kie.workbench.common.stunner.core.processors.MainProcessorjava.lang.ExceptionInInitializerError
at freemarker.template.ObjectWrapper.<clinit>(ObjectWrapper.java:69)
at freemarker.core.Configurable.<init>(Configurable.java:139)
at freemarker.template.Configuration.<init>(Configuration.java:142)
at freemarker.template.Configuration.<clinit>(Configuration.java:127)
at org.uberfire.annotations.processors.AbstractGenerator.<init>(AbstractGenerator.java:44)
at org.kie.workbench.common.stunner.core.processors.rule.ContainmentRuleGenerator.<init>(ContainmentRuleGenerator.java:43)
at org.kie.workbench.common.stunner.core.processors.MainProcessor.<init>(MainProcessor.java:194)
The same change was done in UF …

Synchronize Freemarker setup to avoid concurrency issues

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-api/pom.xml
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenterTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenterTestBase.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/widgets/DataModelerEditorsTestHelper.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-client/src/main/java/org/kie/workbench/common/screens/datasource/management/client/util/PopupsUtil.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/BaseViewPresenter.java
kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/validation/CopyValidator.java
kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/validation/SaveValidator.java
kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/validation/ValidationService.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/validation/ValidationServiceImpl.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/validation/ValidationServiceImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationMessageTranslator.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationMessageTranslatorUtils.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationPopup.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationPopupView.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationPopupViewImpl.html
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationPopupViewImpl.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/resources/i18n/KieWorkbenchWidgetsConstants.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/client/resources/i18n/KieWorkbenchWidgetsConstants.properties
kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/client/resources/i18n/ValidationConstants.properties
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationMessageTranslatorUtilsTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/popups/validation/ValidationPopupTest.java

Introduce pre-save & pre-copy checks to make sure the user doesn't create multiple Planning Solutions within a project. The checks reside on the server side and can be easily defined by implementing PreSaveOperationCheck & PreCopyOperationCheck classes.
DataModelerOperationCheckService provides methods to verify all conditions (checks) in a single place.
As the checks are performed on the server side, there was a need to provide mapping between the server-side messages & client-side messages (where the latter are i18ned). This is managed by OperationCheckTranslator class.
Part of:
https://github.com/droolsjbpm/guvnor/pull/416
https://github.com/droolsjbpm/jbpm-wb/pull/630
https://github.com/droolsjbpm/kie-wb-common/pull/681
https://github.com/droolsjbpm/optaplanner-wb/pull/134
@manstis / …

PLANNER-736: Workbench: Prevent user from creating multiple @PlanningSolution data objects

---

kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetPresenter.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetView.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetViewImpl.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetPresenterTest.java

See https://issues.jboss.org/browse/GUVNOR-2856
GWT's ```onBrowserEvent``` was throwing a RTE when the ```ButtonCell``` had no rendered content.
It is a general problem for the "Data Object imports" tab and not specific to Guided Decision Tables.
See https://github.com/droolsjbpm/kie-wb-common/pull/689/files?w=1 with whitespace diffs removed.

GUVNOR-2856: [Guided Decision Table] Remove import throws exception

---

kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/indexing/PackageDescrIndexVisitor.java

```org.drools.compiler.lang.descr.UnitDescr``` descriptor was added for "RuleUnit" support in ```drools-compiler``` however ```PackageDescrIndexVisitor``` was not updated accordingly.

Fix failing PackageDescrIndexVisitorLogicTest.visitLogicTest() test.

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/pom.xml
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/docks/AuthoringWorkbenchDocks.java

Hey @manstis @pefernan @mbiarnes 
This commit fixes the wrong dependency from the workbench client module to stunner.
Thanks!

Remove transitive  dependency to Stunner.

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/KieDefaultWorkbenchClient.gwt.xml

Hey @mbiarnes @manstis @pefernan @Rikkola ,
Sorry guys, I forgot to remove the gwt module dependency as well in [this already merged PR,](https://github.com/droolsjbpm/kie-wb-common/pull/708) so here is the fix for it. 
PS: It has been impossible for me, during this weekend, to do a full build for master, I'm facing with some compile issues and all seems up to date, so still not sure if it's just my local or something is bad on the repos... Anyway I say this because I was NOT  been able to test this commit - I expect making the repositories compile again, and for the jbpm-wb module  (which still does not depend on Stunner), the docks will appear on the showcase but probably will fail once trying to open it at runtime (as the hardcoded screen ids used for docks should not be present). …

Remove transitive gwt module dependency to Stunner.

---

kie-wb-common-stunner/kie-wb-common-stunner-backend/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/pom.xml
kie-wb-common-stunner/pom.xml

With this changes it is possible to check is new PR decreases test coverage of Stunner.
To run jacoco plugin run [1] on project root. If test-coverage were decreases it will fail (only profile [1], regular build will be successful). If test-coverage didn't decreased you can found test-coverage reports in target/site/jacoco (for project with any tests).
[1]
```
mvn clean verify -Dcode-coverage
```
Known issue:
Tests with mock are not counting due to conflicts between current Jacoco and mock versions. This issue in progress.

Stunner - jacoco plugin configurations to notify about decreased test coverage

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-api/src/main/java/org/kie/workbench/common/stunner/bpmn/project/factory/impl/BPMNProjectDiagramFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/definition/BPMNDiagram.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/util/CaseManagementUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-backend/src/main/java/org/kie/workbench/common/stunner/cm/backend/CaseManagementDiagramMarshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-api/src/main/java/org/kie/workbench/common/stunner/cm/project/factory/CaseManagementProjectDiagramFactory.java

See https://issues.jboss.org/browse/JBPM-5790
Following https://github.com/kiegroup/kie-wb-common/pull/737 @hasys reports it is no longer possible to open BPMN diagrams into Stunner/BPMN editor. I replicated the issue using the same steps as @hasys (although could not replicate using InteliJ). The problem was traced to CM's ```BPMNDiagram``` extending BPMN's ```BPMNDiagram```.

JBPM-5790: Case Modeller: Change containment rules for Diagram and Stages

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-adf/kie-wb-common-forms-adf-engine/kie-wb-common-forms-adf-engine-api/src/test/java/org/kie/workbench/common/forms/adf/engine/shared/formGeneration/processing/fields/fieldInitializers/TextAreaFieldInitializerTest.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-adf/kie-wb-common-forms-adf-engine/kie-wb-common-forms-adf-engine-api/src/test/java/org/kie/workbench/common/forms/adf/engine/shared/formGeneration/processing/fields/fieldInitializers/selectors/SelectorFieldInitilizerTest.java

TextAreaFieldInitializerTest increases coverage of HasPlaceholderInitializer and HasRowsFieldInitializer classes. SelectorFieldInitilizerTest increases coverage of SelectorFieldInitilizer class.

increase coverage in kie-wb-common-forms-adf-engine-api

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/icons/svg/SVGIconRendererViewImpl.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/icons/svg/SVGIconRendererViewImpl.java

Fixes a CSS issue that makes some SVG look bad on the palette.
@romartin can you take a look?

JBPM-5802: fixing styling to make icons don't appear cropped on the palette

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/WiresContainerShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/WiresContainerShapeViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/PictureShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/PictureUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/glyph/PictureGlyph.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/test/java/org/kie/workbench/common/stunner/shapes/client/view/PictureShapeViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/test/java/org/kie/workbench/common/stunner/shapes/client/view/PictureUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/test/java/org/kie/workbench/common/stunner/shapes/client/view/glyph/PictureGlyphTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/BS3PaletteGlyphViewFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/BS3PaletteViewFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/BindableBS3PaletteGlyphViewFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/AbstractSessionPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/AbstractSessionViewer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/tooltip/DefinitionGlyphTooltipImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/BS3PaletteGlyphViewFactoryTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/palette/factory/BindableBS3PaletteGlyphViewFactoryTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionViewerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/tooltip/DefinitionGlyphTooltipImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/shape/factory/CaseManagementShapesFactoryImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/wires/AbstractCaseManagementShape.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/shape/factory/CaseManagementDelegateShapeFactoryTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/wires/MockCaseManagementShape.java

See https://issues.jboss.org/browse/JBPM-5828
Whilst adding icons I noticed some DOM leaks regarding glyphs (used for the icons) and fixed those too.
The leaks fixes probably relate to https://issues.jboss.org/browse/JBPM-5462

JBPM-5828: Case Modeller: Stages and Activities to use icons

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryView.less

The fix to [GUVNOR-2968](https://issues.jboss.org/browse/GUVNOR-2968) depends on [this PR](https://github.com/uberfire/uberfire/pull/653) too, but both PRs can be merged independently.

GUVNOR-2968: [Library] Remove margin above Messages panel

---

kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-data-modeller-integration/kie-wb-common-forms-data-modeller-integration-client/src/main/java/org/kie/workbench/common/forms/data/modeller/client/formModel/DataObjectFormModelCreationViewImpl.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/main/java/org/kie/workbench/common/forms/jbpm/client/formModel/JBPMFormModelCreationPresenterManager.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/main/resources/org/kie/workbench/common/forms/jbpm/client/resources/i18n/Constants.properties
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/test/java/org/kie/workbench/common/forms/jbpm/client/formModel/JBPMFormModelCreationPresenterTest.java

JBPM-5579: Data objects in the data source dropdown disappear on the second select of the radio button.
JBPM-5532: Form definition name in the new item dialog gets deleted on data source select.
@wmedvede can you take a look please?

JBPM-5532 & JBPM-5579: Fixing new Form popup bugs

---

kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/relations/subform/SubFormFieldRenderer.java

Setting the rendering mode of the subform widget to read only mode, when the field is set to read only.
@pefernan can you review please?

JBPM-5603: setting the rendering mode of the subform widget to read only mode, if the field is set to read only

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/docks/AuthoringWorkbenchDocks.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/docks/AuthoringWorkbenchDocksTest.java

See https://issues.jboss.org/browse/GUVNOR-3030
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/798 for 7.0.x
(cherry picked from commit c5cb87153a4ba08a0b33e4d2f34868b4d6e7eda8)

[7.0.x] GUVNOR-3030: Resizing Project Explorer Dock throws NPE

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImplTest.java

Playground repository cloning is a costly operation, make sure it's not done repeatedly when querying for a list of available projects within the repository (e.g. when opening example import wizard multiple times)
@manstis Could you please review the PR? Thanks in advance

GUVNOR-3032: Example import: Optimize playground repository cloning

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImpl.java

Replace Files.delete by File.delete to avoid AccesDeniedExceptions if directory is marked as read-only (windows-related).

GUVNOR-3038: [Library] Import examples not working

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml

Hey @manstis @hasys ,
The stunner's showcase was not starting due to some missing class dependencies to Dashbuilder, here is a fix for it.
Thanks!!

Stunner showcase - Added missing dashbuilder dependencies.

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenter.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenterRefreshTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenterTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenterTestBase.java

See https://issues.jboss.org/browse/RHBPMS-4564
Before (or [see the video](https://drive.google.com/a/redhat.com/file/d/0B4qIOCgZfb2eeG4zN0c3Y19vN2s/view?usp=sharing)):
After:

[6.5.x] RHBPMS-4564: Cloning managed repo as unmanaged causes menu on project editor displays different options for user using same roles in BxMS 6

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenButtonDisableEnableTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenReloadTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenSequentialLoadRequestTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenTestBase.java

See https://issues.jboss.org/browse/GUVNOR-3058
This fixes use of "key down" to activate filtering of the Project asset list; consistent with the other "filters".
I added a couple of tricks to prevent the server being flooded with requests for assets as the User types:
1. Only make the server call after a timer (250ms) has elapsed to cater for a User typing quickly
2. Only invoke the server call after any "in progress" calls have completed; thus as a User is typing and the timer expires triggering a server call successive changes to the filter do not invoke new server calls until the first completes. 
This also fixes the width of the "page size" selector.

GUVNOR-3058: Asset list search / paging issues

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/wizard/container/NewContainerFormPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/wizard/container/NewContainerFormView.html
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/wizard/container/NewContainerFormView.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/resources/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.properties
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/wizard/container/NewContainerFormPresenterTest.java

depends on https://github.com/kiegroup/droolsjbpm-integration/pull/948
this PR introduces new checkbox on the new container wizard to allow directly start the container when created

RHBPMS-4375 - Container is not started when being created

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/EmptyProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/EmptyProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/NewProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/OrganizationalUnitsView.html
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourceViewImpl.html

See https://issues.jboss.org/browse/GUVNOR-3043 and https://issues.jboss.org/browse/GUVNOR-3066
Use of ```<button>``` inside ```<form>``` elements leads to the form being resubmitted when either the ```<enter>``` key is pressed or the User clicks the ```<button>``` element. This is expected behaviour (and correctly implemented by Chrome).
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/854 for 7.0.x
(cherry picked from commit 888ea4130accb13298389365da0a2f528bd6af26)

[7.0.x] GUVNOR-3066: GUVNOR-3043: Workbench reloading on User interactions.

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/EmptyProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/EmptyProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/NewProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/OrganizationalUnitsView.html
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourceViewImpl.html

See https://issues.jboss.org/browse/GUVNOR-3043 and https://issues.jboss.org/browse/GUVNOR-3066
Use of ```<button>``` inside ```<form>``` elements leads to the form being resubmitted when either the ```<enter>``` key is pressed or the User clicks the ```<button>``` element. This is expected behaviour (and correctly implemented by Chrome).
See:
http://stackoverflow.com/questions/23420795/why-would-a-button-click-event-cause-site-to-reload-in-a-bootstrap-form
http://stackoverflow.com/questions/17406320/enter-key-reloads-chrome-browser

GUVNOR-3066: GUVNOR-3043: Workbench reloading on User interactions

---

kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/pom.xml
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/main/java/org/kie/workbench/common/forms/jbpm/server/service/impl/BPMNFormModelGeneratorImpl.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/test/java/org/kie/workbench/common/forms/jbpm/server/service/impl/BPMNFormModelGeneratorImplTest.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/test/resources/definitions/process-with-all-possible-variables.bpmn2
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-backend/src/test/resources/definitions/process-without-variables.bpmn2

Tests generateProcessFormModel, generateTaskFormModels and generateTaskFormModel methods on two valid process definitions loaded from resources.
Part of this commit is also cleanup of the unused private class TaskVariableSetting from the BPMNFormModelGenerator.
@pefernan, @manstis could you please review?
@pefernan, there are two tests ignored because of the JBPM-5977. Could you please unignore them later in the pull-request fixing the bug?

create integration test for BPMNFormModelGenerator

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/command/DataModelCommandBuilder.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/command/RemovePropertyCommand.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/DomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/advanceddomain/AdvancedDomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/droolsdomain/DroolsDomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/jpadomain/JPADomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/handlers/maindomain/MainDomainHandler.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/editor/DataObjectBrowser.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/widgets/editor/DataObjectBrowserViewImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/command/RemovePropertyCommandTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/widgets/editor/DataObjectBrowserTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/widgets/editor/DataObjectBrowserViewImplTest.java

- Ignore getter/setter creation for generated attributes (generators need to add those manually)
- Add data object field remove command
- Object editor - Disable remove button for generated fields
@wmedvede As this impacts the data modeler, could you please take a look? Thanks. I haven't formatted all the code yet, so that the changes are visible at first glance.
Part of:
- https://github.com/kiegroup/kie-wb-common/pull/869
- https://github.com/kiegroup/optaplanner-wb/pull/158
- https://github.com/kiegroup/kie-wb-playground/pull/23

PLANNER-784: Workbench: AbstractSolution.score can't be marshaled when using JAXB

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryAssetTypeDefinition.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/LibraryAssetTypeDefinitionTest.java

See https://issues.jboss.org/browse/GUVNOR-3083
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/883 for 7.0.x
(cherry picked from commit 41fe528630fe7bd876c27489044e725cd6e7dbea)

[7.0.x] GUVNOR-3083: Library: Indexer should not index folders

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreen.java

(cherry picked from commit ac2baf838210b76c4d297206df6f34df1b288c82)
Related to #890 
And another fix that should still go in.

[7.0.x] GUVNOR-3089 : Workbench: Asset list is not complete after importing a project

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/index/LibraryFileNameIndexTerm.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/index/LibraryValueFileNameIndexTerm.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/FindAllLibraryAssetsQuery.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryIndexer.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/BaseLibraryIndexingTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/FindAllLibraryAssetsQueryTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/ListAssetsTest.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/main/java/org/kie/workbench/screens/workbench/backend/impl/DefaultLuceneConfigProducer.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/test/java/org/kie/workbench/screens/workbench/backend/impl/DefaultLuceneConfigProducerTest.java

See https://issues.jboss.org/browse/GUVNOR-3107
You won't be able to test this "live" without merging https://github.com/kiegroup/kie-wb-common/pull/881 locally (as there's no way to perform a "meta-data" search in the Workbench at the moment... however I found this issue when furthering my work for GUVNOR-3082 and thought better to fix now than - forget - later).

GUVNOR-3107: [Library] Indexer: Duplicates results of searches

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValues.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValuesTest.java

This Jira and PR were created because the same problem was recently fixed in Designer.
@romartin  , @hasys  Will you review please. Today is my last day, so if it needs changes will one of you make the necessary changes. (Hopefully none will be needed!). Thanks.

JBPM-6035: Show added constants only for current row in DataIOEditor

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspective.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspectiveTest.java

Hi @jhrcek, if you could check if the issue is gone, please. Thanks!

GUVNOR-3114: [Library] Proj.exp initialization causes random project to be loaded when returning to library from other perspectives

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/DeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/command/DeleteNodeCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/SafeDeleteNodeProcessor.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/SafeDeleteNodeProcessorTest.java

Hey @manstis @hasys 
This commit fixes these two bugs: [JBPM-6006](https://issues.jboss.org/browse/JBPM-6006) and [JBPM-6076](https://issues.jboss.org/browse/JBPM-6076). 
It basically removes the connectors (in some cases) instead of setting empty source/target connections. 
Thanks!

JBPM-6006 & JBPM-6076: Fixings for connectors when removing nodes.

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDiagramMarshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/marshall/json/Bpmn2Marshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDiagramMarshallerTest.java

@romartin , @hasys   This is incomplete but I think worth committing at this point. I've changed some of the 'testMarshall...' tests so that checks are made against the Eclipse BPMN2 API objects which are created by the marshaller, rather than testing against strings in the output XML. The advantage is that in many cases, the tests are no longer testing for matching UUID's, so it's much easier to update existing bpmn test files and test cases when necessary. When the tests were for matching UUID's, all UUID's for that test case would need to be updated if a change to the test process was made.

JBPM-5978: Improve marshalling tests in BPMNDiagramMarshallerTest

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/pom.xml
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/resources/org/kie/workbench/common/screens/datamodeller/client/resources/i18n/Constants.properties
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/pdescriptor/ProjectClassListTest.java

I did the following changes:
1. I changed the message that is displayed in the text box for entering persistable classes in the Persistence Descriptor Editor. In my opinion, the original message was not sufficiently informative.
2. I added three more unit tests that test the `void onLoadClass()` method.
3. I reformated the code in the `ProjectClassListTest` class using the KIE Java Conventions.
4. I fixed the order of parameters of the `assert` methods (was incorrectly `actual, expected`, while it should be `expected, actual`.) EDIT: AssertJ was used instead.
@wmedvede, could you please have a look?

Improve persistence descriptor editor coverage

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/Point2D.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/builder/impl/AbstractElementBuilderControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/toolbox/command/builder/NewNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtilsTest.java

Hi @romartin ,
this is the commit for the following tickets:
[Stunner - New elements added to business process have alignment to the top border 
](https://issues.jboss.org/browse/JBPM-5448
)
[Stunner - possibility to add several nodes after gateway without node moving
](https://issues.jboss.org/browse/JBPM-5811
)
[Stunner - Append new element doesn't work for elements inside Swimlanes
](https://issues.jboss.org/browse/JBPM-5501
)
Can you please review this PR?
Thanks.

JBPM-5448 & JBPM-5811 & JBPM-5501: Improved evaluation of the next available position for newly added Graph elements.

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/FindAllLibraryAssetsSortedQueryTest.java

See https://issues.jboss.org/browse/GUVNOR-3242
This PR simply increases the separation between the two tests in the class.

GUVNOR-3242: Fix intermittent failing FindAllLibraryAssetsSortedQueryTest

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/toolbox/AbstractToolboxControlProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/toolbox/FlowActionsToolboxControlProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/toolbox/command/builder/NewNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/toolbox/FlowActionsToolboxControlProviderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/lookup/util/CommonLookups.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/lookup/util/CommonLookupsTest.java

See https://issues.jboss.org/browse/GUVNOR-3220
@romartin This moves the fix for always using "default connector" in ```AddNodeCommand``` to ```master``` which also includes the fix to ```CommonLookups``` that did not check if an "allowed connection" (to a target node) originated from the "source node". 
It _might_ interfere with https://github.com/kiegroup/kie-wb-common/pull/948 as we;'ve both dabbled with ```AddNodeCommand```.

GUVNOR-3220: [DMN Editor] FlowActionsToolboxControlProvider always uses a 'default' connector

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/diagrams/DiagramNavigatorItemImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/item/NavigatorThumbnailItemView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/diagrams/DiagramNavigatorItemImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/item/NavigatorThumbnailItemViewTest.java

See https://issues.jboss.org/browse/GUVNOR-3247
The problem was that the size was set before the browser had loaded the image and hence; on the "first view" the preview was not re-sized. However when it had loaded the ```Image``` in the ```DOM``` held the full size image.

[Stunner] List of diagrams is not rendered correctly when first loading previews

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/main/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenModelSaver.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenModelSaverTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenServiceImplTest.java

See https://issues.jboss.org/browse/GUVNOR-3261
The problem was that the ```LRUPomModelCache``` may not be invalidated by a ```InvalidateDMOProjectCacheEvent``` (raised by VFS observing a change to the ```pom.xml```) until **after** the ```KieBuilder``` (used to perform the build) is instantiated and ```PomModel``` set (if found to be cached). The ```PomModel``` controls the GAV in the build.

GUVNOR-3261: Wrong version pom.properties is contained in kjar

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/runtime/AsyncKieServerInstanceManager.java

Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/995

[6.5.x] RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/runtime/AsyncKieServerInstanceManager.java

See https://issues.jboss.org/browse/RHBRMS-2874
Before:
After:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1073
- https://github.com/kiegroup/kie-wb-common/pull/995

RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/test/java/org/kie/workbench/common/forms/editor/backend/indexing/FormDefinitionIndexerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/indexing/BpmnFileIndexerTest.java

Hi @pefernan, @romartin,
I used IntelliJ _rerun until fail_ feature to test my fix. And this test passed about 100 times in a row without any problem. Without fix it failed in first 5 execution. So, I hope, it will help.

Fix for random fails in Indexer tests.

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/runtime/AsyncKieServerInstanceManager.java

Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/995
---
- https://github.com/kiegroup/kie-wb-common/pull/1002
- https://github.com/kiegroup/droolsjbpm-integration/pull/1082

[7.2.x] RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/FieldPropertiesRendererViewImpl.java

@pefernan @jsoltes this is the same as https://github.com/kiegroup/kie-wb-common/pull/1006, pointing to the **7.2.x** branch

JBPM-5425 Unnecessary field type selector when there is only one field type to select

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/slider/definition/DoubleSliderDefinition.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/relations/multipleSubform/definition/MultipleSubFormFieldDefinition.java

There was some wrong setting on the @FormField annotations for that classes. Fixed
@jsoltes could you review?

[8.0.x] JBPM-6284: Slider and Multiple SubForm break the consistency with "ReadOnly" and "ValidateOnChange" labels.

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorPresenter.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorPresenterTest.java

@pefernan @jsoltes could you please give a look?
**WARNING**: to be merged with  https://github.com/kiegroup/kie-wb-common/pull/1021

JBPM-5917 Change the order of "Tools" and data object/process variable dropdown

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml

Cherrypick of the commit 49d1526c8a110a72c749c173aa2c43e8ed1b9674 to portback to 7.2.x
Referred PR on **Master**
https://github.com/kiegroup/kie-wb-common/pull/992
@romartin 
@manstis

[7.2.x] JBPM-6265 : Inserting missed dependencies on stunner project showcase

---

kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/IndexingTest.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/drl/IndexDrlLHSTypeExpressionFieldCombinedTest.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/drl/IndexDrlLHSTypeFieldTest.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/drl/IndexDrlLHSTypeTest.java

Hi @manstis,
There are tree changes:
- Increase wait time (will fix ~ 4% of random fails)
- Use FS Batch operation (will fix ~ 80% of random fails)
- shadow the Uberfire bug. I will send a PR directly to Uberfire to test it. After that I will make a same PR (with Set instead of List) for Forms and Stunner. (have to fix the rest ~ 15%) of fails
P.S. But there are still small chance for random fail in case of sleep time won't be enough.

Index test stabilization

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

@romartin just removing the shared dependency that is not necessary on the showcase standalone module in response to the comment on: https://github.com/kiegroup/kie-wb-common/commit/a33699b8e0d6b64ec6a946449e80af960124a1c8#commitcomment-23545859

JBPM-6103 Fix removing unnecessary depencency from showcase standalone

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/slider/definition/DoubleSliderDefinition.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/relations/multipleSubform/definition/MultipleSubFormFieldDefinition.java

There was some wrong setting on the @formfield annotations for that classes. Fixed
@jsoltes could you review?

[7.2.x] JBPM-6284: Slider and Multiple SubForm break the consistency with "ReadOnly" and "ValidateOnChange" labels.

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Portback the fix of JBPM-6103, the original PR is https://github.com/kiegroup/kie-wb-common/pull/1054/ to 7.2.x.
The referred commit is 56390b3db9a1538d66d5009fcae157c59bc7a9d1.
@romartin 
@manstis

[7.2.x] JBPM-6103 Fix removing unnecessary depencency from showcase standalone 

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/DMNCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/DeleteCellValueCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/NavigateToDRGEditorCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/NavigateToExpressionEditorCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/SetCellValueCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/SetExpressionTypeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/VetoExecutionCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/VetoUndoCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/command/impl/ClearSessionCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/command/impl/SessionCommandFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/presenters/session/impl/SessionPresenterFactoryImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/command/ClearToolbarCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/command/ToolbarCommandFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/impl/EditorToolbarFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/DeleteCellValueCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/NavigateToDRGEditorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/NavigateToExpressionEditorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/SetCellValueCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/SetExpressionEditorDefinitionCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/command/impl/ClearSessionCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/ClearSessionCommand.java

See https://issues.jboss.org/browse/GUVNOR-3354
This PR adds a new ```SessionCommandFactory``` for the DMN Editor; with a ```ClearSessionCommand``` that does not respond to DMN-centric events that would lead to the Toolbar button becoming enabled.

GUVNOR-3354: [DMN Editor] Toolbar: Add support for using different SessionCommandFactory

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/presenters/impl/SessionPresenterFactoryImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/presenters/impl/SessionPreviewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/BaseCommandsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/command/impl/ClearSessionCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/presenters/impl/SessionPreviewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/preview/SessionDiagramPreviewScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPreviewImpl.java

See https://issues.jboss.org/browse/GUVNOR-3356
This PR adds a different ```SessionPreviewImpl``` implementation for the DMN Editor that does not replay commands implementing ```DMNCommand```. There will be no tangible differences from a Users perspective. If however you were to put a break point in (for example) ```NavigateToExpressionEditorCommand.execute()``` you'd notice it is now only executed once. Previously it was executed twice: Once for the main "view" and again for the "preview".

GUVNOR-3356: [DMN Editor] Add support for filtering events

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/annotation/RuntimePropertyAdapter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/EmbeddedSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/forms/model/ComboBoxFieldDefinition.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/forms/model/ConditionalComboBoxFieldDefinition.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/forms/model/ConditionalComboBoxFieldType.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/forms/service/fieldProviders/ConditionalComboBoxFieldProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/util/MultipleFieldStringSerializer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/util/MultipleFieldStringSerializerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/AbstractComboBoxFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ComboBoxFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ComboBoxFixedValuesWidgetView.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ComboBoxFixedValuesWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ConditionalComboBoxFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/annotation/FixedValues.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/AbstractComboBoxFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ComboBoxFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ConditionalComboBoxFieldRendererTest.java

The second part of this issue related to the **Script Language** that was not being persisted, in fact the problem is that scricpt laguage is an attribute of the **onEntryAction** and **onExitAction** fields, in this way, the user is only able to select a script language in case the **onEntryAction** and **onExitAction** are filled with values and not empty. 
For this it was implemented a Conditional ComboBox that is only enabled due to a condition of other fields being filled before.
Some refactory needed to be made to support this component and make the existing code more clear.
@romartin

JBPM-6103 Stunner - Script Language values are not persist to Embedded subprocess

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java

Now the diagram title on the Stunner Diagram Editor is displayed on the proper format.
Basically it was implemented a method to format the tittle on the **AbstractProjectDiagramEditor** and the concrete classes may override the format if necessary.
@manstis 
@hasys

JBPM-5537: Stunner - Workbench editor name have no extension and asset type

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/slider/definition/DoubleSliderDefinition.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/relations/multipleSubform/definition/MultipleSubFormFieldDefinition.java

This is a cherrypick from 7.2.x (https://github.com/kiegroup/kie-wb-common/pull/1040).
@manstis could you please review?

[7.3.x] JBPM-6284: Slider and Multiple SubForm break the consistency with "ReadOnly" and "ValidateOnChange" labels.

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/gateway/DefaultRouteFormProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/gateway/DefaultRouteFormProviderTest.java

Now it is possible to open the Exclusive Gateway properties panel.
The problem was that the **DefaultRouteFormProvider** was using a **TreeMap** implementation to provide SelectorData to the Combobox of the DefultRoute property.
The methods **get(key)** and **containsKey(key)** of the **TreeMap** class throws NullPointerException whether the key parameter is null. The HashMap doesn't throw Exception in case key is null.
Reference:
https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html
@hasys 
@manstis

JBPM-6304 Stunner - gateway doesn't show properties

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/components/palette/widget/DMNPaletteWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/presenters/impl/SessionPresenterFactoryImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/PaletteWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/SessionPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/AbstractSessionPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterFactoryImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorPresenterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/annotation/DiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenEventPublisher.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenMaximizedEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenMinimizedEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenResizeEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenResizeEventObserver.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenEventPublisherTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/docks/StunnerDocksHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/SessionDiagramEditorScreen.java

Now the palette is being hidden when screens are maximized unless it is a diagram editor.
It was added an DiagramEditor annotation to identify screens that contains diagram editor and observer/publisher of this events.
SessionEditorPresenter is responsible to hide the palette based on the screen resize events.
StunnerDocksHandler hide docks when diagram is maximized, just used in project, not on standalone.
If you have any  questions or suggestions, it is always welcome.
@jomarko 
@hasys 
@manstis

GUVNOR-3357 Full screen Preview does not hide Palette

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/DMNBaseGridWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionEditorViewImplTest.java

See https://issues.jboss.org/browse/GUVNOR-3198
---
- https://github.com/AppFormer/uberfire/pull/808
- https://github.com/kiegroup/drools-wb/pull/583
- https://github.com/kiegroup/kie-wb-common/pull/1110

GUVNOR-3198: [Guided Decision Table] Visual indication where the current view of Decision Table is located

---

kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/date/DatePickerFieldRenderer.java

Copy of https://github.com/kiegroup/kie-wb-common/pull/1123
There was two issues here:
a JS error going on when the component floating div was added to the DOM because the container for it wasn't initialized.
a CSS issue when displaying the DatePicker floating div appear on scroll bars instead of overflow the layout element container.
This PR initializes the DatePicker with the container for the floating div, now it's being added to the body (as the DateTimePicker does by default) to avoid overflow issues.
@jsoltes can you review?

JBPM-6220: Unable to complete your request after setting the Show Time property to false.

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-api/src/main/java/org/kie/workbench/common/forms/service/shared/FieldManager.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/AbstractFieldManager.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/pom.xml
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorHelper.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/FieldPropertiesRenderer.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/FieldPropertiesRendererHelper.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/DataBindingEditor.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/dynamic/DynamicDataBinderEditor.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/statik/StaticDataBinderEditor.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/rendering/EditorFieldLayoutComponent.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorHelperTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/DataBinderEditorTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/dynamic/DynamicDataBinderEditorTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/properties/binding/statik/StaticDataBinderEditorTest.java

Copy of https://github.com/kiegroup/kie-wb-common/pull/1117
Changed the way compatible properties are calculated to use the providers supported types.
@jsoltes can you review?

[7.3.x] JBPM-6324: Inconsistency between field types and field bindings with slider.

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetViewImpl.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetViewImpl.html
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.html

Reverting commit 21fa7410ece16686383f150f5b17002611f08196 due to missing toolbar.
It is being fixed on the PR https://github.com/kiegroup/kie-wb-common/pull/1105
@manstis 
@romartin

JBPM-6052  Reverting the merge commit 21fa7410ece16686383f150f5b17002611f08196

---

kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/main/java/org/kie/workbench/common/forms/jbpm/client/document/DocumentFieldRendererViewImpl.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/test/java/org/kie/workbench/common/forms/jbpm/client/document/DocumentFieldRendererViewImplTest.java

changed the reference to the document upload file servlet, making it relative removing the slash

[7.3.x] JBPM-6389 : Upload file in task form is not working for eap7

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/LibraryService.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/LibraryServiceImplTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/NewProjectScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/NewProjectScreenTest.java

JBPM-6354: Cryptic error message when trying to create a project with name that already exists in Maven repo
GUVNOR-3457: [Library] edge case when filtering projects by name leads to javascript error
GUVNOR-3176: [Library] Filtering assets and projects is not unified

[7.3.x] JBPM-6354, GUVNOR-3457, GUVNOR-3176

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/SafeDeleteNodeProcessor.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/TestingGraphInstanceBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/SafeDeleteNodeProcessorTest.java

Hi @hasys ,  @manstis , @romartin ,
Fixed a bug that did not allow to remove a container with a non-empty container inside.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-6104).
Could you please review this PR?
Thanks.

JBPM-6104: Stunner - not possible to remove container with not empty container inside

---

kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/PackageDataModelOracleCompletionsTest.java

https://issues.jboss.org/browse/GUVNOR-3479
Looks like there were tests after all.

GUVNOR-3479 : [GSS-RFE] Add support for missing keywords like "not matches" condition in Guided Rule

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/README.md
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Hey @manstis @mbarkley @psiroky 
Here is the fix for using the version `10.1.0.Final` of the errai's embedded wildfly server.
Depends on this one https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/550 !!
Thanks!

JBPM-6426: Use of Errai's embedded Wildfly server 10.1.0.Final

---

kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/PackageDataModelOracleCompletionsTest.java

https://issues.jboss.org/browse/GUVNOR-3479
(cherry picked from commit 916b4ab3853b0822922522336dd2645b9f8bb78f)
https://github.com/kiegroup/drools/pull/1480
https://github.com/kiegroup/kie-wb-common/pull/1173
https://github.com/kiegroup/drools-wb/pull/626

[7.3.x] GUVNOR-3479 : [GSS-RFE] Add support for missing keywords like "not matches" condition in Guided Rule

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProvider.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProviderImpl.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorHelper.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProviderImplTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/test/TestFormEditorHelper.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/pom.xml
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/main/java/org/kie/workbench/common/forms/jbpm/client/JBPMEditorFieldTypeProviderImpl.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/test/java/org/kie/workbench/common/forms/jbpm/client/JBPMEditorFieldTypeProviderImplTest.java

Copy of https://github.com/kiegroup/kie-wb-common/pull/1177
This PR fixes a smaill issue introduced by previous commit.

[7.3.x] JBPM-5429: AssigneeEditor should not appear in the form-modeler.

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImpl.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImplTest.java

[7.3.x] Remove redundant else branch from getFQCNByFactName method (#1175)

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/index/bounds/CanvasBoundsIndexerImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/index/bounds/CanvasBoundsIndexerImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/index/bounds/BoundsIndexer.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/builder/impl/AbstractElementBuilderControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeAction.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeActionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/index/bounds/GraphBoundsIndexerImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/processing/indexing/bounds/GraphBoundsIndexerImplTest.java

Hi @hasys , @manstis , @romartin ,
Now It's possible to add  new nodes from toolbox without containment rule violations. 
The final position for the new target node is dinamically evaluated.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-6164).
Could you please review this PR?
Thanks.

JBPM-6164: Stunner - Adding new nodes from toolbox can fail with containment rule violations

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProvider.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProviderImpl.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorHelper.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/EditorFieldTypesProviderImplTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/test/TestFormEditorHelper.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/pom.xml
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/main/java/org/kie/workbench/common/forms/jbpm/client/JBPMEditorFieldTypeProviderImpl.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-client/src/test/java/org/kie/workbench/common/forms/jbpm/client/JBPMEditorFieldTypeProviderImplTest.java

This PR fixes a smaill issue introduced by previous commit.

[8.0.x] JBPM-5429: AssigneeEditor should not appear in the form-modeler.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/BaseNavigateCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/components/palette/widget/DMNPaletteWidgetViewImpl.css
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/components/palette/widget/DMNPaletteWidgetViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetViewImpl.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetViewImpl.html
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.html
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/impl/ToolbarViewImpl.ui.xml
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/SessionDiagramEditorScreen.java

Fix for the reopened issue JBPM-6052 according to the comment of @manstis regarding the commit [1]. 
Now the palette is fixed and the toolbar is not missed, tested on the project, standalone and kie-drools-wb. Some videos were attached to the JIRA [2]. If it is ok after the merge it is necessary the port back to the 7.3.x.
@ibek @hasys can you please help to validate.
Thanks.
**[1]** https://github.com/kiegroup/kie-wb-common/commit/9fe2a86f4609968fd030ae8ff5be308b92d3470a
**[2]** https://issues.jboss.org/browse/JBPM-6052

JBPM-6052 Stunner: fixing toolbar panel that was missing with fixed palette

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/menu/DefaultWorkbenchFeaturesMenusHelper.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/menu/DefaultWorkbenchFeaturesMenusHelperTest.java

Cherry-picked from [master](https://github.com/kiegroup/kie-wb-common/pull/1174)

[7.3.x] AF-615: Items in the logout menu duplicated every time navigation tree is changed

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/Transform.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/TransformImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/event/BuildCanvasShapeEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/event/CanvasShapeDragStartEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/event/CanvasShapeDragUpdateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/event/BuildCanvasShapeEventTest.java

This is a partial fix for JBPM-6045: It now places new nodes correctly after a pan. It it is offset a variable amount to the left and up based on scale; if we could discover the exact amount this can be accounted for in the current implementation. The rest of the issues in JBPM-6045 remain unresolved. Does anyone know what classes handles Lane containment highlighted and the like so I can fix them?

[JBPM-6045] Use correct Canvas position after scaling/panning

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/legacy/Bpmn2JsonUnmarshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/legacy/Bpmn2JsonUnmarshallerTest.java

To do this I need to URL-encode the name when creating a new resource, and URL-decode the name when displaying the resource name. What are all the widgets that read the title names? I did the main ones, but there are a few I missed (ex: Case Management).

JBPM-6049: Allow user to put spaces in the name of processes

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresTextDecorator.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/WiresConnectorViewTest.java

See https://issues.jboss.org/browse/GUVNOR-3394
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1074 for 7.3.x.
(cherry picked from commit ed62be08a4488b0a4f469b35918ce6e0292d35aa)
Please note 7.3.x does not have the DMN Editor and hence the changes here are only for Stunner.

[7.3.x] GUVNOR-3394: [DMN Editor] Literal Expression: Line breaks for multiple line expressions

---

kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/main/java/org/kie/workbench/common/screens/explorer/backend/server/ProjectExplorerContentResolver.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/HelperWrapper.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/ProjectExplorerContentResolverTest.java

Cherry-picked from [master](https://github.com/kiegroup/kie-wb-common/pull/1181).

[7.3.x] AF-619: [Library] Null exception appears in Project Explorer when switching views

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/EditorIds.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/authz/PermissionTreeSetup.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.properties
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/authz/PermissionTreeSetupTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/handlers/BPMNDiagramNewResourceHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/handlers/BPMNDiagramNewResourceHandlerTest.java

See https://issues.jboss.org/browse/GUVNOR-3524
This PR sets up the ```PermissionTreeSetup``` to include the editors we need to restrict access to; and adjusts Stunner's ```NewResourceHandler``` to prevent creation of new assets if permission is denied. Plus a bunch of tests.

GUVNOR-3524: Do not expose unsupported features by UI (e.g. scorecards, decision trees)

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/components/palette/factory/DMNPaletteDefinitionFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/components/palette/factory/DMNPaletteDefinitionFactoryTest.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/DynamicFormRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/DefaultDefSetPaletteDefinitionFactoryImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/SelectionControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/palette/factory/AbstractPaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/palette/factory/BindableDefSetPaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/palette/factory/BindablePaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-basicset/kie-wb-common-stunner-basicset-client/src/main/java/org/kie/workbench/common/stunner/basicset/client/components/palette/factory/BasicSetPaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/palette/factory/BPMNPaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/palette/CaseManagementPaletteDefinitionFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/palette/CaseManagementDefinitionSetPaletteBuilderImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/palette/CaseManagementPaletteDefinitionFactoryTest.java

Now if more than one diagram is opened the palette is displayed on all of them.
The problem was basically the `AbstractPaletteDefinitionFactory.newPalette` was returning always the same instance instead of creating a new instance on each method call, in this way there was only one instance of the palette. Now, every method call `AbstractPaletteDefinitionFactory.newPalette` a new instance is returned.
This issue was affecting **BPMN** and **DMN**.
**Important**: there was a bug inserted on the master branch on this line https://github.com/kiegroup/kie-wb-common/blob/2b2ff376755db5d918fbc7e032c160e5be91f34d/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/F …

JBPM-6419 - When opening more than one Diagram the Palette is not rendered on all of them

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/error/DefaultWorkbenchErrorCallback.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.properties
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/error/DefaultWorkbenchErrorCallbackTest.java

The previous modal showed just a cryptic error saying JSON could not
parsed, which was quite confusing.
The modal shows a `Yes`, `No` and `Cancel` options (with `No` and `Cancel` doing the same -- nothing, just closing the modal). Does that make sense? Is there a use case where user would not want to login again directly and remain on the page (even though it can be used anymore)?
@manstis or @porcelli could you please take a look?

[UF-510] detect session timeout and show nicer modal

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspective.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspectiveTest.java

RHBPMS-4895: [Library] Javascript error when canceling navigation to Library perspective
Cherry-picked from [master](https://github.com/kiegroup/kie-wb-common/pull/1245).

[7.4.x] GUVNOR-3531: Workbench navigation - An error popup appears, if unsaved data, when navigating to the Projects screen

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspective.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/perspective/LibraryPerspectiveTest.java

RHBPMS-4895: [Library] Javascript error when canceling navigation to Library perspective

GUVNOR-3531: Workbench navigation - An error popup appears, if unsaved data, when navigating to the Projects screen

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Adding dependency to fix building GWT on Stunner and DMN webapp showcases.
Basically it was an inection of `MVELEvaluator` instance that was missing on the CDI.
Drools implements it on `SafeMVELEvaluator` and it is instantiated on the CDI on https://github.com/kiegroup/drools/blob/master/drools-cdi/src/main/java/org/drools/cdi/CDIProducer.java.
Thanks @manstis to give me the clue.
Can you check if is it alright, I've tested all webapps and they are running fine now.
@romartin 
@wmedvede 
@alepintus

JBPM-6503 - Missing Dependency when building webapp Showcases

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/LRUPomModelCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/LRUPomModelCacheTest.java

See https://issues.jboss.org/browse/AF-889
This is on the 6.4.7 JIRA list.

[6.5.x] AF-889: [GSS] (6.4.z) 'Reimport' doesn't invalidate LRUPomModelCache

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/LRUPomModelCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/core/LRUPomModelCacheTest.java

See https://issues.jboss.org/browse/AF-889

AF-889: 'Reimport' doesn't invalidate LRUPomModelCache

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenter.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/editor/ProjectScreenPresenterTest.java

See https://issues.jboss.org/browse/RHBRMS-3022
Before:
After:
---
Menus from other editors were interfering with permissions to enable/disable delete (and other buttons) in the Project Editor.
---
- https://github.com/AppFormer/uberfire/pull/903
- https://github.com/kiegroup/kie-wb-common/pull/1284

RHBRMS-3022: Cannot disable "Delete" button for Analyst role in business central

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/preferences/DroolsSystemPropertiesInitializer.java

Inserting the import to `org.drools.core.util.KeyStoreConstants` the class the constants were moved to.
Can you review this, it is a fix to the master branch that is broken.
@romartin 
@manstis

JBPM-6617 Fix for missing drools constants on keyStoreHelper

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorPresenter.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/test/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorPresenterTest.java

@jsoltes Could you please take a look?
This PR is a part of an ensemble, please merge with:
https://github.com/AppFormer/uberfire/pull/907
https://github.com/kiegroup/kie-wb-common/pull/1287

JBPM-6589: Field Settings lost after moving on layout

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/pom.xml
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/pom.xml
pom.xml

@psiroky could you please check and merge? Now that maven 3.5.2 highlights those warnings with colors, it's kinda harder to ignore :-)
Fixing the following warnings. Those dependencies are already declared in those poms, just removing all the duplicates found by 
`mvn dependency:analyze-duplicate`
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie.workbench.widgets:kie-wb-common-widgets:pom:7.5.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie.soup:kie-soup-bom:pom -> duplicate declaration of version ${version.org.kie} @ org.kie.workbench:kie-wb-common:[unknown-version], /home/hrk/Devel/github.com/jhrcek/kie-wb-common/pom.xml, line 83, column 19
[WARNING] …
```

Remove duplicated dependencies

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/glyph/ShapeGlyphDragHandlerImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/builder/ObserverBuilderControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/components/glyph/ShapeGlyphDragHandlerImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/exceptions/ElementOutOfBoundsException.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/builder/impl/AbstractElementBuilderControl.java

- Now when clicking on a palette item it starts the drag and when clicking again it drops, it works for the default item on the palette and when selecting a sub-item.
- Now if an item is dropped outside the canvas area, the item is not placed on canvas and no error message will appear to the user, only the error log about trying to drop outside canvas area.
@romartin 
@hasys

JBPM-6513 Stunner - Dropping / clicking palette items displays an error message

---

kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java

See https://issues.jboss.org/browse/GUVNOR-3486
(Actually see [here](https://issues.jboss.org/browse/RHBRMS-2955?focusedCommentId=13504046&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13504046)).
I also noticed that the "Columns tab" was being disabled when it should have been enabled; and enabled when it should have been disabled.. so I fixed and refactored a bit to make things clearer in the future.

GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/icons/event/event-intermediate.svg
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/icons/event/event-start.svg

Hey @alepintus @wmedvede @hasys 
Actually the icons for start and intermediate events are not being displayed, neither in the morph menu on the canvas shapes neither when dragging those icons from the palette. Here is the fix for it, it was due a few invalid declarations in the SVG files.
Thanks!

Stunner - Fixing start and intermediate SVG icons declaration

---

kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieMultipleDocumentEditor.java

See https://issues.jboss.org/browse/GUVNOR-3486
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1316 for 7.5.x
(cherry picked from commit 2a38bfed0f546b386ee3a35b894c9c320ad604b3)

[7.5.x] GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/util/CommandUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/MoveRowsCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/util/CommandUtilsTest.java

Fixes following https://github.com/kiegroup/kie-wb-common/pull/1339

DROOLS-1946: Change implementation of moving rows. Fixes.

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/event/selection/CanvasSelectionEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/command/CanvasCommandFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/Counter.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/test/java/org/kie/workbench/common/stunner/core/util/CounterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/CloneConnectorCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/CloneNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/DefaultCanvasCommandFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/clipboard/LocalClipboardControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CopySelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/PasteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/command/CloneConnectorCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CopySelectionSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/PasteSelectionSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/command/impl/AbstractCompositeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/CloneConnectorCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/TestingGraphMockHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/command/CaseManagementCanvasCommandFactory.java

Now it is possible to copy/cut and paste multiple selection of elements on diagrams.
The position of pasting was changed to avoid overlapping elements, now it is considered the max Y position considering all the elements on the selection.
@romartin @hasys  can you please help to review the PR.
Thanks.

JBPM-6705 [Stunner] Multi-selection copy/cut and paste

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/cache/LRUDataModelOracleCache.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/cache/LRUProjectDataModelOracleCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/Builder.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/LRUBuilderCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/LRUPomModelCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/LRUProjectDependenciesClassLoaderCache.java

See https://issues.jboss.org/browse/DROOLS-2230
QE had dead-locks in failing Selenium tests. 
The changes in this PR resolve the issues as verified by @tomasdavidorg 
```Builder``` had the most extensive changes; whereby synchronised blocks were changed to safe-guard the smallest area possible. ```LRUCache``` implementations synchronised removed from public methods as the underlying ```Collection``` used by the cache is thread-safe in itself.

DROOLS-2230: Deadlock related to org.kie.workbench.common.services.backend.builder.core.LRUProjectDependenciesClassLoaderCache

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/resources/org/kie/workbench/common/screens/datamodeller/client/resources/i18n/Constants.properties

See https://issues.jboss.org/browse/DROOLS-2250
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1370 for 7.5.x
(cherry picked from commit 979908f61defd37e288582ebdb7f563e00756566)

[7.5.x] DROOLS-2250: Align Engine hints in Decision Table column wizard with BAPL-708

---

kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/general/BaseNavigateCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/panel/DMNGridPanel.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/BaseNavigationCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/NavigateToDRGEditorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/NavigateToExpressionEditorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/panel/DMNGridPanelTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/view/BootstrapNavigatorView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/navigator/view/BootstrapNavigatorView.ui.xml
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/SessionPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionContainer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.html
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.less
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/views/session/ScreenPanelViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterViewTest.java

See https://issues.jboss.org/browse/DROOLS-2155
@romartin This introduces some small changes to Stunner. A continuous "inheritance path" is required from the (Lienzo) ```Layer``` used to hold the DMN grids to the outer most Stunner ```SessionPresenterView``` that supports ```RequiresResize``` so the DMN grid layer can resize and adjust its virtual scrollbars. Therefore I've had to make a few ```FlowPanel``` into ```ResizableFlowPanel``` in Stunner.
I also added the ability for the ```SessionPresenterView``` to have set whether it's main ```DIV``` controls scrollbars on the content (as you have now, a large (Lienzo) ```Panel``` in a small ```DIV``` with ```overflow: auto``` or whether the content provides its own scrollbars (as is the case with the DMN grid layer).
I've tested with DMN …

DROOLS-2155: Table editor should use full canvas area available

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/general/BaseNavigateCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/components/palette/widget/DMNPaletteWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/components/palette/widget/DMNPaletteWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/palette/PaletteWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorPresenterTest.java

See https://issues.jboss.org/browse/DROOLS-2256
@tiagobento the changes you made for https://issues.jboss.org/browse/GUVNOR-3357 forces the Palette to show (for a ```@DiagramEditor``` widget) when a workbench Panel is maximised or minimised. This breaks the DMN Editor that has two modes of operation: (1) The normal "Stunner" graph grid display, (2) A sub-view when the User chooses to edit the detail of a node (the sub-view is still part of the ```@DiagramEditor``` "main" view). In the second scenario we hide the Palette as it is not needed; however maximising/minimising a Panel caused the Palette to reappear.
The change in this PR allows me to prevent this undesirable behaviour by only showing the Palette if it has not been hidden "on purpose" by the User editing the node detail.

DROOLS-2256: [DMN Designer] Scrollbars in full screen mode

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ExpressionPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/resources/wrong_context.dmn

SPECIAL CASE: to represent a partially edited DMN file.
consider a LiteralExpression with null text as missing expression
altogether.
/cc @jomarko

DROOLS-2217 [DMN Editor] Allow DMN persistence for an incomplete, still being authored, DMN model

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/background/BgColour.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/background/BorderColour.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/font/FontColour.java

See https://issues.jboss.org/browse/DROOLS-2260
This PR is probably impacted by #1362 however I'm happy to keep this PR pending (merge of #1362) and fix accordingly (the mentioned PR removes ```defaultValue``` but I'll move to static literals instead).

DROOLS-2260: [DMN Designer] Background Color change throws an Exception

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java

See https://issues.jboss.org/browse/DROOLS-2270
@jomarko Due to [this](https://issues.jboss.org/browse/DROOLS-1937) the name of the node shown in the "back link" in the UI is always "My name" however you can see from the Unit Test that it does use the value extracted from the ```HasName``` instance. I also stepped through the code in the browser and the ```HasName``` passed is identical to the node selected in the graph.

DROOLS-2270: [DMN Editor] Replace 'Return to DRG' button with Link

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/FormEditorPresenter.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/pom.xml
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/PersistenceDescriptorEditorPresenter.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-client/src/main/java/org/kie/workbench/common/screens/datasource/management/client/editor/datasource/DataSourceDefEditor.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-client/src/main/java/org/kie/workbench/common/screens/datasource/management/client/editor/driver/DriverDefEditor.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-api/pom.xml
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-api/src/main/java/org/kie/workbench/common/screens/defaulteditor/service/DefaultEditorService.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-backend/pom.xml
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-backend/src/main/java/org/kie/workbench/common/screens/defaulteditor/backend/server/DefaultEditorServiceImpl.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/GuvnorDefaultEditorPresenter.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/KieTextEditorPresenter.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/test/java/org/kie/workbench/common/screens/defaulteditor/client/editor/KieTextEditorPresenterTest.java
kie-wb-common-screens/kie-wb-common-java-editor/kie-wb-common-java-editor-client/src/main/java/org/kie/workbench/common/screens/javaeditor/client/editor/JavaEditorPresenter.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-api/pom.xml
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-api/src/main/java/org/kie/workbench/common/screens/projecteditor/service/PomEditorService.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/pom.xml
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/main/java/org/kie/workbench/common/screens/projecteditor/backend/server/PomEditorServiceImpl.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/defaulteditor/backend/server/DefaultEditorServiceImplTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/PomEditorServiceImplTest.java
kie-wb-common-screens/kie-wb-common-project-imports-editor/kie-wb-common-project-imports-editor-client/src/main/java/org/kie/workbench/common/screens/projectimportsscreen/client/forms/ProjectImportsScreenPresenter.java
kie-wb-common-screens/kie-wb-common-project-imports-editor/kie-wb-common-project-imports-editor-client/src/test/java/org/kie/workbench/common/screens/projectimportsscreen/client/forms/ProjectImportsScreenPresenterTest.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/DataModelServiceConstructorTest.java
kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/project/ProjectImportsService.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/project/ProjectImportsServiceImpl.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/project/ProjectImportsServiceImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/test/java/org/kie/workbench/common/widgets/metadata/client/KieEditorTest.java

See:
- https://issues.jboss.org/browse/RHBA-148
- https://issues.jboss.org/browse/AF-819
---
Demo:
---
Important topics:
I) I'm keeping the editors, that have their own implementation of the save-and-rename operation, intact;
II) I couldn't apply the generic approach on `jbpm-designer`, due to the save operation that is coupled to native JS code. Thus, I needed to implement a custom solution there;
III) The "save commit" and the "rename commit" are not being squashed. I don't think that it's a problem since we're showing explicitly to the user that two operations are being executed (but, maybe I'm missing something, wdyt @manstis?).
---
- https://github.com/kiegroup/appformer/pull/170
- https://github.com/kiegroup/kie-wb-common/pull/1414
- …

AF-819: Renaming assets discards changes

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/resources/org/kie/workbench/common/stunner/standalone/StunnerStandaloneShowcaseWithSourceMap.gwt.xml

Hi @romartin, @tiagodolphine, @Josephblt, @wmedvede,  @alepintus, @evacchi, @manstis 
I added profile to compile Stunner showcase project with sources in WAR file for easier debugging of Stunner in Chrome browser.
How to use it go to:
`kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone`
execute
`mvn clean package -Psourcemaps`
Deploy `target/kie-wb-common-stunner-showcase-standalone.war` to wildfly and you will have war file with source code to debug Stunner showcase in Chrome browser.
Advantages:
* It is more stable than gwt:run
* It is faster than gwt:run
* Not so RAM consuming which can be critical for laptop with 8/16 GB owners
Disadvantages:
* No hot fix recompilation
* Manual deploy of result war file
P.S. inspired by …

Enable sourcemaps profile for more stable and fast debugging

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/Builder.java

This change is needed due to internal api changes introduced by work on DROOLS-2284
@tarilabs 
@baldimir 
@manstis 
Guys, please have a look.

DROOLS-2328: Replace the internal api call with public api call

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/handler/NewFormDefinitionlHandler.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/NewFileUploader.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/resources/i18n/GuvnorDefaultEditorConstants.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/resources/org/kie/workbench/common/screens/defaulteditor/client/editor/resources/i18n/GuvnorDefaultEditorConstants.properties
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/NewResourceViewImpl.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/handlers/NewResourceViewTest.java

This is part of an ensemble:
- #1278 
- kiegroup/drools-wb#815
- kiegroup/jbpm-designer#748

DROOLS-2109: Show Extension labels in the new resource dialogue

---

kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/ExplorerMenuViewImpl.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/resources/i18n/ProjectExplorerConstants.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/resources/org/kie/workbench/common/screens/explorer/client/resources/i18n/ProjectExplorerConstants.properties

AF-1016: [Project Oriented] Project Explorer "Download Project" no longer makes sense. "Download Project" should be what download repository was before and download repository should not be listed.
AF-1004: [Project Oriented] Downloaded repository is flattened

Project explorer download zip fix

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ExamplesServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/resources/org/kie/workbench/common/screens/library/client/resources/i18n/Library.properties
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/ProjectScreenTestBase.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreenTest.java

Also fixes: 
* AF-1020: [Project Oriented] When you copy a project (in Settings > Copy) the copy modal is not closed.
* AF-1021: [Project Oriented] When you copy a project (Settings -> Copy) there is 'New Asset Name' in the modal instead of 'New Project Name'

Restoring duplicate and reimport functions to the project

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/backend/DefaultLuceneConfigProducer.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/ProjectAssetListUpdated.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/Remote.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/Routed.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryAssetUpdateNotifier.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryIndexer.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/AssetsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/LibraryPlacesTest.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/main/java/org/kie/workbench/screens/workbench/backend/impl/DefaultLuceneConfigProducer.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/backend/DefaultLuceneConfigProducer.java

A fix for AF-985 and a forward port of RHDM-382 are bundled together in this PR as they both affect related code.
The AF-985 fix will cause the project screen to reload whenever a place request to it is made, even if it is already in focus. This allows clicking on the breadcrumb to refresh.

AF-985: [Project Oriented] Project doesn't show all imported assets.

---

kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/NewFileUploader.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/test/java/org/kie/workbench/common/screens/defaulteditor/client/editor/NewFileUploaderTest.java

The import asset was already working (on master) when the project name contained spaces. This fixes the NewResourceSuccessEvent path, which was causing a wrong breadcrumb to be shown after the import process was completed.

AF-1043: [Project Oriented] Error on file upload in a project with spaces

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/AssetQueryService.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/assets/AssetQueryServiceTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreenTest.java

Note that because of other changes in master, the loading popup prevents you from easily reproducing the original issue.
The easiest way I found to test this is open the chrome inspector while the asset list is loading and hide the overlay. Then you can rapidly click the project breadcrumb.

AF-985+: Fix duplicate loading of assets when page is updated rapidly.

---

kie-wb-common-cli/kie-wb-common-project-migration/README.md
kie-wb-common-cli/kie-wb-common-project-migration/pom.xml
kie-wb-common-cli/kie-wb-common-project-migration/src/assembly/descriptor.xml
kie-wb-common-cli/kie-wb-common-project-migration/src/main/sh/migration-tool.bat
kie-wb-common-cli/kie-wb-common-project-migration/src/main/sh/migration-tool.sh

This PR enhances linux launcher to get proper java and removes the setting global CLASSPATH with all jars in lib folder.
Also I added Windows launcher and changed distribution zip assembly to be dist instead of only Linux.
Fixed platform dependent assembly descriptor to use absolute paths for bin and lib.

RHBA-514: migration tool window launcher

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/FunctionDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/QName.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/property/dmn/QNameTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/QNamePropertyConverter.java

See https://issues.jboss.org/browse/DROOLS-2389
@jomarko I've made the ```QName``` in the "Properties panel" read-only for now; since it is the return data-type of the ```Decision```/```BusinessKnowledgeModel``` node. Data-types are yet to be implemented; and how we want to interact with it at the graph level is undefined (e.g. do we want it as a "Properties panel" property; or do we want another icon on the node itself to define it's data-type.
@tarilabs Looks OK now?

DROOLS-2389: [DMN Editor] Add proper support for 3-part QName

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/src/main/resources/org/kie/workbench/common/stunner/project/StunnerProjectShowcase.gwt.xml

https://github.com/kiegroup/appformer/pull/247
https://github.com/kiegroup/kie-wb-common/pull/1511
https://github.com/kiegroup/kie-wb-distributions/pull/709
https://github.com/kiegroup/drools-wb/pull/832

[AF-1074]: Removed unused OrganizationalUnitManager View that made connected clients crash.

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Hey @pefernan @hasys @jomarko @manstis 
I was not able to run the showcases for BPMN or DMN, I guess that's something related to this https://github.com/kiegroup/kie-wb-common/pull/1492
Anyway no worries, feel free to merge it if it makes sense for you. At least it makes my webapps startt working again. This should not affect the downstream repos.
Thanks!

BAPL-764: [Stunner] Added missing dependency to forms-backend-services in the showcase modules

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/generalsettings/GeneralSettingsPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/generalsettings/GeneralSettingsView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/generalsettings/GeneralSettingsView.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-api/src/main/java/org/kie/workbench/common/screens/projecteditor/model/ProjectScreenModel.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/main/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenModelLoader.java

this initial implementation aims to be a quick hack, enabling this long time request available for upcoming release.
It's expected to improve the UI visulation, bringing something like GitHub has.

Bring back Git URL external access of the current project

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionUIModelMapper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionUIModelMapper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/layer/DMNGridLayer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionUIModelMapperTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionUIModelMapperTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGridGeneralTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/layer/DMNGridLayerTest.java

See https://issues.jboss.org/browse/DROOLS-2410
The problem was that grids "off screen" are no longer registered and hence when they moved "off screen" a "selected" grid could not be found and the ghost not rendered. 
I also fixed a problem I found when if you select a cell in a grid scroll it "off screen" and select a different cell in a different nested grid; then scroll back the original selection remained. This too was caused by "off screen" grids no longer being registered. I now walk the data models and deselect all grids whether "on screen" or "off screen". This is quite a (relatively) slow operation (and was removed elsewhere for performance reasons) but is OK to use when selecting a grid as it's driven by the User's interactions and performance is not critical.
Part of an …

DROOLS-2410: [DMN Designer] Active entries not highlighted correctly when scrolling

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/BaseEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/supplementary/FunctionSupplementaryGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/supplementary/java/JavaFunctionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/supplementary/pmml/PMMLFunctionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/model/GridDataCache.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/BaseEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ExpressionEditorColumnTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGridCacheTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGridGeneralTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGridRenderingTest.java

See https://issues.jboss.org/browse/DROOLS-2392
This PR adds support for caching the UI model used for "top level" Expressions.
The problem was that each time the User navigates back to the "graph" view and then again back to (the same) "grid" the UI model was recreated and commands in the undo/redo queue remained associated with the old UI model. With the cache "top level" Expressions, with a UUID (from Stunner), cache and re-use the UI model.

DROOLS-2392: [DMN Designer] Undo and Redo does not update user interface

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/BuiltinAggregatorUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyEditorImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/BuiltinAggregatorUtilsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyEditorImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyEditorViewImplTest.java

See https://issues.jboss.org/browse/DROOLS-2420
Basically, when the ```HitPolicy``` is ```COLLECT``` you don't need to specify a ```BuiltinAggregator```.

DROOLS-2420: [DMN Designer] Hit Policy Collect does not need an Aggregation function

---

kie-wb-common-stunner/kie-wb-common-stunner-backend/src/main/java/org/kie/workbench/common/stunner/backend/service/DiagramLookupServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-backend/src/test/java/org/kie/workbench/common/stunner/backend/service/DiagramLookupServiceImplTest.java

Hey @manstis  @jomarko 
Fixed the issue on the diagram's name matching condition. 
See [DROOLS-2436](https://issues.jboss.org/browse/DROOLS-2436)
Sorry it was my fault, added a small test at least for this. 
@manstis Thanks for pointing out the root issue, this way things are easier... :+1:  
Thanks!

DROOLS-2436: Fix wrong diagram's name match condition.

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ResizeControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/CanvasViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/UpdateElementPositionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/GraphUtilsTest.java

Hey @jomarko @tiagodolphine @manstis 
Sorry after merging a few PRs together the full build got broken due to some `unused imports` check failed. Here is the fix. 
Thanks!

BAQE-400: Remove unused imports (fix)

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.less
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/resources/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterViewTest.java

See https://issues.jboss.org/browse/JBPM-6822
Before:
After:
---
@manstis I considered your [comment](https://issues.jboss.org/browse/JBPM-6822?focusedCommentId=13558096&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13558096), and I checked how easy would be to re-use the existing `NotificationEvent`. This seemed so easy that I quickly tried it, but some scenarios like [this one](https://www.dropbox.com/s/9vrbkvii2525cej/b1.gif?dl=0) became a little buggy ([see](https://www.dropbox.com/s/kj9itf4yau695ym/b2.gif?dl=0) the warning notification). Thus I preferred to follow @romartin's suggestion and fix only the HTML characters.

JBPM-6822: Stunner - make notifications more user friendly

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/PomEditor.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/resources/org/kie/workbench/common/screens/library/client/resources/i18n/Library.properties
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/PomEditorTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-api/src/main/java/org/kie/workbench/common/screens/projecteditor/model/InvalidPomException.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/main/java/org/kie/workbench/common/screens/projecteditor/backend/server/PomEditorServiceImpl.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/PomEditorServiceImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/callbacks/CommandWithThrowableDrivenErrorCallback.java

This PR brings back the `PomEditor` class that was removed along with the implementation of the new Settings screen. More than that, this editor now contains a save validation and displays a friendly message when errors occur.

AF-1151: Project's pom.xml file is not validated before saving

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/MorphNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/MorphNodeCommandTest.java

See https://issues.jboss.org/browse/RHPAM-517
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1645 for 7.7.x
(cherry picked from commit 6cd92c1772186793655bc115fb35a69a85bb83cb)

[7.7.x] RHPAM-517 (JBPM-7012): Stunner - After morph it is not possible to put node inside of subprocess

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/AbstractToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ClearStatesToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ClearToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/CopyToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/CutToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/DeleteSelectionToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToBpmnToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToJpgToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToPdfToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToSvgToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/PasteToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/RedoToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/SwitchGridToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/UndoToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ValidateToolbarCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/VisitGraphToolbarCommandTest.java

cherry-picks #1587 
Add unit test for each toolbar command and
verify instance of these commands are correctly created.

[7.7.x] RHPAM-827: Extend test-coverage of toolbar commands

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/DMNCanvasFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/ViewEventHandlerManager.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresShapeViewExt.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/ViewEventHandlerManagerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/AbstractTextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/AbstractTextEditorBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorBox.css
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorBox.html
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/DefaultCanvasFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/CanvasInPlaceTextEditorControlMultiLine.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/CanvasInPlaceTextEditorControlSingleLine.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/MultiLineTextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/SingleLineTextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/TextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/general/BPMNGeneralSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/general/TaskGeneralSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/canvas/BPMNCanvasFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/canvas/CaseManagementCanvasFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/canvas/CaseManagementCanvasFactoryTest.java

Hi  @romartin @hasys ,
inline name edition feature fixed and text editor box layout changed.
For more information [see this ticket](https://issues.jboss.org/browse/JBPM-6777).
Thanks!

JBPM-6777: Stunner - Cannot edit element names inline RHBA-444

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/shape/view/handlers/DMNViewHandlersTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/WiresContainerShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/DecoratedShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresShapeViewExt.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/AbstractHasRadiusView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/AbstractHasSizeView.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasRadius.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasSize.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/handler/SizeHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/shape/ShapeViewExtStub.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/shape/view/SizeHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/wires/AbstractCaseManagementShape.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/wires/MockCaseManagementShape.java

https://issues.jboss.org/browse/JBPM-7129
AbstractMultiPathPartShapes now support adding min or max Constraints.
You can set minWidth, max Width, minHeight, maxHeight independent from
each other. For example you can set the minWidth for a shape and leave
all other constraints blank. Blank constraints will be ignored.
All this PR's are related to this task:
lienzo-core:
https://github.com/kiegroup/lienzo-core/pull/18
lienzo-tests:
https://github.com/kiegroup/lienzo-tests/pull/14
kie-wb-common
This PR

JBPM-7129: Stunner - Allow optional size constraints for shapes

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/menu/MenuUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/menu/MenuUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorMenuItemsBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorMenuItemsBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorTest.java

See https://issues.jboss.org/browse/JBPM-7031
@romartin I tried endlessly to only have one "open" method and cast the ```SessionPresenter``` but could not find a way to do it; so had to (unhappily) settle for what you see in the PR (two ```SessionPresenter```'s, one for "full" and another for "read-only").... if you can explain how to cast I'll more than happily update to use a single ```openSession(..)``` method!

JBPM-7031: Stunner - Disable doing operation in view mode

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/shape/view/handlers/DMNViewHandlersTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/WiresContainerShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/DecoratedShapeView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresShapeViewExt.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/AbstractHasRadiusView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-shapes/kie-wb-common-stunner-shapes-client/src/main/java/org/kie/workbench/common/stunner/shapes/client/view/AbstractHasSizeView.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasRadius.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasSize.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/handler/SizeHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/shape/ShapeViewExtStub.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/shape/view/SizeHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/wires/AbstractCaseManagementShape.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/test/java/org/kie/workbench/common/stunner/cm/client/wires/MockCaseManagementShape.java

Issue:
[RHPAM-845](https://issues.jboss.org/browse/RHPAM-845)
[JBPM-7129](https://issues.jboss.org/browse/JBPM-7129) 
Cherry-pick:
commit fbd29158037907e593a4656e0686b26941570e81
**This PR depends on kiegroup/lienzo-core.**
**7.7.x Branch PR's:**
[_this one_](https://github.com/kiegroup/kie-wb-common/pull/1677)
kiegroup/lienzo-core:
https://github.com/kiegroup/lienzo-core/pull/20
kiegroup/lienzo-tests
https://github.com/kiegroup/lienzo-tests/pull/16
**Master PR's:**
_kiegroup/kie-wb-common_
https://github.com/kiegroup/kie-wb-common/pull/1641
_kiegroup/lienzo-core:_
https://github.com/kiegroup/lienzo-core/pull/18
_kiegroup/lienzo-tests_
https://github.com/kiegroup/lienzo-tests/pull/14
@romartin

[7.7.x] RHPAM-845 (JBPM-7129) - Stunner - Allow optional size constraints for shapes

---

kie-wb-common-forms/kie-wb-common-forms-integration-tests/src/test/java/org/kie/workbench/common/forms/integration/tests/formgeneration/FormGenerationIntegrationTest.java

@jsoltes @pefernan FYI [JBPM-7170](https://issues.jboss.org/browse/JBPM-7170)

JBPM-7170: Ignore randomly failing FormGenerationIntegrationTest

---

kie-wb-common-forms/kie-wb-common-forms-integration-tests/src/test/java/org/kie/workbench/common/forms/integration/tests/formgeneration/FormGenerationIntegrationTest.java

Just cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/1658
People (@barboras7 ;P ) are complaining that this is often breaking their 7.7.x PR jobs.

JBPM-7170: Ignore randomly failing FormGenerationIntegrationTest (#1658)

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/CloneNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/AbstractCloneCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/CloneNodeCommandTest.java

See https://issues.jboss.org/browse/JBPM-7178
Before:
After:

JBPM-7178: [Stunner] Copy and paste lane with content

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CopySelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CutSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/PasteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/UndoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/BaseSessionCommandKeyboardTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandlerTest.java

See https://issues.jboss.org/browse/JBPM-7134
I removed the use of ```IllegalStateException``` in ```RedoCommandHandler``` however also made all the ```AbstractSelectionAwareSessionCommand``` implementations only invoke the command in response to a keys match **if** the command itself is **enabled**. This IMO is a better fix than simply not throwing the exception.

JBPM-7134: Stunner - Do not notify User about no commands to redo

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/notification/NotificationMessageUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/validation/DiagramElementViolation.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/validation/DomainValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/validation/DomainViolation.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/validation/ValidationService.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/ValidationServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/ValidationServiceImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/validation/ClientDiagramValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/validation/canvas/CanvasDiagramValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/validation/ClientDiagramValidatorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/validation/impl/AbstractDiagramValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/validation/impl/ElementViolationImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/validation/impl/ElementViolationImplBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-backend/src/main/java/org/kie/workbench/common/stunner/project/backend/service/DelegateDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-backend/src/test/java/org/kie/workbench/common/stunner/project/backend/service/DelegateDiagramServiceTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/validation/BPMNValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/validation/BPMNViolation.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/StunnerBpmnApi.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/validation/BPMNValidatorImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/validation/BPMNValidatorImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/validation/no-end.bpmn
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/validation/valid.bpmn
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml

Now, the **BPMN** validation is applied to the diagram and consolidated with the Graph and Model validations that already existed. The validations alerts keep the same template for messages just appending the new validation messages.
The BPMN validation is based on the **jBPM** implementation in the same way as the old designer does.
It was created a `DomainValidator` interface that represents the validator of the diagram domain, for instance: BPMN, CM, DMN... for now only the BPMN is implemented, but if necessary it is prepared to insert other validators to other domains.
The DomainValidators are executed on backend, while the Graph and Model are still executed on client side.
@romartin 
@LuboTerifaj

JBPM-5902 Stunner - Integration with the jBPM validations API

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/impl/ShapeStateAttributeAnimationHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/impl/ShapeStateAttributeAnimationHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/AbstractTextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/AbstractTextEditorBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBoxViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBoxViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/TextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/views/FloatingWidgetView.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/CanvasInPlaceTextEditorControlMultiLineTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/CanvasInPlaceTextEditorControlSingleLineTest.java

See https://issues.jboss.org/browse/RHPAM-883
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1713 for 7.7.x.
(cherry picked from commit f7f0e5c5d6506c008104ee53e8b3c611bba3c2ac)

[7.7.x] RHPAM-883 (JBPM-7181): Stunner - When change name widget disappear by timeout all changes made are lost

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/TextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControlTest.java

See https://issues.jboss.org/browse/JBPM-7180
@tiagodolphine Would you mind taking a look please?
The issue was that the in-place popup was being positioned at the mouse co-ordinate less half the width/height of the containers bounds - which is a really strange thing to do. Ideally the popup should be positioned at the mouse co-ordinate less half the popups height/width; however unfortunately (I tried) the popup height/width is not available until after it is shown and re-positioning it then would lead to flickering.... so I did what was most simple and just positioned at 50% of the CSS min-height/min-width settings. Works much better.

JBPM-7180: Stunner - Name change widget appear in wrong position for containers

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorMultiLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/actions/TextEditorSingleLineBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/TextEditorBox.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControlTest.java

See https://issues.jboss.org/browse/RHPAM-887
This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1719 for 7.7.x
(cherry picked from commit 22992364121974691cd97e2db11ba54f4a11925e)

[7.7.x] RHPAM-887 (JBPM-7180): Stunner - Name change widget appear in wrong position for containers

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRefTest.java

Copy of https://github.com/kiegroup/kie-wb-common/pull/1729
@romartin could you please review?

[7.7.x] RHPAM-617: Stunner - it is not possible to open a process if you put incorrect symbol inside of Event trigger name

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeAction.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeActionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnection.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnectionTest.java

When creating sequence flows using gateways, now the default magnet assigned to the nodes consider the position to choose left or right magnet index. This is a quick win, maybe it can have more detailed rules to assign default connectors considering other restrictions, IMO this should be specified and handled on a new JIRA, after the release. WDYT ?
@romartin 
@LuboTerifaj 
Thanks.

JBPM 6491 - [Stunner] Improve usability and user experience when using connectors

---

kie-wb-common-ala/kie-wb-common-ala-ui/kie-wb-common-ala-ui-client/src/test/java/org/guvnor/ala/ui/client/provider/status/runtime/RuntimePresenterActionsTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/settings/sections/persistence/PersistencePresenterTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/LibraryPlacesTest.java

If an user has no rights to create a Space, the default project could not be created. So the exception was catch and redirected to SpacesScreen to select another Space where the user has rights to see and edit.
Related to:
https://github.com/kiegroup/appformer/pull/328
https://github.com/kiegroup/kie-wb-common/pull/1715

[RHBA-685-7.7.x]: Redirected to Spaces when Organizational Unit is not active

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommandTest.java

https://issues.jboss.org/browse/JBPM-6831
Edge source and target values were not set to null and kept a reference
to the deleted node. This fixes this problem.
This does not fix the undo feature.

JBPM-6831 [Stunner]: Do not allow connectors with empty target/source nodes

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeAction.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeActionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnection.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnectionTest.java

[7.7.x] Improve usability and user experience when using connectors.
Cherry-pick commit 2c73d83c57ae46302169994303f8bed8c13b94e6 related to JBPM-6491.
@romartin 
@LuboTerifaj

[7.7.x] RHPAM-468 Improve usability and user experience when using connectors

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommandTest.java

Issue:
[RHPAM-472](https://issues.jboss.org/browse/RHPAM-472)
[JBPM-6831](https://issues.jboss.org/browse/JBPM-6831) 
Cherry-pick:
commit 35f20f15a0b18b3e1ce724df60020e843760720b
**7.7.x Branch PR's:**
[_this one_](https://github.com/kiegroup/kie-wb-common/pull/1757)
**Master PR's:**
_kiegroup/kie-wb-common_
https://github.com/kiegroup/kie-wb-common/pull/1748
@romartin

[7.7.x] RHPAM-4725 (JBPM-6831) - Stunner - Do not allow connectors with empty target/source nodes

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ResizeControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ResizeControlImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/GraphUtils.java

The `MagnetConnection` locations in the edge are now updated to the current shape magnet position after resize. You can resize a shape with connections, save the diagram and open again to check the new positions.
@romartin 
@LuboTerifaj

JBPM-6702 Issues once resizing a shape: fix connections positions

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/Match.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/NodeMatch.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/ParsedAssignmentsInfo.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/events/IntermediateCatchEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/BoundaryEventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/CatchEventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/DefinitionResolver.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/events/IntermediateCatchEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/BasePropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/BoundaryEventPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/CatchEventPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/EventPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/GatewayPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/LanePropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ThrowEventPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/events/StartEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/events/intermediate/CatchingIntermediateEvent.java

@hasys @LuboTerifaj @romartin I'm fixing this but facing an issue
in `catchingIntermediateMessageEvents.bpmn` we have 
<bpmn2:intermediateCatchEvent id="D9C771AC-6C9D-459F-960F-B3361B75228D" drools:boundaryca="false" name="">
Please notice cancel activity is false.
new marshallers are parsing `cancelActivity == false` (in my view, correctly)
old marshallers are parsing `cancelActivity == true`
that's not what the BPMN file says. So, who's wrong, and why?

JBPM-7156: Stunner - Cancel Activity don't persist after save process

---

kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/main/java/org/kie/workbench/common/forms/dynamic/service/shared/AbstractFormRenderingContext.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/main/java/org/kie/workbench/common/forms/dynamic/service/shared/FormRenderingContext.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/main/java/org/kie/workbench/common/forms/dynamic/service/shared/adf/DynamicFormModelGenerator.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/main/java/org/kie/workbench/common/forms/dynamic/service/shared/impl/MapModelRenderingContext.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/main/java/org/kie/workbench/common/forms/dynamic/service/shared/impl/StaticModelFormRenderingContext.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/test/java/org/kie/workbench/common/forms/dynamic/test/util/TestFormGenerator.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-api/src/test/java/org/kie/workbench/common/forms/dynamic/test/util/TestFormRenderingContext.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-backend/src/main/java/org/kie/workbench/common/forms/dynamic/backend/server/context/generation/dynamic/impl/BackendFormRenderingContextManagerImpl.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/FieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/CheckBoxFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/TextAreaFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/TextBoxFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/date/DatePickerFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/relations/multipleSubform/MultipleSubFormWidget.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/relations/subform/SubFormFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/selectors/listBox/AbstractListBoxFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/selectors/radioGroup/CharacterRadioGroupFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/selectors/radioGroup/DecimalRadioGroupFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/selectors/radioGroup/IntegerRadioGroupFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/main/java/org/kie/workbench/common/forms/dynamic/client/rendering/renderers/selectors/radioGroup/StringRadioGroupFieldRenderer.java
kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-client/src/test/java/org/kie/workbench/common/forms/dynamic/client/helper/MapModelBindingHelperTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-api/src/main/java/org/kie/workbench/common/forms/editor/service/shared/FormEditorRenderingContext.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/main/java/org/kie/workbench/common/forms/editor/backend/service/impl/FormEditorServiceImpl.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/preview/PreviewFormPresenter.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-client/src/main/java/org/kie/workbench/common/forms/editor/client/editor/properties/FieldPropertiesRenderer.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-data-modeller-integration/kie-wb-common-forms-data-modeller-integration-backend/src/test/java/org/kie/workbench/common/forms/data/modeller/service/dataProvider/BeanPropertiesProviderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-api/src/main/java/org/kie/workbench/common/stunner/forms/context/PathAwareFormContext.java

RHPAM-461: Two different radiogroups with the same name have the same id.

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/OrganizationalUnitsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/OrganizationalUnitsScreenTest.java

It's ok to remove this check because the backend already returns only the spaces that the user has access to.

AF-1202: User cannot see space allowed by permission settings

---

kie-wb-common-screens/kie-wb-common-home/kie-wb-common-home-client/src/main/java/org/kie/workbench/common/screens/home/client/widgets/home/HomeView.less
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/menu/ResetPerspectivesMenuBuilder.java

(cherry picked from commit e7a62add60788f1562eb64b60d8497ab046c2bb1)
https://issues.jboss.org/browse/DROOLS-2555
Bundle, but can be merged individually.
https://github.com/kiegroup/kie-wb-common/pull/1801
https://github.com/kiegroup/kie-wb-distributions/pull/762
@jomarko If you could also take a look at this.

[7.7.x] DROOLS-2555 : Broken welcome page layout in IE11

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControlTest.java

Using non default offset (non zero) should make the test more robust.
@manstis please, could you have a look?
This is cherry-pick of #1784 .

[7.7.x] JBPM-7180: Update test

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/legacy/Bpmn2JsonUnmarshaller.java

**7.7.x** cherry pick of 83b2ff24cf93132182f6beced4bddfee216ee3b3 related to **JBPM-6491**.
@romartin 
@LuboTerifaj

[7.7.x] RHPAM-468 Fix connections positions inside Sub-process was persisted wrong (port JBPM-6491)

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanel.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelViewTest.java

https://issues.jboss.org/browse/JBPM-7132
For the Lienzo canvas panel to listen to key press, down and up events
the mouse has to be over it and the panel has to be focused as well.
The mouse part was already implemented and working soo it was not
changed.

JBPM-7132 (Stunner) - Copy of timer is created when copying name to doc

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/LibraryPlacesTest.java

From master: https://github.com/kiegroup/kie-wb-common/pull/1825
@manstis would you mind to review please?

[AF-1209-7.7.x]: Revert "[RHBA-565-7.7.x]: [RHBA-565]: Copied asset is open after ResourceCopiedEvent is observed

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/actions/AbstractCanvasInPlaceTextEditorControlTest.java

Using non default offset (non zero) should make the test more robust.
@manstis please, could you have a look?

JBPM-7180: Update test

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/Canvas.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvas.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvasTest.java

- Get shape using a Map instead of a List on AbstractCanvas
- Remove CDI event after canvas draw
- Selection only call applyState selected/unselected elements
Related to JBPM-7267: Improve computation performance 
@romartin

JBPM-7317 Perfomance Improvements (getShape, applyState, remove CDI Event on draw)

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ResizeControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ResizeControlImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomInput.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomInputDefinition.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/ElementDefinition.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ScriptTaskPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/SubProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/UserTaskPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/tasks/TaskConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/BpmnNode.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/GraphBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/events/IntermediateCatchEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/events/IntermediateThrowEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/Scripts.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/TaskPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/events/intermediate/CatchingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/events/intermediate/ThrowingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/Task.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/UserTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/userTasks.bpmn

collective PR for all these failing tests
Only one test is still failing, and that's because AssignmentsInfo still compares its string representation. All the required fields are present in the marshalled/unmarshalled version
@romartin @hasys please take a look

[JBPM-7281] Stunner - New Marshallers fail migration tests (throwing, boundary, basic)

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseThrowingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

https://issues.jboss.org/browse/RHPAM-1048
New SequenceFlow Rules added for max and min outgoing flows.

RHPAM-1048: Stunner - Intermediate Throwing Event can have more than one outgoing flow

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/SettingsPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/settings/SettingsPresenterTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenServiceImplTest.java

AF-1233: Manually added dependencies do not show up in Dependencies
AF-1236: Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects
AF-1237: Project duplication should use the suffix "-2" instead of " [2]"
* https://github.com/kiegroup/appformer/pull/393
* https://github.com/kiegroup/kie-wb-common/pull/1862

[7.7.x] Settings fixes

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenterTest.java

See: https://issues.jboss.org/browse/RHPAM-899
---
Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/1865

[7.7.x] RHPAM-899: Execution Servers: ContainerNotFound error thrown when removing the container

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenterTest.java

See: https://issues.jboss.org/browse/RHPAM-899
Before:
After:

RHPAM-899: Execution Servers: ContainerNotFound error thrown when removing the container

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseCatchingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

https://issues.jboss.org/browse/RHPAM-1046
New SequenceFlow Rules added for max incoming flow in all intermediate
events.

RHPAM-1046: Stunner - Intermediate Event can have more then one incoming flow

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/SettingsPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/ProjectScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/settings/SettingsPresenterTest.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-backend/src/test/java/org/kie/workbench/common/screens/projecteditor/backend/server/ProjectScreenServiceImplTest.java

AF-1233: Manually added dependencies do not show up in Dependencies
AF-1236: Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects
AF-1237: Project duplication should use the suffix "-2" instead of " [2]"
* https://github.com/kiegroup/appformer/pull/392
* https://github.com/kiegroup/kie-wb-common/pull/1874

Settings fixes

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LocationControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/wires/WiresUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LocationControlImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/UpdateControlPointPositionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml

Now the connector control points position are updated when the parent changes its position.
Related PRs:
https://github.com/kiegroup/lienzo-core/pull/44
https://github.com/kiegroup/lienzo-tests/pull/28
@romartin 
@LuboTerifaj 
@hasys

JBPM-6882 Fix control points inside sub-process

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseThrowingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

Issue:
[RHPAM-1048](https://issues.jboss.org/browse/RHPAM-1048)
[JBPM-7825](https://issues.jboss.org/browse/JBPM-7285)
Cherry-pick:
commit 9eafbc4
7.7.x Branch PR's:
#1859
Master PR's:
[this one](https://github.com/kiegroup/kie-wb-common/pull/1883)

JBPM-7825 (RHPAM-1048): Stunner - Intermediate Throwing Event can have more than one outgoing flow (#1859)

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseCatchingIntermediateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

Issue:
[RHPAM-1046](https://issues.jboss.org/browse/RHPAM-1046)
[JBPM-7824](https://issues.jboss.org/browse/JBPM-7284)
Cherry-pick:
commit 510c51c
7.7.x Branch PR's:
#1860
Master PR's:
[this one](https://github.com/kiegroup/kie-wb-common/pull/1882)

JBPM-7824 (RHPAM-1046): Stunner - Intermediate Events can have more then one incoming flow

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/Canvas.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvas.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvasTest.java

Cherry pick b6c4ccef450a2084ac60227b035363fec923e9ed related to  https://issues.jboss.org/browse/JBPM-7317
@romartin 
@LuboTerifaj

[7.7.x] RHPAM-1159 Stunner - Performance Improvements (Canvas get shape, Selection, Draw CDI event)

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanel.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/view/LienzoPanelViewTest.java

Issue:
[RHPAM-755](https://issues.jboss.org/browse/RHPAM-755)
[JBPM-7132](https://issues.jboss.org/browse/JBPM-7132)
Cherry-pick:
commit 140eac7
7.7.x Branch PR's:
[this one](https://github.com/kiegroup/kie-wb-common/pull/1894)
Master PR's:
#1881

RHPAM-755 (Stunner) - With Process Designer, a copy of the timer is created when you copy text from a name field to a documentation field

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerUIModelMapper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/property/dmn/QNameFieldRenderer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNEditorSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNViewerSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/ExpressionGridCacheImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/DMNEditorToolbar.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/images/shapes/dmn-shapes.css
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerUIModelMapperTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/UndefinedExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/BaseDMNSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/DMNEditorSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/DMNViewerSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/shape/view/handlers/DMNViewHandlersTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/ExpressionGridCacheImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultViewerSession.java

See https://issues.jboss.org/browse/DROOLS-2425
@romartin I added the cache's life-cycle to ```ManagedSession``` (remember our discussions?!)
The issue was that after saving, closing and re-opening the (Context etc) grid was retrieved from the cache however associated to a new "parent" that lead to sizing/re-sizing issues that updated the size of the "old" (disconnected) parent and not the "current" parent. 
The cache's life-cycle is now tied to that of the ```Session``` and hence destroyed when the editor is closed. I also added a ```DMNViewerSession``` (although it is not accessible at the moment, as it is not possible to open read-only versions until I integrate the editor into a "project showcase" - as opposed to "standalone showcase"). This is because I have to cast the ```Session``` …

DROOLS-2425: [DMN Designer] Undo of relation column deletion is not proper

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml

Hey @hasys @tiagodolphine 
This is a fix for the project showcase, as @ederign pointed out there was an error on the pom, it was not starting up on SDM.
Thx

Stunner - Fix project showcase startup on SDM

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/lookup/domain/DomainLookupFunctions.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/lookup/domain/DomainLookupFunctionsTest.java

See https://issues.jboss.org/browse/DROOLS-2628
@romartin The issue was that the ```anyMatch(..)``` in ```isSourceConnectionAllowed(..)``` results in ALL permitted connections matching and hence the target role for all source node types are collected. I've modified the code to get permitted connections whose ```startRole``` matches the source node's role(s) and then collect the ```endRole```. This fixes DMN and fixes all Unit Tests that broke as a result of adding the extra permitted connection in ```DomainLookupFunctionsTest```.

DROOLS-2628: [DMN Designer] DataInput toolbox actions

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionUIModelMapper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionUIModelMapperTest.java

See https://issues.jboss.org/browse/DROOLS-2473
The issue was that the nesting of **all** child grids (FEEL, Java or PMML) should be equal to ```FunctionGrid.nesting + 1```. It was not evident for Java or PMML as these use a "supplementary" grid that explicitly hides the header rather than depending on the nesting.

DROOLS-2473: [DMN Designer] Function language change inconsistency

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/widget/card/body/BodyPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenterTest.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenterTest.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/widget/card/body/BodyPresenterTest.java

ContainerPresenter reacting only on ContainerSpecSelected event when it is the one that is being displayed
Use container.getContainerSpecId() instead container.getContainerName() to map containers
clear status notifications before add new one, added by update actions

[7.7.x] RHPAM-1107: Selected container gets changed

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java

See https://issues.jboss.org/browse/DROOLS-2156
The "Expression Editor" screen now contains the type of expression (identical to the Navigator).

DROOLS-2156: DMN decision table names should be presented as titles in editor screen

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Hello @romartin,
I'm introducing a new profile that will enable to skip gwt compilation of showcases in `downstream-pullrequests` jobs. In normal build, nothing is skipped. Only when you add `-Pno-showcase` to mvn command line, the showcases won't be gwt-compiled.
https://github.com/kiegroup/jbpm-wb/pull/1160
https://github.com/kiegroup/kie-wb-common/pull/1917
https://github.com/kiegroup/drools-wb/pull/877
https://github.com/kiegroup/appformer/pull/401

AF-1248: Add profile to enable skipping of gwt compilation of showcases

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/selectors/CharacterSelectorOption.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/selectors/DecimalSelectorOption.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/selectors/IntegerSelectorOption.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/main/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/relations/TableColumnMeta.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/test/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/basic/selectors/AbstractSelectorOptionTest.java
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/src/test/java/org/kie/workbench/common/forms/fields/shared/fieldTypes/relations/TableColumnMetaTest.java

Backport of https://github.com/kiegroup/kie-wb-common/pull/1852

[7.7.x] JBPM-6913 (RHPAM-462): New Instances in RadioGroups, ListBoxes and Multiple Subforms are missing the required annotation.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/DeleteInputClauseCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/DeleteOutputClauseCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/expressions/types/relation/DeleteRelationColumnCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/util/CommandUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/model/GridCellTuple.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/DeleteInputClauseCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/DeleteOutputClauseCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/relation/DeleteRelationColumnCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/util/CommandUtilsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/model/GridCellTupleTest.java

See https://issues.jboss.org/browse/DROOLS-2644
The issue was that when a column was resized it considered the maximum of the "proposed" width (could be narrower than it was, when deleting a column) and the current column width. I've changed this to consider the "proposed" width and the minimum required for any editors in the column.

DROOLS-2644: [DMN Designer] Deletion of the column causes last column width increase

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/VariableNameTextBoxTest.java

https://issues.jboss.org/browse/RHPAM-470
Process name value and id were fixed in other changes.
Process data variables now won't accept dots. The dots seemed to be the
only invalid character that was still allowed.

RHPAM-470 (Stunner) - Validate and generate the right BPMN process id name and data properties

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/marshall/json/builder/BPMNGraphGenerator.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/marshall/json/parser/BPMN2JsonParser.java

This PR changes places where sysout is used in old marshallers, so that they output to LOG.debug()
#1922 includes a fix for NEW marshallers related to logging
with these 2 PRs merged, console output should be zero
@romartin @hasys @LuboTerifaj

Stunner - Old Marshallers: Move sysout logging to LOG.debug

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/InformationRequirement.java

See https://issues.jboss.org/browse/DROOLS-2721
@jomarko I also tested this fix with https://github.com/kiegroup/kie-wb-common/pull/1955 and it worked OK.

DROOLS-2721: [DMN Designer] InputData node can not be connected to BKM node

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/InformationRequirement.java

OMG DMNv1.1 Specification states InformationRequirements apply to only Decision nodes.
This reverts commit 9dd321788139798539a2d2834b77082dcd3fb8f0.

Revert "DROOLS-2721: [DMN Designer] InputData node can not be connected to BKM node

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphCanvasNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/MorphNodeAction.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphCanvasNodeCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/MorphNodeActionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/TestingGraphInstanceBuilder.java

Now it is possible to morph a docked Event on an activity inside a sub-process and change its locations, save and load, and undo/redo without any issues.
The problem was on the `MorphCanvasNodeCommand.java` that has not handling the dock/undock in case morphing a docked node.
@romartin 
@LuboTerifaj 
@hasys

JBPM-7217 Stunner - Boundary event morphing cause issues

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/definition/adapter/MorphAdapter.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphCanvasNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/definition/adapter/AbstractMorphAdapter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseNonContainerSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/ReusableSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/workitem/BaseServiceTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/workitem/ServiceTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/palette/BPMNPaletteDefinitionBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/palette/BPMNPaletteDefinitionBuilderTest.java

Changes related to this PR:
- Morph from tasks to reusable sub-processes
- Morph from reusable sub-processes to tasks
- Service tasks **not**  allowed to be morphed
- Morph between sub-processes (containers) except reusable (that is not a container)
- Fix morph sub-process with children or docked nodes
PS:  I need to update the `MorphCanvasNodeCommandTest.java`  but depending on this https://github.com/kiegroup/kie-wb-common/pull/1893 to be merged before that includes the test class.
@romartin 
@LuboTerifaj

JBPM-6829 : Stunner - Morphing issues for BPMN activities

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomInput.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ActivityPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/CatchEventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/DeclarationWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/InputAssignmentWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/OutputAssignmentWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ThrowEventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/sequenceflows/SequenceFlowConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/AssignmentsInfos.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/InputAssignmentReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomInputDefinitionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ActivityPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/InputAssignmentWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/InputAssignmentReaderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/AssociationsTest.java

I am "fixing" this in the marshallers, but it's actually a bug at a higher-level. URLEncoding/Decoding should not be handled in the marshallers, it's (I guess) a front-end concern.
In this PR we also
- fix handling of InputSet sections in XML
- disable an unrelated WARN logging which irked me
@romartin @hasys @LuboTerifaj  for review

 JBPM-7373 Should URLDecode/URLEncode assigned values 

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/NameColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/ClauseColumnHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DescriptionColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/InputClauseColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/OutputClauseColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/NameColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/EditableTextHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/TextAreaDOMElement.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/TextBoxDOMElement.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/BaseDOMElementSingletonColumnTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/BaseDOMElementTest.java

See https://issues.jboss.org/browse/DROOLS-2720

DROOLS-2720: [DMN Designer] Do not execute a command to update a cell value if the value has not changed

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/GroupItem.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/ToolboxVisibilityExecutors.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/AbstractDecoratedItem.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/AbstractFocusableGroupItem.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/AbstractGroupItem.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ButtonGridItemImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ButtonItemImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/GroupImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ItemGridImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ToolboxImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/WiresShapeToolbox.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/WrappedItem.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/GroupItemTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ButtonGridItemImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ButtonItemImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/FocusableGroupTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/GroupImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ItemGridImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ItemImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ToolboxImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/WiresShapeToolboxTest.java

Hey @manstis @hasys 
As @mdproctor noticed, the `stunner-lienzo-extensions` module, which was supposed to depend only on lienzo, was also including also a few dependencies from uf/errai, and should be not present.
It was only because the use of the class `org.uberfire.mvp.Command`, so I refactored this for `Runnable`. This way the dependency tree for this module is the excepted one. 
On the other hand I remember some talks with you @manstis about this - you was proposing not to use `Runnable` for client side stuff, is it? If so, which other functional interface can we use?
Thanks!!

Stunner - Clean dependencies for lienzo-extensions module

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

JBPM-7297 (Stunner) - Stunner - doesn't allow to create processes with multiple outgoing connections from Start Event
https://issues.jboss.org/browse/JBPM-7297
Adjusted rules to match BPMN 2.0 specification.

JBPM-7297 (Stunner) - Stunner - doesn't allow to create processes with

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNProjectDiagramEditorMenuItemsBuilder.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNProjectEditorMenuSessionItems.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/ProjectToolbarStateHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/resources/i18n/DMNProjectClientConstants.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/resources/org/kie/workbench/common/dmn/project/client/resources/i18n/DMNProjectClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNProjectDiagramEditorMenuItemsBuilderTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/ProjectToolbarStateHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorMenuItemsBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectEditorMenuSessionItems.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorMenuItemsBuilderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorStub.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectEditorMenuSessionItemsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNProjectDiagramEditorMenuItemsBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNProjectEditorMenuSessionItems.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNProjectDiagramEditorMenuItemsBuilderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementProjectDiagramEditorMenuItemsBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementProjectEditorMenuSessionItems.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/resources/i18n/CaseManagementProjectClientConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/resources/org/kie/workbench/common/stunner/cm/project/client/resources/i18n/CaseManagementProjectClientConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/test/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementProjectDiagramEditorMenuItemsBuilderTest.java

See https://issues.jboss.org/browse/DROOLS-2743
Depends on both the following preceding PRs being merged first:
- https://github.com/kiegroup/kie-wb-common/pull/1975
- https://github.com/kiegroup/kie-wb-common/pull/1981
@romartin Further to the discussion on DROOLS-2743 this PR moves the "export" menu caption out of the class causing the pain to the different sub-classes of ```AbstractProjectDiagramEditor``` (and their related menu/toolbar setup).
Just 4th commit for this PR.. this will be rebased as the other PRs are merged...

DROOLS-2743: [DMN Designer] Download as toolbar button

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/handlers/PackageListBoxViewImpl.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/handlers/PackageListBoxViewImplTest.java

@Rikkola @tomasdavidorg 	
I'm not 100% sure if this is the right solution or I just 'shoot the messenger'.
But what happens is:
If the default package is select at first, all good because the value will be set to "default".
But if we change the package to another one, and then come back to default the select value will be "" and we cannot lookup the selected package.
@Rikkola this issue is for Friday EOD, could you please take a look if this is the best option or should I do something else?

[AF-1406] Asset cannot be created in default package

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeAction.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/FlowActionsToolboxFactory.java

Hi @manstis,
there is a fix for Stunner (any selection or adding new nodes to the canvas lead to error see below).
I considered to use existing `FlowActionsToolbox` instead of new `BPMNFlowActionsToolbox`, but it looks like `FlowActionsToolbox` already in use by both DMN and Process designers, so in my opinion it's better to create new annotation.
Also I am not sure how to test this kinds of issues. I guess so far only Selenium can catch it, am I right?
<details>
<summary>Error log</summary>
<pre>Uncaught exception: Exception caught: Exception caught: CDI Event exception: CommandType=CDIEvent, BeanType=org.kie.workbench.common.stunner.core.client.canvas.event.selection.CanvasSelectionEvent, BeanReference=org.kie.workbench.common.stunner.core.client.canvas.event.selection.CanvasSelectionEve …

Fix for ambiguous Dependency for CreateNodeAction in Stunner

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ControlPointControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LocationControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/drag/DragBoundsEnforcer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/WiresConnectorView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ControlPointControlImplTest.java

Now it is now possible to move bend points of a connector outside of the canvas area.
Note: I inserted a margin of 10px to avoid the bend point to be dropped exactly on the canvas bounds that was not easy to drag it back into the canvas.
@LuboTerifaj 
@wmedvede (adding you to help on the review since @romartin is on PTO)
related:
https://github.com/kiegroup/lienzo-core/pull/57

JBPM-6883 Stunner - can't move with bend points

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/general/ClearExpressionTypeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/ClearExpressionTypeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNProjectEditorMenuSessionItems.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommands.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/session/command/SaveDiagramSessionCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommandsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/session/command/SaveDiagramSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/session/EditorSessionCommandsTest.java

See https://issues.jboss.org/browse/DROOLS-2827
This PR removes the automatic creation of diagram SVGs when the file is saved from DMN.

DROOLS-2827: [DMN Designer] SVG produced for each save operation

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/Ids.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java

Restore old behavior: IDs for variables are now non-namespaced as before, i.e. IDs==variable names. 
This should be backwards compatible with the old designer (although quite fragile, as we already know)

JBPM-7620: Stunner - NewMarshallers - Variable identifiers

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/README.md
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BPMNBackendService.java

Let's update the flag so that it is no longer "experimental", as per @krisv's suggestion
-Dbpmn.marshaller.legacy=true
disables the new marshallers. Default: **false**; i.e., use the new marshallers.
cc: @hasys @LuboTerifaj

JBPM-7619: Stunner - New Marshallers: rename flag

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ExpressionEditorColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionColumnNameHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionColumnRenderer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridRenderer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/util/RendererUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionColumnRendererTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridRendererTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/BaseNameAndDataTypeColumnRendererTest.java

See https://issues.jboss.org/browse/DROOLS-2913
As with all these "in grid" editor changes; this PR will be merged after the others in the queue.

DROOLS-2913: [DMN Designer] Data-types: Grid: FunctionDefinition

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/Processes.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/SubProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/GraphBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/SubProcessPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/BPMNDiagramMarshallerBase.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/events/intermediate/DockedEventsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/JBPM_7645.bpmn

This fixes the issue. 
Please notice that the underlying issue is that processing nodes in the sequence coming from the XML may lead to unexpected results, when the ordering is not the "right" one. In this case, we had 2 issues
**Marshalling**. Docked nodes are rendered (added) to the XML representation *before* the nodes they were docked to (e.g., the event before its parent task); the generated XML looked like this:
```xml
<bpmn2:boundaryEvent id="_D37CB404-5190-4CF4-92A1-E5BDBFDD3276"
drools:boundaryca="true"
drools:dockerinfo="126.0^61.0|"
name="Event"
attachedToRef="_6A26F0A2-3368-4769-B9E9-A6290530ED8F">
<bpmn2:timerEventDefinition id="_7K3JlqRjEeimWcuZ5UDpfg"/>
</bpmn2:boundaryEvent>
<bpmn2:businessRuleTask id="_6A26F0A2-3368-4769-B9E9-A6290530ED8F" name="Task"> …
```

JBPM-7645 Stunner: New Marshallers - task w/ docked node in subprocess

---

kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/preferences/ApplicationPreferences.java
kie-wb-common-services/kie-wb-common-services-backend/pom.xml
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/preferences/KieTimeZonePreferencesLoader.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/preferences/KieTimeZonePreferencesLoaderTest.java
kie-wb-common-widgets/kie-wb-common-ui/pom.xml
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/util/TimeZoneUtils.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/util/TimeZoneUtilsTest.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/AbstractCellFactory.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCell.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/test/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCellTest.java

See: https://issues.jboss.org/browse/DROOLS-2777
---
_"Cherry picking"_ https://github.com/kiegroup/kie-wb-common/pull/2038 on `6.5.x` branch. We don't need a PR for `drools-wb` in the `6.5.x`.

[6.5.x] DROOLS-2777: Guided Decision Table is changing date field value based on the timezone

---

kie-wb-common-services/kie-wb-common-services-api/src/main/java/org/kie/workbench/common/services/shared/preferences/ApplicationPreferences.java
kie-wb-common-services/kie-wb-common-services-backend/pom.xml
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/preferences/KieTimeZonePreferencesLoader.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/preferences/KieTimeZonePreferencesLoaderTest.java
kie-wb-common-widgets/kie-wb-common-ui/pom.xml
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/util/TimeZoneUtils.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/util/TimeZoneUtilsTest.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/AbstractCellFactory.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCell.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/test/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCellTest.java

See:
https://issues.jboss.org/browse/DROOLS-2777
---
Demo:
- First, we need to set the `user.timezone` property:
- ..and then, we can change the timezone to **"Europe/Vilnius"** in the server (`systemsetup -settimezone Europe/Vilnius`):
- ..or even change to **"Europe/Prague"** (`systemsetup -settimezone Europe/Prague`):
..the client side is always using the timezone from the server (from `user.timezone`), so the displayed value will always be consistent.
cc @etirelli 
---
- https://github.com/kiegroup/kie-wb-common/pull/2038
- https://github.com/kiegroup/drools-wb/pull/911

DROOLS-2777: Guided Decision Table is changing date field value based on the timezone

---

kie-wb-common-stunner/README.md

Fixing copyright info in Stunner Showcasse README to reference the official file and correct IDEA Preferences config location in Stunner showcase README.

Copyright setup change for Stunner Showcase README per PR feedback and fix

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/factories/DecisionNavigatorBaseItemFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/decision/factories/DecisionNavigatorBaseItemFactoryTest.java

@manstis @hasys please have a look, one more case to check.

JBPM-7689: Focus canvas after node selection in DMN navigator dock

---

kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-backend/src/main/java/org/kie/workbench/common/screens/datasource/management/backend/core/impl/DefaultDriverInitializerImpl.java
kie-wb-common-screens/kie-wb-common-datasource-mgmt/kie-wb-common-datasource-mgmt-backend/src/test/java/org/kie/workbench/common/screens/datasource/management/backend/core/impl/DefaultDriverInitializerTest.java

* https://github.com/kiegroup/kie-docs/pull/1056
* https://github.com/kiegroup/kie-wb-common/pull/2102
Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/2101

[7.11.x] AF-1549: jdbc drivers should not be download by default

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListViewTest.java

This PR is corollary of issues:
- https://issues.jboss.org/browse/DROOLS-2816
- https://issues.jboss.org/browse/DROOLS-2818
- https://issues.jboss.org/browse/DROOLS-2820
@manstis @danielzhe @karreiro would you mind to have a look?

DROOLS-2956: IE11 Prevent error due to unsupported element.remove

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/InputClauseColumnHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/OutputClauseColumnHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationColumnHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/NameAndDataTypeHeaderMetaData.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/NameAndDataTypeHeaderMetaDataTest.java

See https://issues.jboss.org/browse/DROOLS-3010
This PR defers retrieval of the ```HasTypeRef``` in ```NameAndDataTypeHeaderMetaData``` to _when it is needed_ vs when ```NameAndDataTypeHeaderMetaData``` was instantiated.

DROOLS-3010: [DMN Designer] Regression - Unable to add InputClause columns

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-core/src/test/java/org/kie/workbench/common/services/backend/compiler/utils/MavenUtilsTest.java

Removed check that maven repo ends with ".m2/repository"
Added isDirectory check

BAQE-550: Update MavenUtilsTest to be more robust

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-core/src/test/java/org/kie/workbench/common/services/backend/compiler/ConcurrentBuildTest.java

This PR is a short-term workaround before [PR-2136]( https://github.com/kiegroup/kie-wb-common/pull/2136) is merged. It will be removed once the above mentioned PR is reviewed by @porcelli and merged. 
The ConcurrentBuildTest gets stuck on Windows and after 4 hours, the Jenkins job is aborted. This means that we do not have any test results for Windows.
@porcelli @desmax74 could you take a look, please?

AF-1569 workaround for failing jenkins job

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/common/DataTypeUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeSelectView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidgetTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/common/DataTypeUtilsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeSelectViewTest.java

See https://issues.jboss.org/browse/DROOLS-3028
This PR:
- Adds the `OptionGroup` to the Properties Panel data-type selector
- Sorts data-types added to the data-type selector in the Data Types dialog
This ensures the content of both is consistent.

DROOLS-3028: [DMN Designer] Consolidate data type select boxes

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/InferNamesProjectImportServiceImplTest.java

simplified (yet more correct) way to infer project names that avoid the issue of invalid URI/URL for protocol http or others than file:// and git://

RHPAM-1592: fix for the reported issue

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/InferNamesProjectImportServiceImplTest.java

simplified (yet more correct) way to infer project names that avoid the issue of invalid URI/URL for protocol http or others than file:// and git://
cherry-pick of this https://github.com/kiegroup/kie-wb-common/pull/2165

RHPAM-1592: fix (master) for issue found on project name infer

---

kie-wb-common-cli/kie-wb-common-cli-migration-tool/pom.xml
kie-wb-common-services/kie-wb-common-data-modeller-core/pom.xml

Fixes the warning
"[WARNING] Parameter tasks is deprecated, use target instead"
See maven-antrun-plugin [docs](http://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html#tasks)

Use <target> instead of deprecated <tasks> in antrun plugin config

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ExpressionPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/resources/wrong_decision.dmn

/cc @jomarko @manstis @etirelli requirement change as per DROOLS-3116

DROOLS-3116 empty Literal Expression is preserved

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommandTest.java

Hi @tiagodolphine, @LuboTerifaj,
this line was removed (see link below) and I am not sure, should we return it or not, but with this line I can't reproduce issue any more. https://github.com/kiegroup/kie-wb-common/commit/490271a1ea9403447892229075762e90034fc5dd#diff-75800ba6215a86b707fa744b75e5c7a2L116
Steps To Reproduce:
1. model process with more then one node
2. select all or part of them by group selection
3. press Delete button
Before fixt:
Nodes disappear but selection box is still visible.
After fix:
Nodes disappear and selection box is also not visible any more.

Process Designer: Clear selection when delete group of nodes

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/event/FormFieldChanged.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/container/FormsContainer.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/widgets/container/FormsContainerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BPMNDiagramImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/DiagramSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/service/BPMNDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/service/ProjectType.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/service/BPMNDiagramServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/BPMNDiagramServiceImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/StunnerBPMNEntryPoint.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/diagram/DiagramTypeService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/diagram/DiagramTypeServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/filters/BPMNDiagramFilterProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/session/BPMNSessionInitializer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/StunnerBpmnClient.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/StunnerBPMNEntryPointTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/diagram/DiagramTypeServiceTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/filters/BPMNDiagramFilterProviderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/session/BPMNSessionInitializerTest.java

Hide / Show Case Management Properties whether the diagram is under a case project and the `adhoc` property is set to **true**
To test it is necessary 2 conditions:
- the existence of **.caseproject** file on the root project filesystem on the .niogit, on the WB just create a case project should be enough because it creates this file.
- the property adhoc set to true or false on the forms
Since the adhoc condition can be changed at runtime, you can test setting to true/false and see the Case Management properties be shown/hide.
@romartin 
@LuboTerifaj

JBPM-7604 Stunner - Showing case management properties for cases only

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/QName.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/types/BuiltInType.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/property/dmn/types/BuiltInTypeTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricher.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionUpdateHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidgetTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/QNameConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionUpdateHandlerTest.java

See https://issues.jboss.org/browse/DROOLS-3185
This PR requires https://github.com/kiegroup/kie-wb-common/pull/2204 to be first merged (this PR has one commit itself but 10 more - at the time of writing - for the related PR, for DROOLS-3143)...
This PR also fixes some other issues with the change for "Built in types" in DMN 1.2 (meaning they no longer require a name space prefix or URI).

DROOLS-3185: [DMN Designer] Change Literal Expression to Decision Table

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/docks/AuthoringWorkbenchDocks.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestReportingDocksHandler.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.html
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/WorkbenchConstants.properties
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/docks/AuthoringWorkbenchDocksTest.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestReportingDocksHandlerTest.java

https://issues.jboss.org/browse/DROOLS-3173
Fixes several smaller issues. 
Does not cover "Clean alert panel when a run succeed"
Does cover opening the test results panel automatically for the legacy test scenarios.
https://github.com/kiegroup/kie-wb-common/pull/2223
https://github.com/kiegroup/drools-wb/pull/981

DROOLS-3173 : Scenario Simulation Docks support improvements

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/Definitions.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/factory/AbstractDMNDiagramFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/factory/DMNDiagramFactoryImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DefinitionsConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DefinitionsConverterTest.java

See https://issues.jboss.org/browse/DROOLS-2890
This PR adds `Namespace` to the UI (hurrah!) and makes `Name` editable (a _default_ is now only set if the value in the model is empty). `ID` and `Description` were already present.

DROOLS-2890: [DMN Designer] DMNDiagram properties

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsCanvasSessionHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsCanvasSessionHandlerTest.java

Now changes on forms, for instance, a Task name can be undone and redone.
Changed the `FormsCanvasSessionHandler` to use the `SessionCommandManager` that has support to the command registry that allows the undo/redo.
@romartin 
@LuboTerifaj

JBPM-7853 Stunner - Changes on the forms panel cannot be undone/redone

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/AdHocSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BPMNDiagramImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/EmbeddedSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/cm/CaseFileVariables.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/cm/CaseManagementSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/MultipleInstanceSubprocessTaskExecutionSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/HashCodeAndEqualityTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/cm/CaseFileVariablesTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/processes/RootProcessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/RootProcessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/CaseFileVariableReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/MultipleInstanceSubProcessPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ProcessPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/processes/RootProcessConverterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/CaseFileVariableReaderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/VariablesProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentsEditorWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableDeleteHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/VariableProviderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableDeleteHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/definition/CaseManagementDiagram.java

https://issues.jboss.org/browse/JBPM-7601
This adds case file variables to the new Designer. They idea is to
replicate the same functionality of the old Designer. Other than minimal
UI differences they both will work identically.
The variables will be displayed in a different section called Case Data,
under the Process Data section, where available. Case File Variables can
be used on the MI Collection Input/Output in Multiple Instance Processes
as well.

JBPM-7601 (Stunner) - Case Files

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/cm/CaseIdPrefix.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/cm/CaseManagementSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/CustomElement.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/processes/RootProcessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/RootProcessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ProcessPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/processes/RootProcessConverterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/VariableProviderTest.java

Adding a new property **CaseIdPrefix** to the CaseManagementSet on the `BPMNDiagramImpl`.
This property is a String input, the new marshallers were updated to support the new property.
@romartin 
@evacchi 
@LuboTerifaj

JBPM-7890 add caseIdPrefix to the CaseManagementSet on BPMN

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ServiceTaskPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/tasks/TaskConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ServiceTaskPropertyReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/RestServiceTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/ServiceTask.java

As discussed, this fixes all of the tests except [this](https://github.com/kiegroup/kie-wb-common/blob/8ba0a5c6b8764030dc27ec27644e0737363bb0cb/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java#L2965-L2966)
```java
assertEquals(WorkItemDefinitionMockRegistry.EMAIL.getDocumentation(),
email.getGeneral().getDocumentation().getValue());
```
because the expected value there is "index.html", while now it is an empty string.
The failure in this test is to be expected, because the tests we're fixing **expect** this value to be **the empty string**. 
So I suppose either **this** test is wrong, or the others. Which is which? …

 JBPM-7726: Stunner - (Un)Marshaller tests for Rest Service Tasks are failing

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DecisionTablePropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/InputClausePropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/OutputClausePropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/resources/qGslQdo2.dmn

DROOLS-3281
[DMN Designer] The output name is valorized for single output decision
table
DROOLS-3262
[DMN Designer] The `defaultOutputValue` and the `outputValue` are being
persisted when the value is empty in the UI
/cc @jomarko @karreiro @manstis

DROOLS-3262 DROOLS-3281 [DMN Designer] Decision Table In/Out clause fixs

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ContextPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/resources/DecisionWithContextWithDefaultResult.dmn
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/resources/DecisionWithContextWithoutDefaultResult.dmn
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextEditorDefinition.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextUIModelMapper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricher.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridRenderer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGridRenderer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/BaseContextUIModelMapperTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextUIModelMapperTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridRendererTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGridRendererTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGridTest.java

See https://issues.jboss.org/browse/DROOLS-3269
Video of manual testing: https://youtu.be/Yc7SXcWT1N8
@tarilabs I'd like you just to look at the backend marshalling changes that [create](https://github.com/kiegroup/kie-wb-common/pull/2255/files#diff-a3d8fc8bd84bfda135fff7c119953302R44) and [remove](https://github.com/kiegroup/kie-wb-common/pull/2255/files#diff-a3d8fc8bd84bfda135fff7c119953302R69) a `ContextEntry` for the _default result_ row required by the UI (but not DMN XML, if no default result is defined).

DROOLS-3269: [DMN Designer] Context: Default can be any expression type

---

kie-wb-common-dmn/pom.xml

```
kie-wb-common-dmn overrides 'version.org.apache.sshd' defined in jboss-integration-platform-parent from '1.6.0' to '1.6.0'
kie-wb-common-dmn overrides 'version.org.eclipse.jgit' defined in jboss-integration-platform-parent from '4.8.0.201706111038-r' to '4.8.0.201706111038-r'
```
These overrides are no longer necessare and keeping them in will introduce unnecessary inconsitencies in the future. @manstis please check and merge

Remove useless property overrides

---

kie-wb-common-profile/kie-wb-common-profile-api/src/main/java/org/kie/workbench/common/profile/api/preferences/Profile.java
kie-wb-common-profile/kie-wb-common-profile-api/src/main/java/org/kie/workbench/common/profile/api/preferences/ProfilePreferences.java

It breaks GWT superdevmode. Also, adding license headers.

AF-1717: ProfilePreferences should not use a String constant

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/QName.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/types/BuiltInType.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/property/dmn/QNameTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/QNamePropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/QNamePropertyConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/common/DataTypeUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidgetTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeSelectViewTest.java

See https://issues.jboss.org/browse/DROOLS-3334
---
This PR reverts the https://github.com/kiegroup/kie-wb-common/pull/2266 to solve the [DROOLS-3334](https://issues.jboss.org/browse/DROOLS-3334).
In a future PR (on master), we  can differentiate `Structure` DTs and `Undefined` DTs, but for the `7.14.x` branch, we're following the most secure approach, so we're reverting the change.
---

DROOLS-3334: [DMN Designer] Data Types - "Structure" Data Types are being set as "Undefined"

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/keyboard/AbstractCanvasShortcutsControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/keyboard/AbstractCanvasShortcutsControlImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControlTest.java

Hey @jomarko 
Looking at the VCS history I see you created this stuff, so as I'm fixing a bug here, would like you to double check. 
The issue is about calling the `canvas.focus()` method on each `element` registration, in the `AbstractCanvasShortcutsControlImpl`. When opening an existing process in IE11 is causing some issues, as the canvas has not been yet well initialized. Also it's not correct because if you open a process with, let's say 100 elements, it will call `focus` also 100 times...
Anyway, probably this call is quite old as the canvas is being focused anyway when removing it. Please can you double check?
It depends on https://github.com/kiegroup/lienzo-core/pull/72
CC @hasys ^^
Thanks in advance!
Roger

RHPAM-1681: Stunner - any change on the canvas scroll process to left-top corner in IE11

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/factory/AbstractBPMNDiagramFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/factory/BPMNGraphFactoryImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-api/src/main/java/org/kie/workbench/common/stunner/bpmn/project/factory/impl/BPMNProjectDiagramFactoryImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-api/src/test/java/org/kie/workbench/common/stunner/bpmn/project/factory/impl/BPMNProjectDiagramFactoryTest.java

`BPMNGraphFactoryImpl` is causing an issue with dependency injection after the PR merge regarding the Case Management Wizard for BPMN.
Another fix were added regarding diagram creation on a _Non Project_  case, where the Id and Name were set to `null`, testing with the Standalone showcase.
@romartin @xiezhang7 
@LuboTerifaj

JBPM-7956 Stunner - fix standalone showcase

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImplTest.java

With @pefernan found that exist the possibility that if crytp:passw contains a null value when it tries to get credentials it fail. So if any credential value is null, credentials are not set.
* https://github.com/kiegroup/appformer/pull/545
* https://github.com/kiegroup/kie-wb-common/pull/2305
@pefernan @ederign would you mind to review?

[AF-1715-migration-import]: Added null checking condition for credentials

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImplTest.java

With @pefernan found that exist the possibility that if crytp:passw contains a null value when it tries to get credentials it fail. So if any credential value is null, credentials are not set.
@ederign would you mind to review?

[AF-1715-7.14.x]: Added null checking condition for credentials

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/add/AddAssetScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/assets/add/AddAssetScreenTest.java

Moved the filter where it should be. It solves 1727 and also the duplicated NewResourceHandler for Case management legacy.

AF-1727: Case Management NewResourceHandler wrongly visible with PLANNER_AND_RULES profile

---

kie-wb-common-stunner/kie-wb-common-stunner-backend/src/main/java/org/kie/workbench/common/stunner/backend/service/BackendFileSystemBootstrap.java

Hey @ederign @hasys @manstis 
See https://issues.jboss.org/browse/JBPM-8026
As @ederign hopefully pointed out, the default git repository for stunner (`stunner.git`) is being created in the wrong location. Although this module is only used in some showcases and does not affect the BC, let's put the repository where appformer expects it.
Related to https://github.com/kiegroup/drools-wb/pull/1018
Thanks!

JBPM-8026: Fixed wrong root path for standalone backend FS.

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommands.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/session/EditorSessionCommands.java

See https://issues.jboss.org/browse/DROOLS-3395
This PR simply moves registration of commands to a method that is overridden by the DMN Editor.
This prevents Errai from invoking the `@PostConstruct` method twice.

DROOLS-3395: [DMN Designer] Two copies of node are created

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DefaultDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DefaultDiagramViewer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DiagramLoader.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DiagramLoaderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/presenters/diagram/impl/DiagramViewerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/preferences/StunnerPreferencesRegistryLoader.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultCanvasElementListener.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultCanvasShapeListener.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/DiagramPresenterScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/ShowcaseDiagramService.java

Hey @hasys @nmirasch @cristianonicolai @krisv 
Some background - From the console perspective they are considering to move from the actual SVG image used for the process to a real canvas (Stunner). IMO that's great for several reasons: Stunner already provides editor/viewer components, it's much more powerful on the UI and because of they can use the Stunner API as well. So I recommended to @nmirasch to give it a quick try to the Stunner's `DiagramViewer` component, which allows to display a process in a canvas and use the api to manage the shapes, etc. 
But I noticed there were a few bugs on the `DiagramViewer` and `DiagramEditor` types, which were easy to fix and I just created the ticket [JBPM-8013](https://issues.jboss.org/browse/JBPM-8013) and this PR which provides the fixes: …

JBPM-8013: Stunner - Diagram Editor/Viewer components are not working

---

kie-wb-common-ala/kie-wb-common-ala-openshift/kie-wb-common-ala-openshift-provider/src/main/java/org/guvnor/ala/openshift/access/impl/OpenShiftAccessInterfaceImpl.java

Fixed fabric8 client compatibility issue (https://github.com/fabric8io/kubernetes-client/commit/43f532fca44b28c4fe9c786aaf50e5d6232e5508) as result of raising fabric8 client version to 4.1.0 (Related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/878) which is a pre-requisite for a larger PR (Related PR: https://github.com/kiegroup/droolsjbpm-integration/pull/1611)

JBPM-7834: Provide OpenShiftStartupStrategy

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/ParentsTypeMatchPredicate.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/FilteredParentsTypeMatcherTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/ParentsTypeMatcherTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/rule/ext/impl/ConnectorParentsMatchConnectionHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/rule/ext/impl/ConnectorParentsMatchContainmentHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/SequenceFlow.java

Hi @romartin, @tiagodolphine, @LuboTerifaj,
I found a regression caused by https://github.com/kiegroup/kie-wb-common/pull/2306
This is a fix and fixed tests.
In short new Embedded subprocess bounds exceeded tests was extended by https://github.com/kiegroup/kie-wb-common/pull/2306 for all types of sub-processes and BPMNDiagram, but Lane were forgotten.
But it is not possible just add Lane to this rule, because it can be a situation when you want to connect nodes from top level process with nodes inside of Swimlane and it is a valid case. Another valid case is connecting two nodes from different Swimlanes.
So, I removed BMPNDiagram from checked parents and extended rule to ignore nodes without checked parent as it was before https://github.com/kiegroup/kie-wb-common/pull/2306.
Thank you!

JBPM-8039 - It is not possible to connect nodes inside of swimlane

---

kie-wb-common-forms/kie-wb-common-forms-integration-tests/src/test/java/org/kie/workbench/common/forms/integration/tests/formgeneration/FormGenerationIntegrationTest.java

Since the main reason for the random failures of this test was the parallel build and it is not disabled, unignoring the tests. This should have several green tests before it gets merged (to be sure the random failure character is truly gone).
@jhrcek @manstis can you please approve?

JBPM-7170 unignore FormGenerationIntegrationTest

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorDock.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/factories/DecisionNavigatorBaseItemFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorDockTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/decision/factories/DecisionNavigatorBaseItemFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/test/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreenTest.java

See https://issues.jboss.org/browse/DROOLS-3431
@karreiro I changed things around a bit to also set the `Diagram` on the `DecisionNavigatorPresenter`. The `Diagram` is available before the `Session` and before Stunner attempts to render the Graph (and hence trigger the `CanvasElementAddedEvent` events that lead to the undesirable behaviour reported by @jomarko).

DROOLS-3431: [DMN Designer] Error after reopening

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/DMNModelInstrumentedBase.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/factory/DMNDiagramFactoryImplTest.java

/cc @manstis @jomarko @danielezonca 
Linked PR also : https://github.com/kiegroup/drools/pull/2205
The linked PR fixes the issue.
This PR additionally avoid the issue beforehand.

DROOLS-3469 DMN xml NS definition on non-root xml elements

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/ClusterLibraryObserver.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/delete/DeleteOrganizationalUnitPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/delete/DeleteOrganizationalUnitPopUpPresenterTest.java

Now observing AfterDeleteOrganizationalUnitEvent instead of RemoveOrganizationalUnitEvent.
* https://github.com/kiegroup/appformer/pull/575
* https://github.com/kiegroup/kie-wb-common/pull/2348

[AF-1750]: Added Clusted event to sync spaces.

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/export/LienzoCanvasExport.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/export/LienzoCanvasExportTest.java

When saving the diagram, the SVG image is generated and this process uses a Wrapped `Context2D` to generate the SVG. 
It is necessary to draw the original `Context2D` from Canvas after the SVG generation is complete, otherwise, the canvas remains empty.
@romartin I think this was removed during some refactor necessary for the infinite canvas (https://github.com/kiegroup/kie-wb-common/commit/1082e1994c9ed231384984b8bb8b9da2205b56fe#diff-22baa68f555ac85b7f154466ae47e825L76)
@LuboTerifaj

JBPM-8098 Stunner - Canvas becomes empty after saving the diagram

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRefTest.java

- Not all MVEL expressions are evaluated
- Allows basic client validation of expression
- Complete compilation and validation delegated to runtime
- Allows expressions like #{processVar}, #{procObj.property} and #{System.getProperty("default.value", procVar)}

JBPM-8091 - Allow basic mvel expressions

---

kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-api/src/main/java/org/kie/workbench/common/services/verifier/api/client/api/Initialize.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-api/src/main/java/org/kie/workbench/common/services/verifier/api/client/api/RequestStatus.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/pom.xml
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/AnalysisReporter.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/Poster.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/Receiver.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/VerifierWebWorkerConnection.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/VerifierWebWorkerConnectionImpl.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/resources/org/kie/workbench/common/services/verifier/reporting/VerifierReporting.gwt.xml

https://issues.jboss.org/browse/DROOLS-2848
Some changes I found necessary when adding the V&V for DMN tables. I removed the changes for the table. Just pushing these in so the code does not get stale.
The PR bundle:
https://github.com/kiegroup/kie-wb-common/pull/2295
https://github.com/kiegroup/drools-wb/pull/1004

DROOLS-2848 : Make the Verifier Web Worker connector reusable for different V&V types

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/SessionScreenView.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/SessionScreenViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/views/session/ScreenPanelViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/views/session/ScreenPanelViewImplTest.java

This PR fixed the DMN and Stunner _standalone_ webapps following [this](https://github.com/kiegroup/kie-wb-common/commit/5099ea6c052402cb6eda6f7ba8e69d335f70f554).
The _canvas_ needs a unbreakable chain of `RequiresResize` from AppFormer to the editor. Furthermore the size of the _canvas_ is taken from the pixel dimensions of its parent. The _standalone_ webapps had a break in pixel sizes in the `Widget` inbetween AppFormer's `PageViewImpl` (a tabs content) and Stunner's `SessionPresenterView` (the graph editor view).
Before JBPM-7790's CSS fix was merged DMN had a CSS selector for `.tab-content > div > div > div { height: 100% }` that had the same effect (but was wrong as it clearly broke JBPM console).

JBPM-7790 - Process instance diagram zoom controls. Fix for standalone webapps

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/FilteredParentsTypeMatcher.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/ParentsTypeMatchPredicate.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/util/ParentsTypeMatcher.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/rule/ext/impl/AbstractParentsMatchHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/rule/ext/impl/ConnectorParentsMatchConnectionHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/rule/ext/impl/ConnectorParentsMatchContainmentHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/FilteredParentsTypeMatcherTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/ParentsTypeMatcherTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/rule/ext/impl/ConnectorParentsMatchConnectionHandlerTest.java

Now If you have connected node you can move it outside of swimlane (or bring it inside of any swimlane).
This should not be possible with subprocesses, that should be validated as well.
I made some modifications now it seems to be working better, however, I think this part deserves a refactoring in the future to make it more simple and clear, now it is quite complicated to follow and debug the rules evaluation for this case. 
@romartin 
@hasys

JBPM-8069 Stunner - it is not possible to move in/out of swimlane connected node

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/documentation/DefaultDiagramDocumentationView.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/documentation/BPMNDocumentationView.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditor.java

See https://issues.jboss.org/browse/DROOLS-3537
Further to https://github.com/kiegroup/kie-wb-common/pull/2363 whilst it is acceptable to use the `DocumentationView` _override_ specified in the JavaDocs for the BPMN editor in _standalone_ mode; when there are several Stunner-based Editors in the workbench (Business Central, that has BPMN, DMN and CM) the override affected ALL such editors. This change allows the different domains to provide their own `DocumentationView` implementation.

DROOLS-3537: [DMN Designer] Unexpected error appears when diagram is created

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/XMLEncoderDiagramMetadataMarshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/XMLEncoderDiagramMetadataMarshallerTest.java

Further to https://github.com/kiegroup/kie-wb-common/pull/2406 this PR ensures the `XMLEncoder` is flushed to the `OutputStream` before the stream is closed (by the try with resources block)

[Stunner] Use try with resources. Ensure XMLEncoder is flushed before Stream is closed

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreen.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreenTest.java

@danielezonca, @Rikkola, could you please take a look?
I know this solution is not exactly perfect, but it cannot be achieved directly using `DateTimeFormat` and it is not possible to use `SimpleDateFormat` because of GWT.
Before:
After:

DROOLS-3222 Test duration should not start with zeros

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItem.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/common/DataTypeEditModeToggleEvent.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/test/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreenTest.java

See: https://issues.jboss.org/browse/DROOLS-3399
---
- https://github.com/kiegroup/appformer/pull/609
- https://github.com/kiegroup/kie-wb-common/pull/2411
---
There's a corner case on this PR. When the user opens two DTs on edit mode and saves the first one, the "Save" button is enabled. However, since we'll prohibit the parallel edition ([DROOLS-3015](https://issues.jboss.org/browse/DROOLS-3015)), I don't think we need to fix this here.

DROOLS-3399: [DMN Designer] Data Types - Disable the global 'Save' button when edit mode is enabled

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/documentation/ClientBPMNDocumentationService.java

Hey @hasys  @wmedvede 
This is a quick fix for [JBPM-8157](https://issues.jboss.org/browse/JBPM-8157). 
I have reassigned the ticket to @tiagodolphine , because I'm not really sure if that's the right fix and also because there are still missing the tests, but at least this commit fixes this bug, which is urgent, as it's being produced lot of times and really on the initial authoring stages... 
So for now, if you agree, let's commit this fix and let @tiagodolphine check and test it properly once he's back. WDYT?  
Thanks!

JBPM-8157: Stunner - Documentation page produces an error when a process with a UserTask is being opened

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNEditorSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/DMNEditorSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/event/registration/CommandRegisteredEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/event/registration/RegisterChangedEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/command/RequestCommandManager.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/UndoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/command/RequestCommandManagerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/UndoSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/registry/impl/ClientCommandRegistry.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/session/CaseManagementEditorSession.java

Hi @romartin, @LuboTerifaj,
I investigated this issued and there are my findings:
**Short version:**
There are two EventHandlers for `MouseUp` event: on **lienzo-core** side and on **Stunner** side. Both handlers are executed when we finishing drag an element, but **lienzo** side handler is **_first_** in the queue of handlers and it execute check of command registry are there any commands to undo or not.
**Stunner** handler executes **_after_** **lienzo-core** handler and this handler adding new command to command registry and that's why first action doesn't unlock undo button, but works for second and following actions (and that's why it is possible to undo first action if button already unlocked).
As _temporary_ solution I added new event after new command added to registry and handle …

RHPAM-1534 - Stunner - Not possible to use Undo action immediately

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-core/src/test/java/org/kie/workbench/common/services/backend/compiler/plugin/KieMetadataTest.java

See https://issues.jboss.org/browse/AF-1819

AF-1819: Fix KieMetadataTest.compileAndLoadKieJarMetadataAllResourcesPackagedJar()

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/pom.xml
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/resources/i18n/WorkbenchConstants.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestResultDonutPresenter.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreen.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingView.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.css
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.html
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/KieDefaultWorkbenchClient.gwt.xml
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/WorkbenchConstants.properties
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestResultDonutPresenterTest.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreenTest.java

https://issues.jboss.org/browse/DROOLS-3234
This has been a time sink for few reasons. I suggest this layout since if we make the donut look like the wireframe we need to edit the widget and that is even more time consuming.
Optionally we can drop the legend specified in the Donut widget and make a custom separate item that looks like the original design. This will not take that long.

DROOLS-3234 : Add a Donut widget to improve the visualisation of test report screen

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-core/src/test/java/org/kie/workbench/common/services/backend/compiler/plugin/KieMetadataTest.java

Fix compileAndLoadKieJarMetadataAllResourcesPackagedJar -
The number of types produced and/or provided by PMML processing, based
on the test input data, is 22. This aligns with the number expected,
based on a visual analysis of the input data. Consequently, the "magic
number" is being changed from 35 to 22.

AF-1819 Fix KieMetadataTest

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/AssetsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/assets/AssetsScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreenTest.java

When an asset was updated, deleted, or created we used to refresh the list clearing everything, and showing a "Loading assets" message.
Now the asset list is refreshed in a silent way showing the updated assets without visible messages or delay because of network latency. 
The only time Loading assets message is shown is when assets are being loaded first time or when a search is being made.
@ederign @jhrcek @porcelli would you mind to review?

[AF-1820]: Improved asset list to remove refresh blink

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/impl/CommandManagerImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/impl/ReverseCommandTest.java

Hi @romartin, @manstis 
it is a fix for java 11 build, since CORBA is removed from Java 11: https://openjdk.java.net/jeps/320
@romartin, any ideas why we had it? Tests are passing with regular java.lang.Object as well.

JBPM-8236: Fix java 11 build

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricher.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/range/DataTypeConstraintRangeView.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/BaseDecisionTableEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGridTest.java

See https://issues.jboss.org/browse/DROOLS-3632
The issue was that the `ContextEntry` for the _default_ row does not have an `InformationItem` and hence the `Name` and `TypeRef` of the Decision Table's `OutputClause` could not be ascertained. After speaking to @etirelli he advised that in these scenarios the `Name` and `TypeRef` of the enclosing `Context`'s parent should be used.

DROOLS-3632: [DMN Designer] Context result row can not be a decision table

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/editors/types/RangeValue.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/editors/types/RangeValueTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/range/DataTypeConstraintRangeTest.java

DROOLS-3633: [DMN Designer] Data Types - Constraints - Range - Checkboxes for include start and end value must be enabled by default

DROOLS-3633: [DMN Designer] Data Types - Constraints - Range - Checkboxes for include start and end value must be enabled by default

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/impl/ShapeStateDefaultHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/impl/ShapeStateDefaultHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/shape/impl/ShapeStateAttributesFactory.java

See https://issues.jboss.org/browse/JBPM-7968
This PR restores the (correct) blue border for _selected_ nodes. 
Added both @romartin and @hasys as reviewers since this affects all Stunner editors.
I checked BPMN, CM and DMN. All appear OK to me!

JBPM-7968: Stunner - Node Selection Design

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/reflect/BackendDefinitionAdapter.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/BaseFooTestBean1.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/BaseFooTestBean2.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/FooTestBeanBaseGrandParent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/FooTestBeanBaseParent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/FooTestBeanNoParent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/definition/adapter/reflect/BackendDefinitionAdapterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/BaseDirectDiagramMarshaller.java

Fix errors on Marshalling tests. 
**Summary:**
TL;DR; 
The problem was at the` BackendDefinitionAdapter.getBaseType`. `UserTask` has changed its parent... now it is `BaseUserTask`, and before it was `BaseTask`, the adapter was just getting the first parent.
Details:
`BootstrapObjectBuilder.stencil` method was getting the Definition based on a given **oryxStencilId**, so sometimes it gets the `UserTask`, and the adapter was not returning the correct BaseType. If the return was any other Task, (BusinessRule, Script, None...) it worked... but this code is totally random. 
If you look at `BaseOryxIdMappings.getKey` this is the random part, it gets the map.entrySet from all the definition mapping and takes the first Definition that matches the **oryxStencilId**, randomly it was getting the …

JBPM-8234 fix failing Marshalling tests

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControls.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlsView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlsViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/CellEditorControlsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlImplTest.java

See https://issues.jboss.org/browse/DROOLS-3656
The issue was much the same as my previous PR.. when multiple DMN files are open each was getting its own `CellEditorControlsView` added to the HTML `body` which lead to Bootstrap binding popovers to the wrong element. This PR ensures all editors share a single instance attached to `body`.
Please note I could not replicate without first merging #2483 as I was unable to have multiple editors simultaneously open. With the referenced PR merged locally I could successfully replicate the issue - and tested my fix.

DROOLS-3656: [DMN Designer] Select logic type missing entries

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/pom.xml

Hi @romartin, @LuboTerifaj,
there is a fix for missing dependency for Java 11 support.
There are still more should be done to fix all Java 11 issues:
1. Fix LienzoRunner, see [JBPM-8029](https://issues.jboss.org/browse/JBPM-8029)
2. Update PowerMock (and mockito as well) framework (probably it will cause a lot of new issues and not only in Stunner project, but across all kiegroup repositories) or remove it from tests (it means some refactoring, mostly doing `static` methods not static.
@LuboTerifaj, there are some more backend test should be investigated, see below:
<details>
<summary>Click to expand</summary>
<pre>-------------------------------------------------------------------------------
Test set: org.kie.workbench.common.stunner.core.backend.definition.adapter.bind.BackendBindableDe …

JBPM-8030: Add dependency to jaxb.xml.bind

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/BPMNDiagramMarshallerBase.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/AssociationsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/BusinessRuleTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/EmailServiceTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/LogServiceTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/NoneTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/RestServiceTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/ScriptTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/ServiceTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/ServiceTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/Task.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/UserTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/WebServiceTaskTest.java

Hi @romartin, @wmedvede, @tiagodolphine, @LuboTerifaj,
there is a refactoring of new marshalling tests. It affects only Task tests because it is the most slow part of all tests and we handle different nodes in different way, so we need a lot of copy-pasting or global refactoring. I think global refactoring is a good way to go, but it's better to do it as part of Old marshaller tests removal task (or even after it).
**What changed**: Diagram is parsed only twice for the test class - once by the Old marshaller and once by the New marshaller. Before refactoring diagram was parsed for every single method separately, sometimes even two or three times.
Task tests **before** refactoring (on my local machine):
Task tests **after** refactoring (on my local machine):
All marshalling tests including …

 JBPM-7826 - Speedup new marshaller tests for Tasks

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorControlImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorControlImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java

See https://issues.jboss.org/browse/DROOLS-3706
Screenshot of change
- Text responds to updating Name/Expression type
- Back to link responds to change to Diagram properties (at the moment the back to link text is tied to the DRG and not a DRD.. as the editor does not support DRDs at the moment). 
- Best tested with `drools-wb-webapp`

DROOLS-3706: [DMN Designer] Boxed Expressions - Enhance component title

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-offprocess-classpath/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-offprocess-classpath/src/main/java/org/kie/workbench/common/services/backend/compiler/offprocess/generator/ClassPathMavenGenerator.java

When building `kie-wb-common` outside its root dir (using `mvn -pl`, `mvn -f`, or even using [kiegroup-all](https://github.com/tiagobento/kiegroup-all)), I was getting a `java.nio.file.NoSuchFileException`.
The fix was to supply the `${project.basedir}` POM built-in property so that the `ClassPathMavenGenerator#main` method can work only with relative dirs.

Fix relative path problems in kie-wb-common-compiler-offprocess-classpath

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/forms/conditions/parser/ParsingUtilsTest.java

Fix failing tests on JDK 11.
(cherry picked from commit 2fd1265950aad10e3c995cf29f5b8cdd575b00a0)

JBPM-8279: Stunner - Underscore is not legal name on JDK 11 (#2500)

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ImportConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ImportConverterTest.java

See https://issues.jboss.org/browse/DROOLS-3725
---
Before:
After:
---
The error was happening because the property `xmlns:drools` (from the `import` element) was being discarded (PS.: this property was added by a third party editor).
```xml
<semantic:import
namespace="http://www.treasuretech.com/definitions/789456123459789"
name="model-test"
treasure:fileId="123456789123456798"
treasure:fileName="karreiro/dmn-tests/model-test"
importType="http://www.omg.org/spec/DMN/20180521/MODEL/"
drools:modelName="model-test"
xmlns:drools="http://www.drools.org/kie/dmn/1.1"/>
```

DROOLS-3725: [DMN Designer] Included Models - Error when a file with included models is saved

---

kie-wb-common-forms/kie-wb-common-dynamic-forms/kie-wb-common-dynamic-forms-backend/pom.xml
kie-wb-common-forms/kie-wb-common-forms-commons/kie-wb-common-forms-common-rendering/kie-wb-common-forms-common-rendering-client/pom.xml
kie-wb-common-forms/kie-wb-common-forms-commons/kie-wb-common-forms-processing-engine/pom.xml
kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-fields/pom.xml
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-data-modeller-integration/kie-wb-common-forms-data-modeller-integration-backend/pom.xml

Missing dependencies for annotation and jaxb.

JBPM-8308: Add missing dependencies for JDK 11

---

kie-wb-common-ala/kie-wb-common-ala-distribution/pom.xml
kie-wb-common-ala/kie-wb-common-ala-services-api/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-distribution/pom.xml

added exclusion of duplicated class brought in by resteasy
upgraded to jboss-jaxrs-api_2.1_spec left over

BAPL-1148: upgraded to jboss-jaxrs-api_2.1_spec

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/AddInputClauseCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/AddOutputClauseCommandTest.java

For more details see this   -   https://issues.jboss.org/browse/DROOLS-3777  
I'm ignoring test which are failing on jdk 11.
@jomarko @manstis Hello, may I ask you for review? Thank you in advance!

DROOLS-3777 Ignore test failing on jdk 11

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/HealthCheckControllerBootstrap.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/KieServerEmbeddedControllerProducer.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/KieServerStandaloneControllerProducer.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/AbstractAutoControllerIT.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/AbstractControllerIT.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/EmbeddedControllerIT.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/StandaloneControllerIT.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/StandaloneControllerMultinodeIT.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/arquillian/DefaultLinuxKillProcessor.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/arquillian/ServerExtension.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/resources/arquillian.xml
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/navigation/template/ServerTemplatePresenter.java

fixes some problem during refreshing in the UI
added alive ping to check whether servers are alive
cherry picked from (#2285)
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1772

[JBPM-7974] kie-server not removed from the controller view if server is killed or crashes  (7.18.x)

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryView.less

Added string cut for Toolbar title to avoid breaking html layout due long names

AF-1875-Add string cut for breadcrumb Links and toolbar title

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommandTest.java

CanvasCommandUndoneEvent is firing from CanvasCommandManagerImpl for all subscribers and contains no context related info, as a result we have redu button active for all modeling workspaces. In RedoSessionCommand.onCommandUndoExecuted i added a check to be sure if this event belongs to this workspace. 
My suggestion is reduce it by adding uuid to this event. I am familiar with @Session annotation, maybe it сould reduce the scope but it seems to me that it won't. Any better ideas howto fix it?
@wmedvede @romartin

JBPM-8207: Stunner - Redo command is shared between windows

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/ExpressionGridCacheImpl.java

@jomarko Would you mind approving please.
`drools-wb-webapp` failed to run the DMN editor as Errai was not generating _Type Factory_ for it without the explicit constructor and CDI injection of `ExpressionGridCache` was failing.

Add explicit zero parameter constructor to make drools-wb-webapp work

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeActionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnection.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnectionTest.java

See https://issues.jboss.org/browse/DROOLS-3702
This fixes the issue reported by @danielzhe and the preview when authoring.
It improves on the `MagnetConnector.Builder.forTarget(..)` method to be less naive and considers target nodes above or below the source. The old implementation simply checked for left or right that was OK for BPMN as most diagrams run from left to right whereas DMN is top to bottom.
However please note the preview does not appear to honour the "auto" setting on the connection. This is not a regression caused by this PR but is in `master` too. I've included @romartin and @hasys on the review for BPMN.

DROOLS-3702: [Stunner] Arrows are incorrectly positioned when save-open diagram

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/AdHocSubprocess.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-api/src/main/java/org/kie/workbench/common/stunner/cm/definition/AdHocSubprocess.java

https://issues.jboss.org/browse/RHPAM-1892
Ad Hoc Subprocess Nodes supports End Nodes containment.

RHPAM-1892 - Ad Hoc Subprocess: Signal end node is not allowed

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorView.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/decision/DecisionNavigatorPresenterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreen.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/test/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/SessionDiagramEditorScreenTest.java

See: https://issues.jboss.org/browse/DROOLS-3897
---
---
Disabling _Decision Components component_ and _Included Models tab_.

DROOLS-3897: [DMN Designer] Included Models - Temporally disable Included Models

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/handlers/EditableHeaderGridWidgetEditCellMouseEventHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/handlers/EditableHeaderGridWidgetEditCellMouseEventHandlerTest.java

See https://issues.jboss.org/browse/DROOLS-3896
@jomarko this was not a regression after all but an existing bug.. please note you won't be able to test that entries in the `TextBox` are flushed to the UI when the `TextBox` looses the focus until the remainder of your DOM Factory PRs are complete and merged (as, at the moment, your change to `destroyResources()` means the text is not flushed).

DROOLS-3896: [DMN Designer] Editing a merged header cell positions editor at the wrong location

---

kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/AbstractDecoratedGridHeaderWidget.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/test/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/AbstractDecoratedGridHeaderWidgetColumnResizeTest.java

See https://issues.jboss.org/browse/DROOLS-3930
Unfortunately _lots_of formatting changes; but I'll call out the main changes below.

DROOLS-3930: Improve usability from Guided Rule Template - Can't resize column

---

kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/SessionPropertiesScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/screens/SessionTreeExplorerScreen.java

AppFormer correctly handles `WorkbenchActivity` implementations with no menus.
Stunner standalone showcase webapp was incorrectly providing an empty `@WorkbenchMenu` method (that should either not exist, or should invoke the `Consumer` with `null`). Since the affected screens do not have menus it was perfectly safe to simply remove the `@WorkbenchMenu` methods.

AF-1674: Role-based access to branches in the Workbench. Fix for Stunner standalone webapp screens

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml

Using custom tags causes errors on release builds because the version update script doesn't update these custom versions anymore.

Make kie-wb-common-library-spaces-screen module inherit version from its parent

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/actions/ProjectMainActionsViewImpl.html
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingPanel.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingPanelTest.java

https://issues.jboss.org/browse/DROOLS-3918
and
https://issues.jboss.org/browse/AF-1960
https://github.com/kiegroup/appformer/pull/695
https://github.com/kiegroup/kie-wb-common/pull/2630
https://github.com/kiegroup/drools-wb/pull/1135

DROOLS-3918 : The error reporting should contain information about the corresponding test scenario asset

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/included/modal/dropdown/DMNAssetsDropdown.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/AbstractKieAssetsDropdown.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/KieAssetsDropdown.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/KieAssetsDropdownView.html
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/KieAssetsDropdownView.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineKieAssetsDropdown.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineKieAssetsDropdownView.html
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineKieAssetsDropdownView.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineKieAssetsDropdownView.less
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/assets/dropdown/AbstractDropdownTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/assets/dropdown/AbstractKieAssetsDropdownTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/assets/dropdown/KieAssetsDropdownViewTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineKieAssetsDropdownTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/assets/dropdown/SubmarineSubmarineKieAssetsDropdownViewTest.java

@manstis @jomarko @karreiro 
This PR requires https://github.com/kiegroup/appformer/pull/696
I've slightly refactored original KieDropdown implementation.
My general point of view about abstract classes is
1) they are meant to be extended, so it should be possible to change the behavior, otherwise they are normal classes "masked"
2) to allow that, properties/methods must be readable/writable by child classes
3) only for very specific cases there must be an hidden/unchangeable inner state/behavior (but I do not see such case here)
For this specific one, my idea is 
1) it is GREAT to have one single elemental dropdown, to be used *everywhere* (I have at least one other case where I will use it)
2) following the above, the top-most parent must be absolutely independent of any specific …

[DROOLS-3993] Modified KieAssetsDropdown for better/easier reusability

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/util/DataEnumLoader.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/builder/util/DataEnumLoaderTest.java

https://issues.jboss.org/browse/DROOLS-3974
Without this the dropdown just shows the code that should fetch the enumeration, while the documentation states that the use of ' quotes should let you use the code in the way this PR enables.
The fix changes 
'Fact.field' : '(new org.company.DataHelper()).getList()'
to
'Fact.field[field]' : '(new org.company.DataHelper()).getList()'
This is the most simple way of getting this to work. I don't really want to touch the areas on the client side code since the unit test coverage is weak.
@jomarko @manstis I think you two are again the best to review. Thank you. Or of course happy to ping anyone else who might be able to review this.

DROOLS-3974 : Guided Decision Table is not getting updated

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java

See https://issues.jboss.org/browse/DROOLS-3994
**Tests**
Create a diagram
Add a `Decision` from the palette
Add another `Decision` from the first using the toolbox button
Save, close and re-open.
Create a diagram
Add a `Decision` from the palette
Add another `Decision` from the palette
Connect using the toolbox icon on the first `Decision`
Save, close and re-open.
Create a diagram
Add a `Decision` from the palette
Add another `Decision` from the palette
Connect using the toolbox icon on the first `Decision`
Re-position connector endpoints into the centre of each `Decision`
Save, close and re-open.

DROOLS-3994: [DMN Designer] Connectors to do align with Node boundaries

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/event/registration/RegisterChangedEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/UndoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/UndoSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/registry/impl/ClientCommandRegistry.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandlerTest.java

JIRA: https://issues.jboss.org/browse/JBPM-8378
Here i don't like the way i am providing the ClientSession to ClientCommandRegistry, but i can't Inject ClientSession because errai can't resolv the interface to type and i can't inject ManagedSession because of cyclic deps. ManagedSession belongs to kie-wb-common-stunner-client-common and depends on kie-wb-common-stunner-core-common.

 JBPM-8378: Undo command is shared between windows

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/resources/org/kie/workbench/common/dmn/DMNAPI.gwt.xml
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/editors/types/DMNValidationServiceImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/editors/types/TimeZoneServiceImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/api/included/legacy/DMNIncludeModelsClient.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/common/typed/time/picker/TimeZoneProvider.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumeration.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/range/DataTypeConstraintRange.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/validation/DataTypeNameFormatValidator.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/service/DMNClientServicesProxy.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/DMNClient.gwt.xml
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/api/included/legacy/DMNIncludeModelsClientTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumerationTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/range/DataTypeConstraintRangeTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/validation/DataTypeNameFormatValidatorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/service/DMNClientServicesProxyImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/service/DMNClientServicesProxyImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/service/DMNClientServicesProxyImpl.java

See https://issues.jboss.org/browse/DROOLS-4041
This PR introduces a single `DMNClientServicesProxy` interface to be used in the _client_ to access **all** _external_ services. There is a single implementation of the interface in `-project-client` that uses Errai's `Caller` interface to make RPCs to the server (although the implementation is currently duplicated in the webapp module). The plan being that the Submarine editor has a different implementation to handle the requirements on the client-side (or return sensible defaults without a RPC).
When this is merged I'll rebase DROOLS-3727 with this and make the applicable changes for Submarine.

DROOLS-4041: [DMN Designer] Submarine: Refactor service use to support pluggable implementation

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/main/java/org/kie/workbench/common/stunner/core/definition/service/DiagramMarshaller.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/main/java/org/kie/workbench/common/stunner/core/marshaller/MarshallingMessage.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/main/java/org/kie/workbench/common/stunner/core/marshaller/MarshallingRequest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/main/java/org/kie/workbench/common/stunner/core/marshaller/MarshallingResponse.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/main/resources/org/kie/workbench/common/stunner/core/StunnerBackendApi.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-backend-api/src/test/java/org/kie/workbench/common/stunner/core/definition/service/DiagramMarshallerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/main/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-backend-common/src/test/java/org/kie/workbench/common/stunner/core/backend/service/AbstractVFSDiagramServiceTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDiagramMarshallerTest.java

- API for Marshalling that contains a response with messages regarding the marshaling process. 
- A simple implementation that for now just return an error message (in case current marshallers throws an exception due to any unsupported element or whatever) or success with the expected result (Graph). 
@romartin 
@wmedvede 
@LuboTerifaj  @hasys

JBPM-8432 API for Marshalling with a response to include error/warning messages

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNEditorSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/DMNEditorSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/notification/CommandNotification.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/command/ClientRedoCommandHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/i18n/ClientTranslationMessages.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/registry/impl/ClientCommandRegistry.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/command/ClientRedoCommandHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/i18n/ClientTranslationMessagesTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/RedoSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/diagram/MetadataImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/i18n/CoreTranslationMessages.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/command/util/RedoCommandHandlerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/i18n/CoreTranslationMessagesTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-client/src/main/java/org/kie/workbench/common/stunner/cm/client/session/CaseManagementEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/README.md

Hey @tiagodolphine @Josephblt @wmedvede @treblereel @hasys @LuboTerifaj 
Fixed the issue you're also facing with, about running the project showcase inside IntelliJ :+1
**Some feedback**
Will give you some feedback about how I did it, if you're instered on, so next times you can also consider this "approach" for debugging this.
I understand we're all getting stuck, inside IntelliJ, when running the project showcase at this point:
`[INFO] 2019-05-21 03:19:31,809 [pool-4-thread-6] INFO  Reachability strategy set to Annotated`
So I just run in debug mode, and once getting into that point paused the debugging, then on the same IntelliJ debug console just navigated to the frame "`pool-4-thread-6`" (it can change on each execution) and noticed it was in some kinda infitie loop when trying to …

[Stunner] Fix a core dependency issue (which was causing the project showcase not running properly on IntelliJ)

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/main/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ToolboxImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/src/test/java/org/kie/workbench/common/stunner/lienzo/toolbox/items/impl/ToolboxImplTest.java

Hey @hasys 
Here is the fix for [JBPM-8449](https://issues.jboss.org/browse/JBPM-8449).
See also a video that shows the fixed version [here](https://issues.jboss.org/browse/JBPM-8449?focusedCommentId=13736908&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13736908)
Thanks!

JBPM-8449: [Stunner] Can't click node edit button when line is over top of it

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ExpressionEditorColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ExpressionEditorColumnTest.java

https://issues.jboss.org/browse/DROOLS-3976
The fix enables to edit the cells in Context, Function and Invocation by keyboard. Edit by mouse was possible even without this fix.
@manstis @Bonuseto may I ask you for a review?

DROOLS-3976: edit cell by enter in Context, Function and Invocation

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/NotificationsEditorFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/NotificationsEditorWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationWidgetViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/ReassignmentsEditorFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/ReassignmentsEditorWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/reassignmentsEditor/widget/ReassignmentWidgetViewImplTest.java

Powermockito causes InvocationTargetException on jdk11 so this PR replaces it where not needed.
@LuboTerifaj could you please have a look? This PR should fix some tests from [jdk11 jobs](https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/BxMS/job/RHPAM-master-nightly/job/certification/job/community-tests/job/blessed-community-tests-bcentral-stunner-jvmos-matrix/)

JBPM-8031: Replace powermockito where not needed

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/notification/NotificationsObserver.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/notification/ValidationExecutedNotification.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/notification/NotificationsObserverTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/screens/ProjectMessagesListener.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/screens/ProjectMessagesListenerTest.java

Now validation alerts that have been solved on Stunner don't appear anymore on the panel.
[RHPAM-958](https://issues.jboss.org/browse/RHPAM-958)
@romartin 
@LuboTerifaj

RHPAM-958 Error is visible in Alerts view even after it is fixed

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/common/typed/common/DurationHelper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/common/typed/day/time/DayTimeValueConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/common/typed/years/months/YearsMonthsValueConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/common/typed/common/DurationHelperTest.java

@manstis @jomarko I decided to use a simpler approach since using the FEELParser would demand too many changes.

DROOLS-4082: Cant use whitespaces in expression duration("P1Y")

---

kie-wb-common-screens/kie-wb-common-home/kie-wb-common-home-client/src/main/java/org/kie/workbench/common/screens/home/client/widgets/home/HomeView.less

- Added a css property that will allow the home screen background to "crop both left and right as the screen gets narrower" (As per the discussion with @ederign @bdellasc ).
- Related to PR https://github.com/kiegroup/kie-wb-distributions/pull/933

AF-1965 :Replace name logo images in masthead etc.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/shortcuts/DataTypeListShortcuts.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/shortcuts/DataTypeShortcuts.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/shortcuts/DataTypeListShortcutsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/shortcuts/DataTypeShortcutsTest.java

This PR fix the following issues, that causes the shortcuts stop working when you are editing and/or creating a new Data Type:
1. When you click on a DataType row, the selection was not changed, staying on the previous Data Type. With this PR, clicking on a row also select it.
2. The focus and selection for the DataType was lost after you selected a type from the drop down menu. With this PR, now the focus gets back to the selected DataType.
Notice the two examples bellow, one showing the old behavior and other showing the new:
**OLD BEHAVIOR**:
Click doesn't select the row (notice the "light darker blue"), so when you are editing a row that is not selected, the CTRL + S doesn't work. Also, notice that the selection is lost when you select atype in the drop down menu:
**NEW BEHAVIOR:** …

DROOLS-4093: [DMN Designer] Sometimes shortcuts does not work when editing DataType items

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/tree/TreeExplorer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/explorer/tree/TreeExplorerView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/explorer/tree/TreeExplorerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/explorer/tree/TreeExplorerViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphCanvasNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/command/MorphCanvasNodeCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/factory/impl/AbstractElementFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/MorphNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/TestingGraphInstanceBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/MorphNodeCommandTest.java

Hey @hasys 
Here is the fix for [JBPM-8246](https://issues.jboss.org/browse/JBPM-8246).
PS: Notice there is still some old TODO in the code that should nice to have, altghough IMO it's not urgent, so just created a new ticket for it too, see [JBPM-8524](https://issues.jboss.org/browse/JBPM-8524)
Thanks!

JBPM-8246: Stunner - non empty sub-process lose it's content after morph

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/AbstractValidatingTextBox.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBox.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/VariableNameTextBox.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBoxTest.java

Hey @hasys 
Here is the fix for this **BLOCKER** - [JBPM-8525](https://issues.jboss.org/browse/JBPM-8525)
PS: TBH I just applied same solution as in the `name` field in the process variables editor. I don't really like it, but at this point we don't have too much time for improving the code. So used same approach and also added concrete tests for it.
Thanks!

JBPM-8525: Stunner - less and greater signs in data-types breaks the process

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/AssociationDeclaration.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/InputAssignmentReader.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/AssociationDeclarationTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/InputAssignmentReaderTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/logtask.bpmn
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/serviceTasksJBPMDeginer.bpmn

Fix issue with service tasks marshaling containing a `null` body/value on the data assignments.
To test it can be generated any diagram **jBPM designer** with service tasks export the `bpmn` and import as a new asset on Stunner.
@wmedvede
@hasys 
@romartin

JBPM-8548 Stunner - Issue with ServiceTaks migrating from jBPM Designer to Stunner

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/BusinessKnowledgeModel.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/Decision.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/DecisionService.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/InputData.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/KnowledgeSource.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/v1_1/TextAnnotation.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dimensions/DecisionServiceRectangleDimensionsSet.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dimensions/GeneralRectangleDimensionsSet.java

See https://issues.jboss.org/browse/DROOLS-4124
This PR simply removes the maximum limitation and removes the dimension properties from the Properties Panel (for Decision Services). Other elements still have dimension properties on the Properties Panel however see this [comment](https://issues.jboss.org/browse/DROOLS-4124?focusedCommentId=13742697&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13742697)... depending on the response this PR could change a little!

DROOLS-4124: Decision Service can not be larger than 500 (width) x 200 (height)

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/BusinessKnowledgeModelConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/BusinessKnowledgeModelConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionUIModelMapper.java

See https://issues.jboss.org/browse/DROOLS-4165
This PR ensures the column widths of a `Function` within a `BKM` are written to and read from the XML file.

DROOLS-4165: [DMN Designer] BKM Function column width

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ExpressionEditorColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/supplementary/FunctionSupplementaryGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/supplementary/BaseFunctionSupplementaryGridTest.java

See https://issues.jboss.org/browse/DROOLS-4155
This PR makes the width of the _expression_ columns for Java and PMML kinds wider. This PR does not depend on #2683 however if merged on top of it you'll see the placeholders are no longer truncated.

DROOLS-4155: [DMN Designer] Placeholder doesn't fit a column.

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/BPMNDefinitionSet.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/BaseTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/GenericServiceTask.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/profile/BPMNRuleFlowProfile.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/GenericServiceTaskTest.java

Hey @hasys 
This commit disables the use of the recently included `Generic Service Task` element for Stunner BPMN editor.
See [RHPAM-2183](https://issues.jboss.org/browse/RHPAM-2183)
PS: I just commented out a few points to make the runtime and generated code skip this element during any processing. The idea is to just do it for the 7.23.x branch (targeting RHPAM 7.4 release), as we're actually fixing it on master for next community release.
Thanks!

[7.x] RHPAM-2183: Stunner - Generic Service Task should be temporary disabled

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/factory/AbstractDMNDiagramFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DefinitionsConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/QNamePropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DefinitionsConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/QNamePropertyConverterTest.java

There was 2 issues that was causing the error that this PR fixes:
1. The `xmlns` was duplicated, since `XStreamMarshaller` looks for the DMN URI in the namespaces. If he doesn't found, it adds it as default. Since the default `xmlns` in the file attached to the JIRA was not the default DMN URI, it causes duplicated `xmlns`.
2. After the step 1 applied, there was another issue with `typeref`.  In the provided file, the `namespace` was the same as `kie:xmlns`, but after the conversion of file from DMN 1.1 to 1.2, the `kie:xmlns` is updated. It leads to some references not being found, since the variables was declared in the default namespace that is not the same as `kie:xmlns` anymore. With this PR, if `kie:xmlns` is the same as the default `namespace`, the prefix `kie` is removed from …

DROOLS-4144: [DMN Designer] Imported model is broken after saving changes

---

kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/main/java/org/kie/workbench/common/screens/projecteditor/client/build/exec/impl/executors/redeploy/SnapshotRedeployExecutor.java
kie-wb-common-screens/kie-wb-common-project-editor/kie-wb-common-project-editor-client/src/test/java/org/kie/workbench/common/screens/projecteditor/client/build/exec/impl/executors/redeploy/SnapshotRedeployExecutorTest.java

@paulovmr @domhanak would you mind take a look?
https://github.com/kiegroup/kie-wb-common/pull/2681
https://github.com/kiegroup/droolsjbpm-integration/pull/1839

AF-2011: Redeploy does not abort running process instances when their process definition is deleted

---

kie-wb-common-forms/kie-wb-common-forms-core/kie-wb-common-forms-adf/kie-wb-common-forms-adf-processors-tests/pom.xml
kie-wb-common-forms/kie-wb-common-forms-integration-tests/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-maven-plugins-testing/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-offprocess-testing/pom.xml

enabled the maven-jar-plugin again because the disabling of it causes much more problems then the problem:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project appformer-js: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
This error has to solved ASAP.

revoked the disabling of maven-jar-plugin

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBoxTest.java

Hey @hasys 
Here is the (2nd) fix for [JBPM-8525](https://issues.jboss.org/browse/JBPM-8525). Now it does not allow the "-" symbols in the `data type` field, and also the validation is being done not just for process variables, also for other fields (see [comment](https://issues.jboss.org/browse/JBPM-8525?focusedCommentId=13745589&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13745589)).
Thanks!

JBPM-8525: Stunner - less and greater signs in datatypes breaks the process

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/ClassMethodInspector.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/util/BlackLists.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/ClassMethodInspectorTest.java

See https://issues.jboss.org/browse/AF-2080
(cherry picked from commit 85a22ef5fbb138694803aa1b101456c9e6999f26)

[7.23.x] AF-2080 (RHDM-988): The method defined in a parent data object class is not visible when editing guided decision table (#2719)

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/common/DMNMarshallerImportsHelper.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/common/DMNMarshallerImportsHelperImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/validation/DMNDomainValidator.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/common/DMNMarshallerImportsHelperImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/validation/DMNDomainValidatorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/editor/StandaloneToolbarStateHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/notifications/Notifications.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ClearToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/CopyToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/CutToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/DeleteSelectionToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToBpmnToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToJpgToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToPdfToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToPngToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ExportToSvgToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/PasteToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/PerformAutomaticLayoutToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/RedoToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/SaveToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/SwitchGridToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/UndoToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/toolbar/command/ValidateToolbarCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/validation/canvas/CanvasDiagramValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/validation/canvas/CanvasDiagramValidatorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/validation/impl/AbstractDiagramValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/validation/impl/DiagramValidatorTest.java

See https://issues.jboss.org/browse/DROOLS-3515
This change leverages the existing Stunner support for validation execution and reporting.
The changes to Stunner's commands are not as such part of the change, but whilst looking into how to re-use Stunner's support I found that the commands needed to have `@Any` injected otherwise subsequent lookup of specific commands for different domains (BPMN, DMN, CM) was failing... if/when different domains need to provide different implementations.

DROOLS-3515: [DMN Designer] Validation: Validate button should compile the DMN file and report issues

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreen.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingScreenTest.java

https://issues.jboss.org/browse/DROOLS-3917
@kkufova @danielezonca @gitgabrio Here you are.

DROOLS-3917 : The 'run all' panel should automatically close after leaving the project's library

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBoxTest.java

Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/2703 into `7.23.x` branch (targeting release `7.4.1`)
See [RHPAM-2193](https://issues.jboss.org/browse/RHPAM-2193)
Thanks!

[7.4.1] RHPAM-2193: Stunner - less and greater signs in datatypes breaks the process

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/src/spaces-screen/index.tsx

The event that refreshes SpacesView when a Repository is removed was missing.
IMPORTANT: Refresh Browser cache when testing this because it needs a fresh spaces-bundle.js, if not you will not be able to see changes.  A Jira to force refresh will be created.
@paulovmr @ederign @tomasdavidorg

[AF-2065]: Added repository removed event to SpacesScreen observer

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

Adding `uberfire-preference-client-backend` dependency, which is introduced by: https://github.com/kiegroup/appformer/pull/724
MERGE WITH https://github.com/kiegroup/appformer/pull/724

AF-1987: Adding uberfire-preference-client-backend dep

---

kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieEditor.java

The issue was caused when two users were trying to delete the same asset at same time (with the delete popup opened). When first user finally deletes the asset the second user gets the concurrent delete notification, whatever option he chooses (cancel or ignore) on that popup, the delete popup will still be opened, so he will be able click on the delete button, getting that error.
To prevent that situation, we'll be hiding the delete popup if there's a concurrent deletion.
@tomasdavidorg @adrielparedes @ederign Could you please take a look?
https://github.com/kiegroup/appformer/pull/731
https://github.com/kiegroup/kie-wb-common/pull/2740

AF-2053: Dialog remains open after asset is deleted at the same time

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryServiceImpl.java

@paulovmr just a more user-friendly message. The old one was showing the whole stack trace.
New error:
[INFO] 2019-07-22 18:14:45,105 [default task-1] ERROR Error while searching all users: org.uberfire.ext.security.management.api.exception.NoImplementationAvailableException

[AF-2117] Get all users throw an exception when there is no implementation found

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java

See https://issues.jboss.org/browse/DROOLS-4251
This PR adds support for different editors to choose what to do in the event of validation violations... BPMN/CM will prevent saving in the event of ERRORs... DMN no longer prevents saving in the event of ERRORs.

DROOLS-4251: [DMN Designer] User can not save diagram with validation errors

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationView.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationView.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/HTMLDownloadHelper.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationViewTest.java

As discussed in e-mail, this option was changed for now to "Download HTML", since the approach that we are using to generate .doc have some issues with MS Word.

DROOLS-4317: [DMN Designer] Documentation - Add the "Download .doc file" button to the documentation tab

---

kie-wb-common-stunner/README.md
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/Scripts.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenterTest.java

@romartin Can you review this PR, it is for the FEEL expression changes and the readme changes

JBPM-8666: Stunner - Missing the ability to to specify the FEEL expressions

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/ReusableSubprocessTaskExecutionSet.java

@romartin can you review this PR? Changed type of control so that it allows for a New.. option, search for a previous value and ability to unset a value. Control handled those cases automatically, also please advise about unit tests as I did not find a way to test the control, I will keep looking

JBPM 8622: Stunner - missing freetext called element (e.g. unknown or # {...} for Reusable sub-process	

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/LibraryInfo.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryAssetUpdateNotifier.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryServiceImpl.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/PopulatedLibraryScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/PopulatedLibraryView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/common/TileView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/common/TileWidget.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/library/AddProjectButtonPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/PopulatedLibraryScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/LibraryPlacesTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/widgets/common/TileWidgetTest.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/main/java/org/kie/workbench/screens/workbench/backend/impl/DefaultApplicationScopedProducer.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/main/java/org/kie/workbench/screens/workbench/backend/impl/DefaultBatchIndexListener.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/test/java/org/kie/workbench/screens/workbench/backend/impl/DefaultBatchIndexListenerTest.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-api/src/main/java/org/kie/workbench/common/services/refactoring/model/index/events/BaseIndexingEvent.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-api/src/main/java/org/kie/workbench/common/services/refactoring/model/index/events/IndexingFinishedEvent.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-api/src/main/java/org/kie/workbench/common/services/refactoring/model/index/events/IndexingStartedEvent.java

- Added DefaultBatchIndexListener to get notifications when a project indexing has started or finished
- Improved PopulatedLibraryScreen by minimizing its backend calls and keeping its state on client. The state changes are handled by system events.
- Made the TileWidgets asset count load / refresh asynchronous.
- Removed unnecessary screen refresh on Library when importing/adding new project
- Solved context inconsistency when moving from a project to library
https://github.com/kiegroup/appformer/pull/755
https://github.com/kiegroup/kie-wb-common/pull/2794

AF-2116: Verify Async load of Projects and Spaces Cards

---

kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/main/java/org/kie/workbench/common/screens/defaulteditor/client/editor/NewFileUploader.java
kie-wb-common-screens/kie-wb-common-default-editor/kie-wb-common-default-editor-client/src/test/java/org/kie/workbench/common/screens/defaulteditor/client/editor/NewFileUploaderTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/ClusterLibraryObserver.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/delete/DeleteOrganizationalUnitPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/util/LibraryPlaces.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/organizationalunit/delete/DeleteOrganizationalUnitPopUpPresenterTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/util/LibraryPlacesTest.java

* https://github.com/kiegroup/appformer/pull/764
* https://github.com/kiegroup/kie-wb-common/pull/2806
AF-2069: After space is deleted other users are not redirected to the spaces view on Openshift [CAT1]
AF-2052: No error message when assets are imported on the same pod (OpenShift)[Cat1]

HA improvements

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/DataTypeConstraint.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/DataTypeConstraintTest.java

See https://issues.jboss.org/browse/DROOLS-4409
The `DataTypeListItem` initialization was slow due to the `DataTypeConstraint` initialization.
Now, the `DataTypeConstraint` lazily instantiated. The `DataTypeListItem` instantiation performance was enhanced from ~446.7ms to ~7.9ms.
Before:
After:

DROOLS-4409: [DMN Designer] Data Type Structure update is slow

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/InputClause.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/InputClauseLiteralExpression.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/InputClauseUnaryTests.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClause.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClauseLiteralExpression.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClauseUnaryTests.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/TextAnnotation.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/dataproviders/ConstraintTypeDataProvider.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/resources/org/kie/workbench/common/dmn/api/resources/i18n/DMNAPIConstants.properties

See https://issues.jboss.org/browse/DROOLS-4450
Before:
After:
The rename of the `org.kie.workbench.common.dmn.api.1_1` package (https://github.com/kiegroup/kie-wb-common/pull/2787) caused this issue. Now the labels are updated, and the issue is fixed.

DROOLS-4450: [DMN Designer] DMN Graph - Tooltips are not showing the text properly

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenterTest.java

Now if any problem happens when trying to resolve project just after creation, the project will be created normally, the popup will be closed and the success message will appear, the only thing that might happen is the project not being automatically opened.

AF-2064: Unexpected error is displayed after project is created on OpenShift [Cat1]

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricher.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/BaseDecisionTableEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGridTest.java

This PR is a cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/2860 to `7.26.x`.
---
See https://issues.jboss.org/browse/DROOLS-4496
Before:
After:

[7.26.x] RHDM-1076 / DROOLS-4496: Empty Structure causes DMN editor to crash

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerTest.java

I added some comments in my changes because `DMNMarshaller` already have those kind of comments, but I don't know if it is really required.  I think it may be useful to help people from the future to understand why we are removing elements that doesn't have shape.

DROOLS-4478: [DMN Designer] Decision Service - Models from other vendors are being imported with extra decision services

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/importrepository/ImportRepositoryPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/importrepository/ImportRepositoryPopUpPresenterTest.java

JIRA task: [AF-2213](https://issues.jboss.org/browse/AF-2213)
If the URL has a leading or trailing space for importing a git project, the import fails.
Thus, trimming the URL in order to automatically handle this case for the user.
@paulovmr

[AF-2213] Trimming the URL when importing a project

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/package.json
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock

On this PR:
- Upgrade `ts-jest` package version
- Make it possible to debug in-browser using inline-source-maps.
- Add script on `package.json` to make live-reloading possible with GWT WebApps (e.g. `drools-wb-webapp`)
To build with source-maps:
```bash
mvn clean install -Psourcemaps
```
To live-reload, go to `kie-wb-common/kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen` and run:
```bash
npx watch 'yarn run live-reload-on ~/redhat/kiegroup-all/drools-wb/drools-wb-webapp' ./src
```
> **_NOTE 1_: Replace the location of the targeted webapp.**
> _NOTE 2_: The command used on the `live-reload-on` script already builds with source-maps
This will listen for changes on the AppFormer.js module. After the module builds, go to the browser and refresh the page. …

AF-2104 / AF-2106: AppFormer.js improvements

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java

Due to different line endings across platforms, some tests were failing when executed in Windows. 
Since the line ending was inside a string, probably due to copy pasting it, GIT was not able to pick this up, causing the failed tests. This fixes this issue.

Fix for failing tests in Windows

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/entrypoint/GenericErrorPopup.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/error/DefaultWorkbenchErrorCallback.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.java
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants.properties
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/test/java/org/kie/workbench/common/workbench/client/error/DefaultWorkbenchErrorCallbackTest.java

**[AF-2216](https://issues.jboss.org/browse/AF-2216) Generic Error Pop Up when server is shutdown**
**Issue:**
A Generic Error Pop Up is show when server is shutdown
**Solution:**
Show an appropriated pop up to user when server is shutdown
**Edge Cases:**
* on HA environments
* when server is shutdown in the middle of some operation that shows Busy Pop Up (for example, when creating a new Project). In this case, Busy Pop Up is never closed and the application hangs
**Notes:**
* tested on HA environment and didn't find any issues
* created a new pop up "*Could not connect to server. This very likely means a network problem. Do you want to reload the application?*" similar to an existing pop up that is shown when session timeouts "*Invalid response received from the server. This very likely …

[AF-2216] Generic Error Pop Up when server is shutdown

---

pom.xml

this is dependent PR for: 
* kiegroup/droolsjbpm-build-bootstrap#1055
* https://github.com/kiegroup/appformer/pull/806

managing java validation-api for 1.0.0

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ActivityPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ActivityPropertyWriterTest.java

Hey @hasys 
See [JBPM-8680](https://issues.jboss.org/browse/JBPM-8680)
PS: Some actions to take after this gets merged:
* Include this fix in the kogito bpmn client side marshallers ( CC @tiagodolphine )
* Include this fix in the RHPAM 7.5.1 branch ( see [RHPAM-2412](https://issues.jboss.org/browse/RHPAM-2412) )
Thanks!

JBPM-8680: Stunner - Process with Reusable sub-process print errors to the server log.

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/shapes/bpmn-shapes.css

Hey @hasys 
See [JBPM-8794](https://issues.jboss.org/browse/JBPM-8794)
PS: Once merged, will also include this fix into the RHPAM 7.5.1 branch ( see [RHPAM-2413](https://issues.jboss.org/browse/RHPAM-2413) )
Thanks!

JBPM-8794: Stunner - some end events have incorrect icons.

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-common/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml

@manstis @tiagodolphine @rsynek @mareknovotny 
THis PR should disable SONAR check on kie-wb-common-dmn-webapp-common and kie-wb-common-dmn-webapp-standalone

Drools 3727 Disabling sonar

---

kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreen.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreenView.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreenViewImpl.html
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreenViewImpl.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreenTest.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/panel/AnalysisReportScreenViewImplTest.java

This PR is dependent on the #2909, if we decide merging, I will rebase once #2909 is merged.
This PR introduces "enhancement" of not showing "Analysis Complete" indicator for cases when verifier is in illegal state. For more details see the screenshots.
@manstis @Rikkola @karreiro @danielzhe what do you think?

DROOLS-4545: Do not show Analysis Complete for Illegal Verifier State

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRefTest.java

https://issues.jboss.org/browse/RHPAM-2360
Signal now supports mixed expressions (static and dynamic).

RHPAM-2360 - Signal name cannot be dynamic

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/shape/view/handler/ServiceTaskShapeViewHandler.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/shape/view/handler/ServiceTaskShapeViewHandlerTest.java

https://issues.jboss.org/browse/JBPM-8690
Problem was happening because of an uninitialized Lienzo shape.

JBPM-8690 - cut/paste of Service task shows exception

---

kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/Receiver.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/VerifierWebWorkerConnectionImpl.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/reporting/ExplanationProvider.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/resources/i18n/AnalysisConstants.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/resources/i18n/AnalysisConstants.properties
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/AnalysisReporterTest.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/ReceiverTest.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/analysis/VerifierWebWorkerConnectionImplTest.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/panel/IssuePresenterTest.java

https://issues.jboss.org/browse/DROOLS-4545
https://github.com/kiegroup/drools/pull/2592
https://github.com/kiegroup/kie-wb-common/pull/2952
https://github.com/kiegroup/drools-wb/pull/1244
* DROOLS-4545 : GDST V&V: Clean up situations where the webworker fails
* DROOLS-4545 : GDST V&V: Clean up situations where the webworker fails
- Improve reporting when V&V fails
* DROOLS-4545: Increase coverage
(cherry picked from commit 841c768a68dd6f3c946dafe85c7ddbd9a26664b8)

[7.26.x] DROOLS-4545 : GDST V&V: Clean up situations where the webworker fails

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyPopoverViewImpl.html

See https://issues.jboss.org/browse/DROOLS-4599

DROOLS-4599: [DMN Designer] Decision Tables: Hit Policy select drop-down remains visible if popover closed

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/importrepository/ImportRepositoryPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/importrepository/ImportRepositoryPopUpPresenterTest.java

JIRA task: [AF-2213](https://issues.jboss.org/browse/AF-2213)
If the URL has a leading or trailing space for importing a git project, the import fails.
Thus, trimming the URL in order to automatically handle this case for the user.
@paulovmr

[7.5.1] [AF-2213] Trimming the URL when importing a project

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/ClipboardControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/EdgeClipboard.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/EdgeClipboardTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/clipboard/LocalClipboardControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CopySelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/PasteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/clipboard/LocalClipboardControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/CopySelectionSessionCommandTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/PasteSelectionSessionCommandTest.java

Hi @hasys can you check this PR? Basically it fixes the issue about Sequence flow dissapearing on cut/paste, also it now fixes the scenario when you copy something, then delete the original and then paste. before it did  not paste the sequence flows as well.

JBPM-7502 : Stunner - Sequence flow disappear after some cut/paste actions

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/shapes/bpmn-shapes.css

Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/2926 into `7.26.x` branch.
See [RHPAM-2413](https://issues.jboss.org/browse/RHPAM-2413)
Thanks!

RHPAM-2413: Stunner - some end events have incorrect icons.

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRefTest.java

* RHPAM-2360 - Signal name cannot be dynamic
Signal now supports mixed expressions in the following formats:
staticExpression-#{(dynamicExpression)}
staticExpression-#{(dynamicExpression.dynamicExpression2)}
staticExpression-#{(dynamicExpression.dynamicExpression2(dynamicExpression3)}
staticExpression-#{(dynamicExpression.dynamicExpression2(dynamicExpression3.dynamicExpresion4)}
staticExpression-staticExpression
Improved help and invalid chars messages.
Single letter in dynamic variables is supported.

[7.26.x] RHPAM-2360 - Signal name cannot be dynamic

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsView.java

The current page is not resetting when the user searches by term. It can cause an error if the page does not exist.
You can find the steps to reproduce this issue at JBPM-8825.

JBPM-8825: Resets current page when user searches by term.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/CanBeClosedByKeyboard.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/shortcuts/DataTypeShortcuts.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlsViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/BootstrapSelectDropDownMonitorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/container/CellEditorControlsViewImplTest.java

This PR also prevents that the TAB and SHIFT + TAB to exit from the pop-up, as discussed in the scrum meeting.
This PR also fixes this error, that I've found during the debug:

DROOLS-3652: DMN popover - Enter to apply

---

pom.xml

https://issues.jboss.org/browse/DROOLS-4563
Parent PR:
- kiegroup/droolsjbpm-build-bootstrap#1075
Dependent PRs:
-    kiegroup/appformer#814
-    kiegroup/kie-wb-common#2934
-    kiegroup/drools-wb#1238

DROOLS-4563: managing validation-api for GWT based code to 1.0.0.GA

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/resources/org/kie/workbench/common/workbench/client/resources/i18n/DefaultWorkbenchConstants_es.properties

Now Zanata is decommissioned, looking for a temporal way to update translations. Starting from Spanish as it is my native language.
I was not sure about lines like:
so I prefer to keep it. @manstis  Let me know if they don't make sense, I can rework and remove it.

Updating Spanish translation

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumeration.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumerationTest.java

See https://issues.jboss.org/browse/KOGITO-526

KOGITO-526: [DMN Designer] Constraint Enumeration widget overlaps when re-opened 

---

kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/resources/css/StylesCss.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/BaseViewImpl.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/BaseViewPresenter.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/business/BusinessViewWidget.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/business/BusinessViewWidget.ui.xml
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/loading/BusyIndicator.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/loading/BusyIndicator.ui.xml
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/tagSelector/TagSelectorViewImpl.ui.xml
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/technical/TechnicalViewWidget.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/java/org/kie/workbench/common/screens/explorer/client/widgets/technical/TechnicalViewWidget.ui.xml
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/main/resources/org/kie/workbench/common/screens/explorer/client/resources/css/Styles.css
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/test/java/org/kie/workbench/common/screens/explorer/client/widgets/BaseViewPresenterUpdateTest.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/test/java/org/kie/workbench/common/screens/explorer/client/widgets/business/BusinessViewWidgetTest.java
kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-client/src/test/java/org/kie/workbench/common/screens/explorer/client/widgets/technical/TechnicalViewWidgetTest.java

Task: [AF-2324](https://issues.jboss.org/browse/AF-2324)
As requested, only the project explorer will be blocked while it is loading, not the entire workbench.
Currently, users must wait until the loading finishes to continue using the editor when the project explorer is opened. Here's a demo showing this behavior:
After this PR, users can interact with the editor while the project explorer is being loaded.
Here's a demo showing this behavior:
One downside is that users might notice a UI hang while the project explorer is being loaded.
This can be seen when the "select/unselect" flow stops for a while.
For more details, check [RHPAM-2359](https://issues.jboss.org/browse/RHPAM-2359).

[AF-2324] Blocking only the project explorer while it is loading

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreen.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/resources/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.properties
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/LibraryScreenTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/src/spaces-screen/index.tsx

When userA changes space contributors and and userB is on Spaces view or in Projects view (inside a space) the list of spaces is refreshed. And in case User permissions for that space where 
removed the user is redirected to Spaces view and a warning notification is sent.
@ederign @jakubschwan @paulovmr

[AF-2158]: Added observers to refresh spaces when contributors are modified

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/ProcessesDataService.java

@hasys @romartin Can you review this PR?
The problem was that CaseCalledElement and CalledElement depended on ProcessesDataService instance which was defined as an ApplicationScoped singleton, so CaseCalled element when setting up the query and named changed the one that CalledElement depended on

JBPM-8875 : Stunner - Re-usable subprocess doesn't show options for Called Element properties (DROOLS-3727 merge)

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/query/BPMNProcessIdsResponseBuilder.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/project/backend/query/AbstractFindIdsQuery.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/query/BPMNProcessIdsResponseBuilder.java

https://issues.jboss.org/browse/JBPM-8828
The error happened because of an untreated exception. still happens, but
now it is being logged and handled in a better way. This way it does not
disrupt any editor functionality.

JBPM-8828 - After deleting some Space, the re-usable activities cannot be configured properly

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/NameAndDataTypePopoverViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieEditor.java

See https://issues.jboss.org/browse/DROOLS-3677
This PR also fixes an issue navigating to the Data Types tab on a "fresh" diagram where the "Name and Data-Type" popover had not been previously displayed. The `DataTypePageTabActiveEvent` event (raised when clicking on the _manage_ link) was being handled in the _view_ and led to a NPE if it had not been bound to a _presenter_. I've moved handling to the _presenter_.

DROOLS-3677: [DMN Designer] Change tabs order

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/project/backend/query/AbstractFindIdsQuery.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/query/BPMNProcessIdsResponseBuilder.java

https://issues.jboss.org/browse/JBPM-8828
The error happened because of an untreated exception. still happens, but
now it is being logged and handled in a better way. This way it does not
disrupt any editor functionality.

[7.30.x] JBPM-8828 - After deleting some Space, the re-usable activities cannot be configured properly

---

kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/admin/DefaultAdminPageHelper.java

Added command link to Admin breadcrumb
Test for related method already implemented in uppformer 
https://github.com/kiegroup/appformer/blob/master/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbsTest.java#L287

RHPAM-1560 Preferences breadcrumbs are not links

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/assembly/assembly.xml
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/AbstractControllerIT.java

maven resolver skinwrap does not resolve offline transtive dependencies
so if we are depending from a transitive dependency that it has not been
downloaded previously it would fail. Maven build can resolve those through
assembly descriptor file.

[JBPM-8884] integration test maven resolver

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/DMNExternalLinksToExtensionElements.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/utils/WrapperUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-marshaller/src/main/resources/KIE.xsd

See https://issues.jboss.org/browse/KOGITO-674
`JSITAttachment` needed wrapping for Jsonix to determine it's _type_. I also made a slight change to the `KIE.xsd` as `TAttachment` generated by JAXB had a redundant _value_ property too.

KOGITO-674: [DMN Designer] Not able to save file with external link

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-marshaller/src/main/resources/org/kie/workbench/common/dmn/webapp/kogito/marshaller/js/MainJs.js

This is in preparation for my ongoing work for https://issues.jboss.org/browse/KOGITO-406
When running `GwtTestCase` Unit Tests for the client-side marshaller I get JS compilation issues in `MainJS.js` at runtime when the JS are deployed to `com.gargoylesoftware.htmlunit.WebClient` that is the headless browser engine used for tests. The failures relate to use of `const` (presumably the `WebClient` does not support the JavaScript version introducing `const`). Use of `var` works fine.
I also added missing semi-colons (as IDEA keeps highlighting the file saying they're missing - although this is not true with JavaScript as their use is optional).

Fix JavaScript for use in GWTTestCase

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorView.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java

See https://issues.redhat.com/browse/KOGITO-460
This JIRA/PR now simply removes the "Imports" tab from _kogito_ editors. It also removes the "Decision Components" from the "Decision Navigator" as that shows imported types.

KOGITO-460: [DMN Designer] Remove the ability to add imported models

---

kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/pom.xml
kie-wb-common-widgets/kie-wb-metadata-widget/pom.xml

During https://github.com/kiegroup/kie-wb-common/pull/2784 review these unused dependencies were found.

DROOLS-3957: Remove unused dependencies

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/event/signal/SignalRefTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/comboBoxEditor/ComboBoxWidgetViewImpl.java

JIRA: https://issues.jboss.org/browse/JBPM-8450
this fix might affect other dropdowns in the stunner, i have checked it and i think it's ok, but it needs to be double checked by QE.

JBPM-8450 Stunner - Relax constraint on signal name

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/pom.xml

During RHPAM-2319 review unused dependencies were found. This PR removes few of them as a continuos effort to eliminate them.

RHPAM-2319: Remove unused dependencies

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/GenericServiceTaskPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/GenericServiceTaskPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/GenericServiceTaskPropertyReaderTest.java

Hi @hasys @romartin this is the PR for the change, I moved several folders, wanted to trigger builds to see if any errors. I am waiting for feedback from Maciej, Kris to see if my implementation of using the first Input/Output parameters data type as InMessageType/OutMessageType respectevely

KOGITO-418 : Missing structureref type for service task in VSCode BPMN Editor

---

kie-wb-common-ala/kie-wb-common-ala-build-maven/pom.xml
kie-wb-common-ala/kie-wb-common-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/gwt/GWTCodeServerPortLeaserImpl.java

parent PR is kiegroup/droolsjbpm-build-bootstrap/pull/1102

AF-2333: removing dependency mina-core as only one class is used

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/ContextEntry.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ContextEntryPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ExpressionPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ContextEntryPropertyConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/ExpressionPropertyConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/ContextEntryPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/DecisionConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/ExpressionPropertyConverter.java

See https://issues.jboss.org/browse/DROOLS-4724
Unit Test for kogito marshaller will be in https://issues.jboss.org/browse/KOGITO-406
Unit Test for existing backend marshalling is included in this PR.
I've manually tested (creating, saving and re-opening) with:-
- `-webapp-standalone` (server side marshalling)
- `-webapp-kogito-testing` (client side marshalling)
- Business Central (server side marshalling)

DROOLS-4724: [DMN Designer] Do not default to a LiteralExpression when no expression is defined

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/event/keyboard/KeyboardEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/BaseSessionCommandKeyboardTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommandTest.java

Hi @hasys @romartin can you check this PR? Backspace is now enabled for Mac/Linux/Windows

KOGITO-743 : Delete button on Mac keyboard does not work

---

kie-wb-common-ala/kie-wb-common-ala-openshift/kie-wb-common-ala-openshift-provider/src/main/java/org/guvnor/ala/openshift/config/OpenShiftProperty.java

Followed by the original PR for [AF-2058] Provide alternative implementation of uberfire-nio2-impls b…acked by OCP/K8S
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

[AF-2058] Fixing the OpenShift client API compatibility issue after upgraded io.fabric8 kubernetes client to 4.6.0

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/resources/org/kie/workbench/common/dmn/webapp/kogito/common/js/FormatterJs.js
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-marshaller/src/main/resources/org/kie/workbench/common/dmn/webapp/kogito/marshaller/js/MainJs.js
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/.gitignore
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/webapp/index.html

See https://issues.redhat.com/browse/KOGITO-616
@tiagobento I'm up for suggestions how we can avoid the duplication when running the DMN kogito editor in the `kogito-tooling` wrapper.. Is there anyway I can check if [your](https://github.com/kiegroup/kogito-tooling/blob/master/packages/kie-bc-editors/src/DefaultXmlFormatter.ts) `cachedXsltProcessor` is available/defined from JavaScript and re-use it?

KOGITO-616: DMN Tooling produce single line source

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/resources/org/kie/workbench/common/dmn/showcase/DMNKogitoRuntimeWebapp.gwt.xml

See https://issues.redhat.com/browse/KOGITO-780..
Basically I removed the `draftCompile` flag and a duplicate `logLevel` entry.

KOGITO-780: [DMN Designer] Ensure -runtime WAR is created with 'production' parameters

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/DMNClientEntryPoint.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionColumn.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/codecompletion/MonacoFEELInitializer.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/codecompletion/MonacoPropertiesFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/BaseExpressionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/AutocompleteTextAreaDOMElementFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorDOMElement.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionContainerGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/BaseLiteralExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionColumnTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/codecompletion/MonacoFEELInitializerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/codecompletion/MonacoPropertiesFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/AutocompleteTextAreaDOMElementFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorDOMElementTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/columns/factory/dom/MonacoEditorWidgetTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java

See:
- [DROOLS-4689](https://issues.jboss.org/browse/DROOLS-4689): [DMN Designer] Code Completion - Setup Monaco (loader)
- [DROOLS-4690](https://issues.jboss.org/browse/DROOLS-4690): [DMN Designer] Code Completion - Add Monaco support for 'TextAreaSingletonDOMElementFactory'
- [DROOLS-4691](https://issues.jboss.org/browse/DROOLS-4691): [DMN Designer] Code Completion - Enable code completion for only Literal Expressions
- [DROOLS-4692](https://issues.jboss.org/browse/DROOLS-4692): [DMN Designer] Code Completion - UI adjusts for Monaco component into DMN Boxed Expression component
---
---
- https://github.com/kiegroup/appformer/pull/836
- https://github.com/kiegroup/kie-wb-common/pull/3000

DROOLS-4689/DROOLS-4690/DROOLS-4691/DROOLS-4692: [DMN Designer] Code Completion - Enable code completion for Literal Expressions

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeList.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListViewTest.java

See https://issues.redhat.com/browse/KOGITO-599
The _kogito_ editor no longer has an "Import" button on the "Data Types" tab.

KOGITO-599: [DMN Designer] BC DOs as DMN DTs - Hide import button on Kogito

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/editors/types/DataObject.java
kie-wb-common-dmn/kie-wb-common-dmn-api/src/test/java/org/kie/workbench/common/dmn/api/editors/types/DataObjectTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModal.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModalView.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModalView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModalView.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/treelist/TreeList.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/imported/treelist/TreeListItem.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeList.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModalTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/imported/ImportDataObjectModalViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/imported/treelist/TreeListItemTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/imported/treelist/TreeListTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListViewTest.java

If you want to simplify the tests, you can change the class [MockDataObjectsServiceImpl](https://github.com/kiegroup/kie-wb-common/blob/62c0b90027441bdb0dbb3171fa796464e8215d92/kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/src/main/java/org/kie/workbench/common/dmn/showcase/backend/workarounds/MockDataObjectsServiceImpl.java) to return some DataObjects during the review.
For example:
```
DataObject do1 = new DataObject("something.MyType");
DataObject do2 = new DataObject("something.MyOtherType");
DataObject do3 = new DataObject("something.Abc");
return Arrays.asList(do1, do2, do3);
```

DROOLS-4696: [DMN Designer] BC DOs as DMN DTs - Show a warning message into the import dialog

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/general/BaseNavigateCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/NavigateToDRGEditorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/general/NavigateToExpressionEditorCommandTest.java

See https://issues.redhat.com/browse/KOGITO-528
@romartin @jomarko At the moment there is a slight delay (250ms) before the zoom control hides (due to use of a timer in `ZoomLevelSelectorPresenter`). @romartin Was this timer requested or did you use it to make the zoom control _prettier_? I wonder whether it might be worth me removing the delay in this PR (we don't have a delay _showing_ the control). @romartin @jomarko WDYT?

KOGITO-528: [DMN Designer] Zoom control should be hidden in grid view

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-backend/src/main/java/org/kie/workbench/common/stunner/project/backend/service/ProjectValidationServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-backend/src/test/java/org/kie/workbench/common/stunner/project/backend/service/ProjectValidationServiceImplTest.java

See https://issues.redhat.com/browse/DROOLS-4807
@hasys @romartin Please see the comment [here](https://issues.redhat.com/browse/DROOLS-4807?focusedCommentId=13823269&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13823269) suggesting the change in this PR should apply to BPMN in addition to DMN.

DROOLS-4807: [DMN Designer] Do not group V&V messages by UUID

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/expressions/types/function/AddParameterCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGrid.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/HasParametersControl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/FunctionGridTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverViewImplTest.java

See https://issues.redhat.com/browse/DROOLS-4907
This PR also fixes another issue I found when adding a parameter, then undoing the addition and redoing it.. on `master` the redo gives the parameter a new name and not the original.

DROOLS-4970: DMN FunctionDefinition parameter not trimmed by editor

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-kogito/kie-wb-common-kogito-client/src/main/java/org/kie/workbench/common/kogito/client/editor/BaseKogitoEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/README.md
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/editor/BPMNStandaloneDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/editor/BPMNStandaloneDiagramWrapper.java

Update Kogito editors so they can accept the path parameter in `setContent` method.
Also pass the content path when calling `setContent`.
https://github.com/kiegroup/kogito-tooling/pull/47
https://github.com/kiegroup/kie-wb-common/pull/3099

KOGITO-652: Updating setContent method

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/docks/KogitoDecisionNavigatorDock.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/docks/BaseKogitoDockTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/docks/KogitoDecisionNavigatorDockTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/docks/KogitoPreviewDiagramDockTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/docks/KogitoPropertiesDockTest.java

See https://issues.redhat.com/browse/KOGITO-937
**_How to test (for speed and simplicity)_**
1. `mvn clean install -DskipTests -Dgwt.compiler.skip=true` the `kie-wb-common-dmn` module.
2. `mvn clean install` the `kie-wb-common-dmn-webapp-kogito-runtime` module.
3. Fetch the latest `kogito-tooling` [repository](https://github.com/kiegroup/kogito-tooling.git).
4. Update the version of DMN used [in](https://github.com/kiegroup/kogito-tooling/blob/master/packages/kie-bc-editors-unpacked/pom.xml#L40) `packages/kie-bc-editors-unpacked/pom.xml`
5. `cd kogito-tooling`
6. `yarn run init`
7. `yarn run build:prod`
8. Follow the [README](https://github.com/kiegroup/kogito-tooling/blob/master/README.md) to test in VSCode and GitHub (Decision Navigator should be on the RIGHT).
9. Unzip …

KOGITO-937: [DMN Designer] Decision Navigator dock position per channel

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationView.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.less
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/views/session/EmptyStateLayer.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/views/session/EmptyStateView.java

See https://issues.redhat.com/browse/DROOLS-4989
The background, font and icon colours have been made consistent with https://www.patternfly.org/v3/pattern-library/communication/empty-state/#code

DROOLS-4989: [DMN Designer] Tab content background colour consistency

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/editors/types/DataObjectsServiceImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/editors/types/DataObjectsServiceImplTest.java

RHDM-1145: [DMN Designer] Java Date field is not converted to DMN date type
DROOLS-4977: [DMN Designer] Refactor DataObjectsServiceImpl to not duplicate logic from ParseHelper
EDIT: is not a part of an ensemble anymore. The changes in the Drools was superseded by https://github.com/kiegroup/drools/pull/2735

RHDM-1145: [DMN Designer] Java Date field is not converted to DMN date type

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNProjectEditorMenuSessionItems.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorTest.java

https://issues.redhat.com/browse/JBPM-8986
This removes the migrate button from Stunner. Preventing migration from the new designer to the legacy one.

JBPM-8986 - Remove Migrate Button from Business Process Designer (Stunner)

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-api/src/main/java/org/kie/workbench/common/screens/server/management/utils/ControllerUtils.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/utils/ControllerExtensionTest.java

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
Related JIRAs
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2657
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2008
https://issues.redhat.com/browse/JBPM-8585
Related PRs
https://github.com/kiegroup/droolsjbpm-integration/pull/1995
Followed-By PRs
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414
https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/329
https://github.com/jboss-container-images/jboss-kie-modules/pull/352
https://github.com/kiegroup/kie-cloud-operator/pull/353

[RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/palette/BS3PaletteWidgetImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenPreMaximizedStateEvent.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/screens/DiagramEditorExplorerScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/screens/DiagramEditorPropertiesScreen.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/test/java/org/kie/workbench/common/stunner/kogito/client/screens/DiagramEditorExplorerScreenTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorTest.java

Hi @romartin Can you review this PR?

JBPM-8903 : Stunner - Properties panel is not opened after clicking on "Minimize panel" button

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParser.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParserTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/README.md
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/services/WorkItemDefinitionStandaloneClientService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/resources/org/kie/workbench/common/stunner/kogito/KogitoBPMNEditor.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/services/BPMNStaticResourceContentService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/services/WorkItemDefinitionStandaloneClientServiceTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientMarshalling.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramServiceTest.java

Hey guys,
This PR provides support service tasks in the kogito space. See [KOGITO-277](https://issues.redhat.com/browse/KOGITO-277)
This PR is a continuation of @jesuino 's work ([see PR](https://github.com/kiegroup/kie-wb-common/pull/3034)), and it also includes the fixes for the [missing points](https://issues.redhat.com/browse/KOGITO-277?focusedCommentId=13936693&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13936693) previously identified on top. So it's also using the "new resouce api" from kogito to fetch the declarations and icons for service tasks, if present.
I'll keep working on adding tests and completing the TODO's tomorrow, but the `bpmn-kogito-runtime` webapp it's already running fine (or should be :)), so can you please to the review on the …

KOGITO-277: Stunner - Enable support for Service Tasks (Work Item Handlers)

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/ImportsFieldEditorWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/popup/editor/ImportsEditorWidget.java

https://issues.redhat.com/browse/RHPAM-2699
The @EventHandler tags for the field and the button were removed, preventing the call for
the method that opens the dialog. 
This changes were introduced by this commit:
https://github.com/kiegroup/kie-wb-common/commit/445d3d307a92f741969979567ed22d99e902afe6
This fixes the problem.

RHPAM-2699 - Stunner - Imports dialog not opening

---

kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/main/java/org/kie/workbench/common/screens/archetype/mgmt/backend/maven/BuildProjectCommand.java
kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/main/java/org/kie/workbench/common/screens/archetype/mgmt/backend/service/ArchetypeServiceImpl.java
kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/test/java/org/kie/workbench/common/screens/archetype/mgmt/backend/maven/BuildProjectCommandTest.java
kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/test/java/org/kie/workbench/common/screens/archetype/mgmt/backend/service/ArchetypeServiceImplTest.java

**Task**: [AF-2433](https://issues.redhat.com/browse/AF-2433)
**What's been done**: Building the template project for validation purposes using `MavenEmbedder#buildProjects` instead of executing the maven request from scratch.
**Expected behavior**: No related errors thrown during BC startup.

[AF-2433] Fixed error when building the base kie template

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/services/BPMNStaticResourceContentService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/services/WorkItemDefinitionStandaloneClientServiceTest.java

Hey @jesuino @ederign @porcelli @manstis 
Actual master upstream is broken after merging https://github.com/kiegroup/appformer/pull/886. Here are the fixes to make this repo compile again.
Can you please quickly review and merge, if so? I think that's urgent because master doesn't compile, at least for me.
PS: Please guys next time check the downstream builds are green before merging. I don't see the downstream build green for https://github.com/kiegroup/appformer/pull/886, and it's expected it should be running into this compile issue as well, as it's a compilation error. Anyway, just for the records, lemme know if I can help on any other thing! :+1: 
Thanks in advance!

KOGITO-862: Fixing compilation issues after ResourceContent API changed.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricher.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/BaseDecisionTableEditorDefinitionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionEnricherTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableEditorDefinitionTest.java

See https://issues.redhat.com/browse/DROOLS-5080
The long and short of it is this:
- Create a new DMN model
- Add an `InputData`
- Add a `Decision`, called `A` 
- Add another `Decision`, called `B`
- Link the `InputData` to `A`
- Link the `B` to `A`
- Edit `A` and set its expression to `DecisionTable`
- It should have input columns for the `InputData` and `B`.
- You should be able to use _built in types_ and custom types (including structures).

DROOLS-5080: [DMN Designer] Automatically create InputClause supporting Decisions

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/DMNClientDiagramServiceImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/DMNClientDiagramServiceImplTest.java

See: [https://issues.redhat.com/browse/KOGITO-1157](https://issues.redhat.com/browse/KOGITO-1157)

KOGITO-1157: [DMN Designer] New models must be named with the file name on VSCode

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentation.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/template/dmn-documentation-template.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants_es.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants_fr.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants_ja.properties
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/documentation/DMNDocumentationViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editors/documentation/DMNDocumentationViewButtonsVisibilitySupplier.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editors/documentation/common/DMNDocumentationFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/resources/META-INF/ErraiApp.properties
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editors/documentation/DMNDocumentationViewButtonsVisibilitySupplierTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editors/documentation/common/DMNDocumentationFactoryTest.java

See https://issues.redhat.com/browse/KOGITO-1337
The DMN _model name_ was already in the `DMNDocumentation` class, so I just removed `fileName`.
I've also [moved](https://github.com/kiegroup/kie-wb-common/pull/3208/files#diff-2beebe31108b6489cb3b435185072878) the existing _kogito_ version of `DMNDocumentationViewButtonsVisibilitySupplier` (and test) to the same sub-package path as the one it replaces for kogito for consistency. So there are a couple of other (sort of) related changes in this PR.
**TO TEST**
- Compile `kie-wb-common-dmn`
- Run `kie-wb-common-dmn-webapp-standalone`
- The "Documentation" tab will show both model name (Generated from) and user name (Generated by). The user name will be ANONYMOUS. If you run `drools-wb-webapp` you'll see a _real_ user name.
- Run …

KOGITO-1337: [DMN Designer] Author and filename are always non defined

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/DefinitionResolver.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/DefinitionResolverTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/DefinitionResolver.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/DefinitionResolverTest.java

Hi @romartin, @LuboTerifaj with this fix I was able to load 3 from 4 diagrams provided to me in RHPAM-2686. One of attached to jira issue diagram can be used to test this change (see comment in jira issue). 
This is first part of the RHPAM-2686, small fix for missing SimData. Now marshallers doesn't fail with NullPointer exception but just ignore missing SimData.

RHPAM-2727 - Stunner - it is not possible to open process without simulation extensions

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java

Jenkins execute full downstream build

KOGITO-437: Stunner - Zoom widget duplicated after `setContent` calls

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java

Supporting the new Preview API in DMN and BPMN Editors.
This is done by using canvasFileExport class inside the new client editor `GetPreview` method. GetPreview method will be called by Kogito tooling according to the user action on the channel where the tooling is running:
* On VSCode a new command was added;
* On Online Editor a new button allow users to download the SVG;
* It will be used by Desktop to generate preview of files recently opened by the user.
The getPreview method is any method form the editor that returns a string and have the GetPreview annotation. It works just like GetContent annotation, but it is not required, which means that if you don't provide it then by default it will return null. By default it returns null, no preview, if you want to export SVG from processes …

KOGITO-1236: Preview Support in Editors

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java

This PR creates 'png' screenshot in 'target' folder of the 'kie-wb-common-dmn-webapp-kogito-runtime' module in case of selenium test fail.
This should facilitate investigation of failures like reported in https://issues.redhat.com/browse/KOGITO-1458

KOGITO-1458: take screenshot in case of selenium test fail

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/services/WorkItemDefinitionStandaloneClientService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/services/WorkItemDefinitionStandaloneClientServiceTest.java

KOGITO-1301: Adding support for icons in Work Items
--
In this change we are retrieving binary content, creating the URL for a base64 content and returning a default ICON if the icon could not be loaded. The result can be seen below:
PART OF AN ENSEMBLE, Merge with:
https://github.com/kiegroup/kogito-tooling/pull/68

KOGITO-1301: Adding support for binary icons

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ActivityPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ActivityPropertyWriterTest.java

https://issues.redhat.com/browse/KOGITO-466
This is just a follow up on this:
https://issues.redhat.com/browse/JBPM-8680
Same functionality, different marshaller.

KOGITO-466 - Process with Reusable sub-process print errors to the server log

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/pom.xml

Currently we are uploading DMN Editor testing artifacts in the public repo.
This shouldn't happen, because testing artifacts are used for testing and development. Moreover, the war size is 77mb.
--> https://repository.jboss.org/org/kie/workbench/kie-wb-common-dmn-webapp-kogito-testing/
https://issues.redhat.com/browse/KOGITO-1521

KOGITO-1521: Avoid to publish kogito-testing artifacts

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidget.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItem.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/persistence/ItemDefinitionRecordEngine.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionDestroyHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionUpdateHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/DataTypePickerWidgetTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/persistence/ItemDefinitionRecordEngineTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionDestroyHandlerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/persistence/handlers/ItemDefinitionUpdateHandlerTest.java

Cherry-pick from commit [b3f3a03406f8d489ac94864e073827a317565693](https://github.com/kiegroup/kie-wb-common/commit/b3f3a03406f8d489ac94864e073827a317565693)

[7.33.X] DROOLS-5125: [DMN Designer] Node data type is lost after drag and drop in data type editor

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml

Hey @hasys 
Just a quick fix on the maven profiles for the BPMN kogito runtime webapp:
* Removed the `dev` profile 
* Fixed the `sources` profile
So let's keep it easy - there only exists a couple of profiles: `default` and `sources`:
* `default` - optimized / not source code
* `sources` - not optimized, prettyfied, source code (& sourcemaps) included
Thanks!

Stunner - Update maven profiles for bpmn kogito webapp

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml

The gwt compilation of the kie-wb-common-dmn-webapp-kogito-runtime is necessary for the selenium tests in this module.
The selenium tests open and html page generated byt the gwt compilation.
The no-showcase module is activated during full downstream build on jenkins. We keep this profile in the rest of dmn showcase webapps

KOGITO-1458: Run gwt compilation of kie-wb-common-dmn-webapp-kogito-runtime

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/src/main/java/org/eclipse/emf/ecore/xmi/resource/xml/XMLSave.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/src/test/java/org/eclipse/emf/ecore/xmi/resource/xml/XMLSaveTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/UserTaskPropertyWriter.java

Hi @romartin, @LuboTerifaj, @domhanak, @krisv 
this PR removes all ID without use from BPMN file in KOGITO (Business Central is not affected we have separate jira issue for it). Two ids are still generates on every save, but they are used somewhere, so I didn't remove it, we will handle it as separate jira issue.
* Documentaion
* LaneSet
* ioSpecification
* inputSet
* outputSet
* dataInputAssociation
* DataOutputAssociation
* Assignment
* TimerEventDefinition
* CompensateEventDefinition
* SignalEventDefinition
* errorEventDefinition
* completionCondition
* messageEventDefinition
* escalationEventDefinition
* conditionalEventDefinition
* terminateEventDefinition
* MultiInstanceLoopCharacteristics
* Potential Owner (User Task → Actor property)
* FormalExpression tags such as:
* …

KOGITO-395 BPMN Serialization reusing ID

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/test/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditorTest.java
kie-wb-common-kogito/kie-wb-common-kogito-client/src/main/java/org/kie/workbench/common/kogito/client/editor/BaseKogitoEditor.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/.gitignore
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/Viewer.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/AbstractDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/AbstractDiagramEditorCore.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/DiagramEditorCore.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/main/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-case-mgmt/kie-wb-common-stunner-case-mgmt-project-client/src/test/java/org/kie/workbench/common/stunner/cm/project/client/editor/CaseManagementDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/java/org/kie/workbench/common/stunner/standalone/client/editor/BPMNStandaloneDiagramEditor.java

This PR changes the set content method to return a Promise instead of void.
The goal of this change is to be able to make the loading of editors predictable and remove the need for double set content call.
This PR also includes the changes by @manstis and @romartin  at https://github.com/kiegroup/kie-wb-common/pull/3236/
Merge together with:
kiegroup/kogito-tooling#95
https://github.com/kiegroup/appformer/pull/934
The new changes are here: https://github.com/kiegroup/kie-wb-common/pull/3246/commits/0d5c3a182f32482fa74a58097c72709a57e06171

KOGITO-1436: Stunner - Remove double `setContent` call. 

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java

Without using GwtMockitoTestRunner test of gwt components fails
For more details see https://issues.redhat.com/browse/JBPM-9080

JBPM-9080: use proper test runner

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/pom.xml

This PR removes two unused dependencies
- uberfire-widgets-core-client
- errai-security-server
Both seems be leftovers from modules reorganization done in past.

DROOLS-5129: Remove unused dependencies

---

kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-templates/kie-all-templates/src/main/xslt/dependencies.xml

**Task**:[ AF-2464](https://issues.redhat.com/browse/AF-2464)
**Validation**:
1. Create a new project
2. Create an asset
3. Open the project explorer
4. Change to "_Repository view_" (Settings icon)
5. Find and open `pom.xml` file
6. Check `com.thoughtworks.xstream` dependency version

[AF-2464] Upgrade com.thoughtworks.xstream version (1.4.10 -> 1.4.11.1)

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/links/NameAndUriPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/links/NameAndUrlPopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/hitpolicy/HitPolicyPopoverViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/kindselector/KindPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/kindselector/KindPopoverViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/kindselector/KindPopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/selector/UndefinedExpressionSelectorPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/undefined/selector/UndefinedExpressionSelectorPopoverViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/ValueAndDataTypePopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/ValueAndDataTypePopoverView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/ValueAndDataTypePopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/PopupEditorControls.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/JQueryDropdownMenu.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelector.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorViewImpl.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorViewImpl.less
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/popover/AbstractPopoverImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/popover/AbstractPopoverViewImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/popover/PopoverView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/ValueAndDataTypePopoverImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/ValueAndDataTypePopoverViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/list/ListSelectorViewImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/popover/AbstractPopoverImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/widgets/grid/controls/popover/AbstractPopoverViewImplTest.java

See https://issues.redhat.com/browse/KOGITO-1577
_Context menus_ were not responding to keyboard events.
After a couple of days of trying alternatives this is the _only_ working solution I could find.

KOGITO-1577: Esc doesn't cancel context menus in DMN grid

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/FormPropertiesWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsFlushManager.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/container/FormsContainer.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/widgets/FormPropertiesWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsFlushManagerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/widgets/container/FormsContainerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java

https://issues.redhat.com/browse/KOGITO-987
This fix uses the recent added capability of "flushing" added in this JIRA:
[KOGITO-1219](https://issues.redhat.com/browse/KOGITO-1219). The flush method is called each time the document content is requested.
Providing updated content each time.

KOGITO-987 - VsCode editor - process id not saved/updated

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/common/TileView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/common/TileView.less
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/example/ExampleProjectView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/widgets/example/ExampleProjectView.less

**Task**: [AF-2462](https://issues.redhat.com/browse/AF-2462)
**Fixes**:
- Card title height (letters like 'g' and 'p' were being cut)
- Card description width (the text was being truncated before needed)
**Result**:

AF-2462: Minor fixes on the project sample card

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/DeclarationList.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/ParsedAssignmentsInfo.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/DeclarationListTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/ParsedAssignmentsInfoTest.java

Hey @domhanak @LuboTerifaj 
This PR fixes the issue [KOGITO-1529](https://issues.redhat.com/browse/KOGITO-1529)
**[Not Urgent]** It cannot yet be tested until having [KOGITO-1426](https://issues.redhat.com/browse/KOGITO-1426) done, so no worries for now, but I could reproduce and fix it locally so creating the PR with the fix for further re-integration.
Thanks!

KOGITO-1529: BPMN Editor - Cannot save a process once a service tasks' attributes are not properly set

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml

They are now managed by kie-parent.
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425

BXMSPROD-741: Remove Node and npm versions

---

kie-wb-common-ala/kie-wb-common-ala-services-rest/src/test/java/org/guvnor/ala/services/rest/tests/RestRuntimeProvisioningImplTest.java

Ignored test until we find a permanent fix.

AF-2469 :kie-wb-common-ala/kie-wb-common-ala-services-rest tests requires docker image kitematic/hello-world-nginx

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/resources/org/kie/workbench/common/screens/library/LibraryClient.gwt.xml
kie-wb-common-widgets/kie-wb-config-resource-widget/pom.xml
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/resources/org/kie/workbench/common/widgets/configresource/KieWorkbenchConfigResourceWidget.gwt.xml

This PR removes unused compile dependencies of modules:
- kie-wb-common-library-client
- kie-wb-config-resource-widget
For more details see https://issues.redhat.com/browse/DROOLS-5266

DROOLS-5266 Remove unused compile dependencies

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.java

Hi @romartin, @LuboTerifaj,
this one was easy one. But it is good question, do we have any limits on the body? I didn't found any info about it. Maybe @MarianMacik @cristianonicolai have any info?
Also, I found two further possible issues to fix:
* all content after `@` symbol is cutted
* it is not possible to "enlarge" the text area. It is easy to fix, if needed. See on the picture below how it can be. Yes, it looks little bit ugly, but it can be useful and "better than nothing". I found it useful when I looked why part of the body still cut (see previous point).

RHPAM-2881 Notification Form in Stunner is limiting the Body content

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/DMNClientServicesProxyImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/FEELSyntaxLightValidator.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/DMNClientServicesProxyImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/services/FEELSyntaxLightValidatorTest.java

*Please refer to:* https://issues.redhat.com/browse/KOGITO-1687
*Issue description:* Data type name validation is not present in Kogito
*Proposed solution:* Data type name validation is present in Business Central, in particular in the class `FeelParser`.
However, as for now, we cannot use back-end services in dmn client, so for the short/middle term, the solution is to have a tiny&simple validation mechanism for variable names, that would cover as more cases as possible.

KOGITO-1687: DMN invalid data type names are not reported

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/Builder.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/core/BuilderTest.java

This exception was thrown in the build pipeline stage due to the asynchronous processing of events in incremental builds. During "Save and rename" operation for any resource,  Though the resource was moved, Resource modified event for original resource was queued in the build execution pipeline,  which result in NoSuchFileException. 
Please note that this exception happens in all resource types. To reproduce
1. Open resource (eg. .drl) 
2. Change any content
3. Click on rename
4. Select "Save and rename"

RHPAM-2674 :Exception thrown when a test scenerio containing a tag is renamed without saving

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/activities/ReusableSubprocessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/activities/CallActivityConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/BPMNDirectDiagramMarshallerTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/reusableSubprocessCalledElement.bpmn
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/activities/ReusableSubprocessConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/activities/CallActivityConverter.java

To test this PR I used `testProject.processName~!@#$%^&*()+``-={}[]:"|;'\<>?,./_` and full business central build. Works to me now.

RHPAM-2432 it is possible to break process by setting incorrect called element

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcess.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcessTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java

*Please refer to:* https://issues.redhat.com/browse/DROOLS-5253
*Issue description:* If user copy a DMN diagram node, the copy has exactly the same name as the original node. It causes validation issues as the node names have to be unique. 
*Proposed solution:* Every time we copy a node, a new node will be created with a suffix `-X`, where `X` it is an incremental numeric value.
Logic on uniqueness is performed. For instance, when copying the node `InputData-1`, if, for some reason, `InputData-2` is already present, then the name of the copied node will be `InputData-3`.

DROOLS-5253: [DMN Designer] Copied node should be distinguished from original one

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/pom.xml

parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1203

JBPM-9044: added needed annotation-api dependency for stunner tests

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandalone.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/common/DMNMarshallerImportsHelperStandaloneImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/HrefBuilder.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/editors/common/DMNIncludedNodeFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandaloneTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/common/DMNMarshallerImportsHelperStandaloneImplTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/HrefBuilderTest.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/editors/common/DMNIncludedNodeFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/included/components/DecisionComponentsItemView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/included/components/DecisionComponentsItemViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/DMNMarshallerKogitoMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/HrefBuilder.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/utils/WrapperUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/HrefBuilderTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/utils/WrapperUtilsTest.java

See: https://issues.redhat.com/browse/DROOLS-5229
Before:
```xml
<dmndi:DMNShape id="dmnshape-included1:_ADC4CFCC-385B-42FE-8C61-0B2DA34AC20B" dmnElementRef="included1:_ADC4CFCC-385B-42FE-8C61-0B2DA34AC20B" isCollapsed="false">
</dmndi:DMNShape>
```
After:
```xml
<dmndi:DMNShape id="dmnshape-_ADC4CFCC-385B-42FE-8C61-0B2DA34AC20B" dmnElementRef="included1:_ADC4CFCC-385B-42FE-8C61-0B2DA34AC20B" isCollapsed="false">
</dmndi:DMNShape>
```
This PR removes the `"included1:"` from Shape id, preventing this XML validation error:
```
DMN: Failed XML validation of DMN file: cvc-datatype-valid.1.2.1: 'dmnshape-included1:_50B0350A-72CE-4803-AE8B-7ED16409BC1B' is not a valid value for 'NCName'.
```
Also, I'm intentionally keeping the duplication between the server and the client-side implementation …

DROOLS-5229: DMNValidate mojo fails XMLSchema validation with included models

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/LiteralExpressionPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/definition/v1_1/BaseLiteralExpressionPropertyConverterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/LiteralExpressionPropertyConverter.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/LiteralExpressionPropertyConverterTest.java

*Please refer to:* https://issues.redhat.com/browse/DROOLS-5245
*Issue description:* Description and Expression language properties are not stored for Literal cell
*Proposed solution:* Change `LiteralExpressionPropertyConverter` both on back-end service and on kogito side

DROOLS-5245: [DMN Designer] Literal cell value properties are not stored

---

kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/test/java/org/kie/workbench/common/forms/editor/backend/service/impl/FormEditorServiceImplTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/test/java/org/kie/workbench/common/forms/editor/backend/service/impl/helpers/AbstractFormDefinitionHelperTest.java
kie-wb-common-forms/kie-wb-common-forms-editor/kie-wb-common-forms-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/main/java/org/kie/workbench/common/screens/archetype/mgmt/backend/service/ArchetypeServiceImpl.java
kie-wb-common-screens/kie-wb-common-archetype-mgmt/kie-wb-common-archetype-mgmt-backend/src/test/java/org/kie/workbench/common/screens/archetype/mgmt/backend/service/ArchetypeServiceImplTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/java/org/kie/workbench/common/screens/datamodeller/backend/server/AbstractDataModelerServiceWeldTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/java/org/kie/workbench/common/screens/datamodeller/backend/server/DataModelerEventObserverTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/java/org/kie/workbench/common/screens/datamodeller/backend/server/DataModelerServiceHelperTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/main/java/org/kie/workbench/common/screens/impl/LibraryAssetUpdateNotifier.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/BaseLibraryIndexingTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/LibraryAssetUpdateNotifierTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/java/org/kie/workbench/common/screens/impl/LibraryServiceImplTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider

* Disable JGit specific features when JGit is not the default FS
* Add a switch to choose between Monitoring and Simplified Monitoring
Simplified monitoring is the K8S FS based solution. This can't use JGit specific parts so they are disabled (Like _Pages_)
Possible values:
* -Dorg.appformer.server.simplified.monitoring.enabled=true/false
* https://github.com/kiegroup/appformer/pull/882
* https://github.com/kiegroup/kie-wb-common/pull/3128
* https://github.com/kiegroup/drools-wb/pull/1363
* https://github.com/kiegroup/jbpm-designer/pull/881

AF-2410: Added switch to remove BC features in Monitoring

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/widget/AttachmentFileWidget.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/widget/AttachmentFileWidgetTest.java

Ensemble with:
- https://github.com/kiegroup/drools-wb/pull/1355
The exposed filename will help in XLS/XLSX new file dialogue to determine how to handle file creation.
For more details see https://issues.redhat.com/browse/DROOLS-5274

DROOLS-5274: Expose filename of selected file to upload

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/service/AbstractKogitoClientDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramServiceTest.java

https://issues.redhat.com/browse/KOGITO-2166
Removing this as it is not related to the Package property

KOGITO-2166 - VSCode editor - Package property: default is not a valid Java package name

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/EmbeddedControllerIT.java

https://issues.redhat.com/browse/BXMSPROD-756
This is a random issue during wildly stop/undeploy. The failure jobs have already expired, I can't reproduce it and I can't investigate it deeper. I would at least add a timeout for the failure test in order not to wait for pipeline timeout and start investigating why the timeout has been reached.
wdyt? It's not very elegant solution but at least until we are able to investigate properly...

BXMSPROD-756 timeout added to EmbeddedControllerIT tests

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/remote/card/ContainerCardPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/remote/card/ContainerCardPresenterTest.java

* If container-alias is not available for a container, then the ContainerSpec is created with ContainerSpecId.
Deployable WAR: https://drive.google.com/open?id=15xPtrTK2vR8DpYe-Fcy8TUDbFk-VwOY7

AF-2514 : Execution Server UI breaks if connected to a KIE Server that has a KContainer deployed that its jar is not on BC internal Maven repo

---

kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/query/standard/FindRuleFlowNamesQuery.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/query/standard/FindRuleFlowNamesQueryTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/RuleFlowGroupQueryServiceTest.java

Hi @romartin this fix is inspired by the similar one: https://github.com/kiegroup/kie-wb-common/pull/2950/files
Also, I think there is still two issues on Business Central side.
1. Rules should be removed from the index when project is removed, because now we still have a message in a log about missing file
```
20:07:58,208 ERROR [org.kie.workbench.common.services.refactoring.backend.server.query.standard.FindRuleFlowNamesQuery] (default task-6) org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://master@MySpace/ProjectA/src/main/resources/com/myspace/projecta/TestGroup1.rdrl) found.
```
2. I think [FileSystemNotFoundException](https://github.com/kiegroup/appformer/blob/ae323c023e1fab4a45fba3bf2e7f7c5f20987b8e/uberfire-nio2-backport/uberfire-nio2-model/s …

JBPM-9110 business rule tasks cannot be configured properly

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml

https://issues.redhat.com/browse/JBPM-9189
parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1364

JBPM-9189: fixing used version of wildfly-dist

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml

This is a change for having always directory for Errai Wildfly unpacked distribution to be on the same name as original wildfly distribution as Errai just repackaged it so naming directory to that version is not confusing

fixed real directory for Errai Wildfly distribution

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/elements/GlobalVariablesElement.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/Variable.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/VariableTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElement.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElementTest.java

https://issues.redhat.com/browse/RHPAM-2990
https://issues.redhat.com/browse/RHPAM-3015
Variables accept empty data type values without problems.
Data types are loaded after save.
This applies for Assignment, Process and Global Variables.
Wars and artifacts:
[Business Central](https://drive.google.com/file/d/1775FmEXas184ha-uAm3EkjIprijOYjMY/view?usp=sharing)

RHPAM-2990 / RHPAM-3015 - Variable Data Type related problems

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/webapp/index.html
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/service/BPMNClientDiagramServiceTest.java

Hi @romartin, @domhanak,
To test this PR just put `&` sign inside of any XML attribute value. Only Kogito code was modified so no need to test Business Central. 
VSIX can be downloaded here: https://drive.google.com/drive/u/0/folders/1UzvsBmC4PVaxaIFdmnetQjwRizJJuOjl
PR is ready for review, thank you!
<details>
<summary>Technical details</summary>
<pre>There are two parts fixed: BPMN Editor itself and HTML where editor is embedded. 
* Kogito-Stunner has generic AbstractEditor which already support ACE Editor but only for `DiagramParsingException`, so I fixed it in BPMN Editor and ACE editor was called.
* Second issue was that we need to link ACE editor in HTML separately from the editor itself, that's why there is HTML fix as well.
Also, looks like there are two different ways how ACE …

KOGITO-513 - Do not open editor when .bpmn file can't be loaded

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/elements/GlobalVariablesElement.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/Variable.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/VariableTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElement.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElementTest.java

https://issues.redhat.com/browse/JBPM-9182
Global Variables accept empty data type values without problems.
https://issues.redhat.com/browse/JBPM-9199
All other variable based fields now keep the data type after saving.
[Business Central](https://drive.google.com/file/d/196Mkj5Qa4OTN_X01aBvk3kUveCQ4iQKJ/view?usp=sharing)
[VSIX](https://drive.google.com/file/d/1RXcmBiA3YEHssE1Bj3ePkEVKhUre9bwR/view?usp=sharing)

JBPM-9182 / JBPM-9199 - Variable related issues

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/sections/externaldataobjects/ExternalDataObjectsItemPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/sections/externaldataobjects/ExternalDataObjectsItemView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/settings/sections/externaldataobjects/ExternalDataObjectsItemPresenterTest.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/BuiltInTypeImportHelper.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetPresenter.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetView.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetViewImpl.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/unbound/ImportsWidgetPresenter.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/unbound/ImportsWidgetView.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/main/java/org/kie/workbench/common/widgets/configresource/client/widget/unbound/ImportsWidgetViewImpl.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/BuiltInTypeImportHelperTest.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetPresenterTest.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/bound/ImportsWidgetViewImplTest.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/unbound/ImportsWidgetPresenterTest.java
kie-wb-common-widgets/kie-wb-config-resource-widget/src/test/java/org/kie/workbench/common/widgets/configresource/client/widget/unbound/ImportsWidgetViewImplTest.java

This PR prevents users from removing java built in type imports on three places:
- Project Settings -> External Dependencies tab
- project.imports file
- Guided editors -> Data Objects tab
For more details see the jira: https://issues.redhat.com/browse/DROOLS-5262

DROOLS-5262: Do not allow to remove java built in type imports

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml

For more details see: https://issues.redhat.com/browse/DROOLS-5499

DROOLS-5499: Remove unused compile dependecies - kie-wb-common-server-ui-backend

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/timerEditor/TimerSettingsFieldEditorView.html

Hi @romartin, @domhanak, @tomasdavidorg,
it is a quick fix, but I think it is good enough, since we will fully rework forms in near future.
VSIX for tests can be downloaded here: https://drive.google.com/file/d/1AVtusv1reXlrGELES-HPUS8wN0DXogeY/view?usp=sharing
There how it is looks like now in the Business Central:
I didn't build it locally just tricked css styles directly on running instance.

KOGITO-1660 Fire multiple times type property dropdown is too small

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/popup/editor/defaultImport/DefaultImportListItemWidgetView.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/AssignmentRow.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/VariableRow.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValues.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/ActivityDataIOEditorViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/importsEditor/popup/editor/defaultImport/DefaultImportListItemWidgetViewTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/VariableRowTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValuesTest.java

https://issues.redhat.com/browse/JBPM-9165
This removes the empty value from the data type combo box and uses the value "Object" as the default value.
[Business-Central](https://drive.google.com/file/d/1YjOX8505d50fNrUBWa-PXgW0cAv00bWA/view?usp=sharing)
[VS Code Extension](https://drive.google.com/file/d/1qwqNaelzwd30pL1qUMq4tDw7-wP386wb/view?usp=sharing)

JBPM-9165 - Stunner - Global / Process variables allow empty value as data type

---

kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/main/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCell.java
kie-wb-common-widgets/kie-wb-decorated-grid-widget/src/test/java/org/kie/workbench/common/widgets/decoratedgrid/client/widget/cells/PopupDateEditCellTest.java

https://issues.redhat.com/browse/DROOLS-5516
Templated rules store the table data with Strings. For this reason you get what you see both in server and client side. The grid cell, as far as I know and could find, is only used by templated rules so removed the conversions.

DROOLS-5516 : Date field in Guided rule template is not displaying correct date

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/EventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/EventPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ThrowEventPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/EventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ThrowEventPropertyWriterTest.java

Hi @romartin,
I tested Kogito and XML looks good, will build Business Central locally to perform some End to End tests and will move it to full review. For now code is ready for the review.
Hi @domhanak, @LuboTerifaj, do we need your review here or we can assign it to two Software Engineers?
Thank you!
https://drive.google.com/file/d/1OUikD9cxc008URF85eLjrfggPVueKLTK/view?usp=sharing
https://drive.google.com/file/d/1ZvjXoy2St0A_J1gSXiQsxsgVmVFqUfVo/view?usp=sharing
https://github.com/bpmn-tutorials/EmptyErrorTest

JBPM-9276 - Stunner Empty ErrorRef for the Error Start Event produces build errors

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/i18n/StunnerFormsClientFieldsConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/forms/fields/i18n/StunnerFormsClientFieldsConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java

Hi @romartin @handreyrc can you review this PR? Change is simple, there was a check before to show a warning if the variable is output and expression. I removed the custom message and constants and updated test code. Let me know

KOGITO-2651 : Allow expressions in output assignments

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/selenium/BPMNDesignerKogitoSeleniumIT.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/resources/org/kie/workbench/common/stunner/kogito/client/selenium/basic-process.bpmn2
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/resources/org/kie/workbench/common/stunner/kogito/client/selenium/new-diagram.bpmn2

@hasys @romartin please take a look at this. I have more tests in progress, but I keep getting fails
in these 3 smoke tests so I decided to bring this up to more eyes.
They use `index.html` and JS execution to load up the editor.
As of now 2 will fails with following reasons:
- `testInvalidContent` fails because there is dialog with unreasonable message shown to user.
Reported here: https://issues.redhat.com/browse/KOGITO-2147
- `testBasicModel` fails because upon reopening a diagram, some of it's id attributes are changed to different values.
Reported here: https://issues.redhat.com/browse/KOGITO-1795
To run locally, build kogito-client and run `mvn verify -Pkogito-it-tests` (omit clean to keep target folder with the editor)

KOGITO-1508: Add initial selenium tests for kogito bpmn client

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/notification/NotificationValue.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/NotificationValueTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/ParsedNotificationsInfos.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ParsedNotificationsInfosTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/ParsedNotificationsInfos.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/ParsedNotificationsInfosTest.java

Hi @romartin,
I tested it locally and it works now, I can save and reload the process without issues, uploading a WAR (some connection issue, it takes time today), will attach it later.
@domhanak, @LuboTerifaj do we need your approve or we can assign second Software Engineer to a review?
Thank you!
https://drive.google.com/file/d/16r5eNFShPjak1gsPmHq1XGBmzRHWBY8I/view?usp=sharing
https://drive.google.com/file/d/1IUKYH1Zvt-0HqiLdGm7rGTLPRaaHrAF0/view?usp=sharing

JBPM-9275 - Stunner - '^' character in Notification subject in User task breaks the process

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/selection/DomainObjectAwareLienzoMultipleSelectionControl.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditDRDToolboxAction.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/contextmenu/ContextMenu.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/drd/DRDContextMenu.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/selection/DomainObjectAwareLienzoMultipleSelectionControlTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditDRDToolboxActionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/drd/DRDContextMenuTest.java

**JIRA**: https://issues.redhat.com/browse/KOGITO-3022
**Task description:** When multiple nodes are selected, it should be possible to add/remove them from an existing DRD or to create a new one with them.
**Proposed solution:** the DRD context menu widget will be displayed when more than one node is selected, right clicking on one of them.
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**
* a full production downstream please add comment: regex …

KOGITO-3022: [DMN Designer] Multiple DRDs support - Context menu - When multiple nodes are selected, showing context menu with right click

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/notificationsEditor/widget/NotificationEditorWidgetViewImpl.html

**JIRA**: [JBPM-9290](https://issues.redhat.com/browse/JBPM-9290)
Hi @romartin this is a small fix we talked about. Thank you!
Hi @domhanak, @LuboTerifaj, will check this PR or we can reassign it to another developer?
https://drive.google.com/file/d/1t8EUEcpsY3MHfjbXclrwA11C3d9VfDFA/view?usp=sharing
https://drive.google.com/file/d/1CIN4DT3bgEQWX-HxH7yf0NFUJQMnYufp/view?usp=sharing
https://drive.google.com/file/d/10jwlCy7fd4YVpEVAl7BRAKwGSEdtn_vv/view?usp=sharing
https://drive.google.com/file/d/1XPXcgjLi3Nrd0_SGf6-RMxPuypjBJSIa/view?usp=sharing

JBPM-9290 - Stunner - make body field of Notification resizable

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/src/main/resources/org/kie/workbench/common/stunner/project/StunnerProjectShowcase.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/resources/org/kie/workbench/common/stunner/standalone/FastCompiledStunnerStandaloneShowcase.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone/src/main/resources/org/kie/workbench/common/stunner/standalone/StunnerStandaloneShowcase.gwt.xml

Hey @mbiarnes @mareknovotny 
I've created this PR trying to avoid issues on our CI builds, due to the wrong use of resources. So let's see how the builds work on this PR, and hopefully sooner than later we should have green full builds again for this repo :+1: 
I've done a few improvements for the gwt compiler on the differents apps, but the most important change is on the `stunner-showcase-project` app - gwt compiler was not properly configured and also I've reduced the stress during its compilation by decreasing the permutaions and optimization around it, anyway this app is jsut for our testing, nothing that gets delivered as part of any product, so we're good also this way.
Here is a quick profiling about the hardware stress on the gwt compiler process before and after these fixes: …

Stunner - Reduce the hardware stress for GWT builds

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/LRUBuilderCache.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/core/LRUBuilderCacheTest.java

**Description** :
* Introducing new property 'org.kie.builder.cache.size' to configure LRUBuilderCache size
**JIRA**: 
- [AF-2452](https://issues.redhat.com/browse/AF-2452)
- [RHPAM-2808](https://issues.redhat.com/browse/RHPAM-2808)
* https://github.com/kiegroup/appformer/pull/1032
<pre>
How to retest a PR or trigger a specific build:
</pre>

AF-2452 : Making LRUCache configurable to avoid large memory retention

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/changerequest/review/comment/CommentItemView.css

JIRA: [AF-2608 ](https://issues.redhat.com/browse/AF-2608)
Fixed style since the inherited one no longer applies.
Before:
After:
<pre>
How to retest a PR or trigger a specific build:
</pre>

AF-2608: Fix comment card style

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenterTest.java

- Added ContainerSpec check
- clean up
**JIRA**:  [RHPAM-3134](https://issues.redhat.com/browse/RHPAM-3134)
<pre>
How to retest a PR or trigger a specific build:
</pre>

RHPAM-3134 : UI issue (in business-central) when more than one kie-server (with different ID) is connected

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/session/BPMNSessionInitializer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/CalledElementFormProviderTest.java

Hi @romartin @handreyrc can you review this PR? Basically every time the CalledElement for property was created and a call to get the contents it was firing up a Server event, but returned immediately so the data was not updated, if you previously selected and unselected the element it would get the right data. What I did is make the call upon the Form Provider creation so that the data is ready when the user clicked on the combo box.

JBPM-9266 : Stunner - Called element in Reusable sub-process is not populated

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/Match.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/FlowElementConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/ProcessConverterDelegate.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/MatchTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/FlowElementConverterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/processes/ProcessConverterDelegateTest.java

All nodes were processed as by FlowElementConverters. Edge nodes are processed by a different set of converters.
This fix intends to filter them accordingly and use the correct converters for processing.
**JIRA**: [RHPAM-2452](https://issues.redhat.com/browse/RHPAM-2452)
**Business Central**: [WAR file](https://drive.google.com/file/d/1twxhguRF395vT2L-NwFaFWupsTXIzFGI/view?usp=sharing)
**VS Code**: [*Not reproducible in VS Code*]

RHPAM-2452 - Stunner - Migration from old designer to new one shows Warnings for the simplest processes

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/RuleFlowGroupFormProvider.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/session/BPMNSessionInitializer.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/RuleFlowGroupFormProviderTest.java

Hi @romartin @handreyrc can you review this PR? Basically the Ruleflow was not being populated because it called the server but returned results immediately before the event (back) was catched. Modified so that it initializes when the form provider gets called.

JBPM-9267 : Stunner - Rule flow group is not populated

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNClientProjectDiagramService.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNClientProjectDiagramServiceTest.java

**JIRA**: [DROOLS-5656](https://issues.redhat.com/browse/DROOLS-5656): [DMN Designer] Multiple DRDs support - Editor shows duplicated file extension on BC
**Artifact (it happens on Business Central only)**: [WAR file](https://www.dropbox.com/s/lf5xpgebox3lxth/after.war?dl=0)
**Before:**
**After:**
---
<pre>
</pre>

DROOLS-5656: [DMN Designer] Multiple DRDs support - Editor shows duplicated file extension on BC

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenterTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommands.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/validation/DMNCanvasDiagramValidator.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/validation/DMNValidateSessionCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/session/DMNEditorSessionCommandsTest.java

**JIRA**: [RHPAM-3190](https://issues.redhat.com/browse/RHPAM-3190): RHPAM-3190: Stunner - Error is displayed when using BPMN designer editor
**Artifact (it happens on Business Central only)**: [WAR file v2](https://www.dropbox.com/s/mllt9lkwfj8ydt6/business-central-RHPAM-3190-2.war?dl=0)
**Before:**
**After:**
---
<pre>
</pre>

RHPAM-3190: Stunner - Error is displayed when using BPMN designer editor

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java

Hey @paulovmr @ederign 
As discussed with @porcelli , fixing the actual blocker issue by completely disabling validation in the bpmn editor.
See comments in https://issues.redhat.com/browse/JBPM-9352
BTW You know who should be the QE tester for this, if any? Can't see anyone on the ticket yet.
Thanks!

JBPM-9352: Stunner - Warning when getContent is called while the model is invalid

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/main/java/org/kie/workbench/common/screens/datamodeller/backend/server/DataModelerServiceImpl.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/src/test/java/org/kie/workbench/common/screens/datamodeller/backend/server/DataModelerServiceTest.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenterTest.java

**Issue**: When we change a package or fileName in the general properties of DataModeller and save it, the DataObject is reloaded. If we try to close the data object before reload is complete we see unsaved changes dialog. 
**Reason**: DataObject context and source are updated only during reloading.
**Solution**: The context and source hash are updated before reload. The DataObject is sent to the server after any change in DataModeller or the source to handle the inconsistencies in source and DataObject Model.
**JIRA**: [RHPAM-3119](https://issues.redhat.com/browse/RHPAM-3119)
<details>
<summary>
</summary>
* A compile downstream build: <b>jenkins do …

RHPAM-3119 : [Data Modeler] Unsaved changes dialog appears after rename

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorOptions.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorView.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorPresenterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorViewTest.java

Hey @romartin, Please, could you review this PR?
Notice that I've enabled the miniMap(Preview) attending to requests. 
The editor looks broken once the miniMap space is not returned back to the editing area.
**JIRA**: [RHPAM-3178](https://issues.redhat.com/browse/RHPAM-3178)
**Business Central**: [WAR file](https://drive.google.com/file/d/1922TMxt848gN_MXx6PG1RHREP9OnD3uM/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1RH7i1tnC8hiIrTQ-rmjpwgMV5rIENr2m/view?usp=sharing)
Thanks!

RHPAM-3178: Stunner - Monaco script editor scrollbars disappear

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/converters/InputClausePropertyConverter.java

**JIRA**: https://issues.redhat.com/browse/KOGITO-3366
<details>
<summary>
During DMN file unmarshalling, `inputValues`, in order to be editable, should not be null.
</summary>
</details>

KOGITO-3366: [DMN Designer] Boxed Expression - Decision Tables - Users lost constraints when they change the focus

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/ProjectDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/editor/BPMNDiagramEditorTest.java

SaveAndRenameCommandBuilder where supplying the wrong action when saving trying to save the file.
This fixes the problem by setting the right action as soon as that action is defined.
**JIRA**: [RHPAM-2802](https://issues.redhat.com/browse/RHPAM-2802)
**Business Central**: [WAR file](https://drive.google.com/file/d/1FZSRGjoQkeDOWpt5U1Bszuy1_iM247Xw/view?usp=sharing)
<details>
<summary>
</summary>
</details>

RHPAM-2802 - Save and Rename of DMN/BPMN leads to Unexpected error

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java

**JIRA**: [KOGITO-3571](https://issues.redhat.com/browse/KOGITO-3571): [DMN Designer] Multiple DRDs support - Information requirements are duplicated into the DMN XML
Before:
After:
Here's the [DMN model](https://gist.github.com/karreiro/dd00ffc17138865fb44c9ae600630c31) used in the GIFs.
**Business Central**: [WAR file](https://www.dropbox.com/s/3l081n8gxugaduf/business-central-KOGITO-3571.war?dl=0)
**VS Code**: [plugin](https://www.dropbox.com/s/v60khlm3lrur0m4/vscode-plugin-KOGITO-3571.vsix?dl=0)
<details>
<summary>
</summary>
* …

KOGITO-3571: [DMN Designer] Multiple DRDs support - Information requirements are duplicated into the DMN XML

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/project/KieModuleServiceImpl.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/project/KieModuleServiceImplTest.java

**JIRA**: [AF-2644](https://issues.redhat.com/browse/AF-2644)
Problem is that there are two empty packages. One shows up as "nothing selected" and the other as "<default>". Removing one of them.

AF-2644 : Package list fails to populate default package for imported projects

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/assets/PopulatedAssetsScreen.java

**RHPAM-2859**: https://issues.redhat.com/browse/RHPAM-2859
</summary>
</details>

RHPAM-2859 :Number of assets displayed for a project doesn't matches the count displayed

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasConnectorNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteElementsCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNSafeDeleteNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNDeleteConnectorCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionTargetNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/util/ContentDefinitionIdUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNCanvasHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasConnectorNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNDeleteConnectorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionTargetNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/util/ContentDefinitionIdUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/DeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/DeleteConnectorCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SetConnectionSourceNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SetConnectionTargetNodeCommand.java

**JIRA**: [KOGITO-3364](https://issues.redhat.com/browse/KOGITO-3364)
<details>
<summary>
</summary>
</details>

KOGITO-3364: [DMN Designer] Multiple DRDs support - When a node is deleted in the DRG, undo/redo operations do not work properly

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java

**[7.44.x] DROOLS-5707: [DMN Designer] Multiple DRDs support - Information requirements are duplicated into the DMN XML**
**JIRA**:
- [DROOLS-5707](https://issues.redhat.com/browse/DROOLS-5707) - Information requirements are duplicated into the DMN XML
- [DROOLS-5749](https://issues.redhat.com/browse/DROOLS-5749) - When users open a DMN with duplicated information requirements, the marshaller doesn't fix it
**Business Central**: [WAR file](https://www.dropbox.com/s/8cackuzerxozck5/business-central-7.44.x-DROOLS-5707-2.war?dl=0)
<details>
<summary>
</summary>
* A full production downstream build: …

[7.44.x] DROOLS-5707: [DMN Designer] Multiple DRDs support - Information requirements are duplicated into the DMN XML

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresConnectorViewExt.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresShapeViewExt.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresTextDecorator.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresConnectorViewExtTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresShapeViewExtTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresTextDecoratorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasTitle.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/shape/ShapeViewExtStub.java

Hey @romartin: Please, could you review this PR?
This PR fixes the following related issues:
**JIRA**: [KOGITO-3517](https://issues.redhat.com/browse/KOGITO-3517)
**JIRA**: [RHPAM-3197](https://issues.redhat.com/browse/RHPAM-3197)
* [kogito-tooling](https://github.com/kiegroup/kogito-tooling/pull/290)
**VS Code**: [plugin](https://drive.google.com/file/d/1DnnlIF-z3NaTLSHxnDG_W67t5hqWOX-s/view?usp=sharing)
Thanks!

KOGITO-3517: Stunner: InlineEditor Keyboard events are triggering shortcuts in VSCode

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/reassignment/ReassignmentValue.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/ReassignmentValueTest.java

**JIRA**: [JBPM-9432](https://issues.redhat.com/browse/JBPM-9432)
**Business Central**: [WAR file](https://drive.google.com/file/d/1OAc5b5NH4W3re5MUDhADsv7nu612ZYI1/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1pdEBMzPv52dVcg48jUzV2pVti0aY2Fau/view?usp=sharing)
<details>
<summary>
Hi @romartin, there is a fix for JBPM-9432, I tested showcase and full downstream build (I uploaded it to drive as well, see link above) and I also tested and uploaded a VS code plugin and all works good now as well.
All important checks are green, PR is ready for review. Thank you!
@LuboTerifaj, @domhanak tester is not set, but I am not sure what is the procedure now, so I will add you both to the PR. Thank you!
</summary>
* Retest …

JBPM-9432: Users and Groups reversed for Reassignment property

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/dataio/AssignmentsInfo.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/AssociationDeclaration.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/DeclarationList.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/ParsedAssignmentsInfo.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/AssociationDeclarationTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/properties/ActivityPropertyWriterTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/tostunner/properties/ParsedAssignmentsInfoTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/tasks/UserTaskTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/multipleDefinitionsUserTask.bpmn
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationDeclaration.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/ParsedAssignmentsInfo.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationDeclarationTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/ActivityPropertyReaderTest.java

**JIRA**: [JBPM-9254](https://issues.redhat.com/browse/JBPM-9254)
**Business Central**: [here](https://drive.google.com/file/d/1jH__H8IhyHAhXlLWnqtqmL55wJ-omdU2/view?usp=sharing)
**VS Code**: [here](https://drive.google.com/file/d/1l292hIuhDJQwMdv-DIzm9d0_nZUBbHjD/view?usp=sharing)
<details>
<summary>
Hi @romartin, there is a fix for the jira, I tested it with business central and I can't reproduce it anymore. See details under the cut.
</summary>
<br>
<b>A side effect</b>: now if user will manually declare twice the same variable like `userVar[String]->processVar` all duplicates will be removed. But it won't remove variables if only one or two of tree parts (variable name, variable type, variable association) are the same, like `userVar[String]->processVar1` and …

JBPM-9254 Stunner - BPMN Editor freezes in business central

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/converters/InputClausePropertyConverter.java

**JIRA**: https://issues.redhat.com/browse/KOGITO-3366
<details>
<summary>
During DMN file unmarshalling, `inputValues`, in order to be editable, should not be null.
</summary>
</details>

[7.44.x] KOGITO-3366: [DMN Designer] Boxed Expression - Decision Tables - Users lost constraints when they change the focus 

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/wizard/NewContainerWizard.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/wizard/NewContainerWizardTest.java

**JIRA**: [JBPM-9393](https://issues.redhat.com/browse/JBPM-9393)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

JBPM-9393 'Add Deployment unit' Fields are missing while creating new

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java

**JIRA**: [DROOLS-5749](https://issues.redhat.com/browse/DROOLS-5749) - [DMN Designer] Multiple DRDs support - When users open a DMN with duplicated information requirements, the marshaller doesn't fix it
**Business Central**: [WAR file](https://www.dropbox.com/s/toe10dnah6sgduw/business-central-DROOLS-5749.war?dl=0)
**VS Code**: [plugin](https://www.dropbox.com/s/4auffyl3phrvvlb/vscode-plugin-DROOLS-5749.vsix?dl=0)
<details>
<summary>
</summary>
</details>

DROOLS-5749: [DMN Designer] Multiple DRDs support - When users open a DMN with duplicated information requirements, the marshaller doesn't fix it

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-5664
*How it works*:
1. When the diagram is loaded (and the unmarshaller part already executed), this method gets called, in order to store the original diagram hash.
2. When closing the diagram session, this method checks if the session can be closed or not by comparing the original diagram hash, with the current one:
2.1. if they are different (the method super.mayClose(getCurrentDiagramHash()) returns false), the "unsaved changes" modal is displayed.
*Provided solution*:
Several operations may happen before the diagram is drawn (for example element wrapping, etc.), so it is recommended to compute and store che original diagram hash after the diagram gets loaded (inspired by [kie-wb-common-stunner-kogito-client](https://github.com/kiegrou …

DROOLS-5664 DMN editor reporting unsaved changes in DMN files after no changes

---

kie-identity-session-provider/pom.xml
kie-identity-session-provider/src/main/java/org/kie/provider/SessionInfoProvider.java
kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeIdentityProvider.java
kie-identity-session-provider/src/main/java/org/kie/provider/impl/SafeSessionInfoProvider.java
kie-identity-session-provider/src/main/resources/META-INF/ErraiApp.properties
pom.xml

https://issues.redhat.com/browse/DROOLS-5783
Description:
The goal of this PR is to cleanup `droolsjbpm-integration` repo from unnecessary relation with other repos (in this case `appformer`). It is a sort of followup of this PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505 that tries to do the same but it has been partially reverted because of some remaining usages
Details of this part of the PR:
- moving `kie-identity-session-provider` from `droolsjbpm-integration` repo to here because it is used by some -wb repos but it uses kie-internal so this is the first repo in common we can use
NOTE: I preserved same group and artifact of `kie-identity-session-provider` to preserve downstream usages. If we don't like to have a different naming I can change it + all …

[DROOLS-5783] Make droolsjbpm-integration repo independent from appformer

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-5664
*How it works*:
1. When the diagram is loaded (and the unmarshaller part already executed), this method gets called, in order to store the original diagram hash.
2. When closing the diagram session, this method checks if the session can be closed or not by comparing the original diagram hash, with the current one:
2.1. if they are different (the method super.mayClose(getCurrentDiagramHash()) returns false), the "unsaved changes" modal is displayed.
*Provided solution*:
Several operations may happen before the diagram is drawn (for example element wrapping, etc.), so it is recommended to compute and store che original diagram hash after the diagram gets loaded (inspired by [kie-wb-common-stunner-kogito-client](https://github.com/kiegrou …

[7.44.x] DROOLS-5664 DMN editor reporting unsaved changes in DMN files after no changes

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasConnectorNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteElementsCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNSafeDeleteNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNDeleteConnectorCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionTargetNodeCommand.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/util/ContentDefinitionIdUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/session/DMNCanvasHandler.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasConnectorNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/canvas/DMNDeleteCanvasNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNDeleteConnectorCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionSourceNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/factory/graph/DMNSetConnectionTargetNodeCommandTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/util/ContentDefinitionIdUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/command/DeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/DeleteConnectorCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SafeDeleteNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SetConnectionSourceNodeCommand.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SetConnectionTargetNodeCommand.java

**JIRA**: [KOGITO-3364](https://issues.redhat.com/browse/KOGITO-3364)
Merged: https://github.com/kiegroup/kie-wb-common/pull/3447
<details>
<summary>
</summary>
</details>

[7.44.x] [DMN Designer] Multiple DRDs support - When a node is deleted in the DRG, undo/redo operations do not work properly

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/included/DMNMarshallerImportsService.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/DMNUnmarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnector.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeEntriesFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/KOGITO-3696 (DMN model without DMNDI - expected).xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/KOGITO-3696 (DMN model without DMNDI - fixture).xml

**JIRA**: [KOGITO-3696](https://issues.redhat.com/browse/KOGITO-3696): DMN Editor regression failing display edge when xml missing DMNDI
**VS Code**: [plugin](https://www.dropbox.com/s/x1vsvyzlommqd3d/plugin-KOGITO-3696.vsix?dl=0)
**Asset to test the PR**: [canDrink.dmn](https://issues.redhat.com/secure/attachment/12500383/canDrink.dmn)
<details>
<summary>
</summary>
</details>

KOGITO-3696: DMN Editor regression failing display edge when xml missing DMNDI

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/AbstractDiagramEditorCore.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java

This reverts https://github.com/kiegroup/kie-wb-common/pull/3468 as it breaks the `AbstractProjectDiagramEditorTest` tests.

Revert "DROOLS-5737: [DMN Designer] change in Decision Navigator does not dirty context (#3468)"

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/reassignment/ReassignmentValue.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/ReassignmentValueTest.java

Hi @romartin, @LuboTerifaj, @domhanak this is cherry-pick of https://github.com/kiegroup/kie-wb-common/commit/e032b472a404245dd149aaf6e205431dd56fb6ed I compiled it locally with 7.44.x and it works good. I didn't attach VS Code plugin, since if I correct there will be no Kogito releases from this branch. Thank you!
**JIRA**: [RHPAM-3244](https://issues.redhat.com/browse/RHPAM-3244)
**Business Central**: [business-central-7.44.1-SNAPSHOT-wildfly19-RHPAM-3244.war](https://drive.google.com/file/d/1GrIEGSIvC5xhF3KkTUG2YDNfa6hIlEFN/view?usp=sharing)
**VS Code**: not applicable
<details>
<summary>
</summary>
* A compile downstream build: <b>jenkins do …

[7.44.x] RHPAM-3244 - Stunner - Users and Groups reversed in resulted file for Reassignment property

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/BaseProjectImportService.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImplTest.java

**AF-2540**: [AF-2540](https://issues.redhat.com/browse/AF-2540)
**RHDM-1407**: [RHDM-1407](https://issues.redhat.com/browse/RHDM-1407)
- During importing a project, the repo is now cloned temporarily cloned into the system folder and deleted when the branches and other details are fetched from it.
- In this way, Business central always gets a new copy and hence able to see new changes in subsequent imports. 
- Due to this user can now see the new added branches when a project is reimported again (RHDM-1407) 
<details>
<summary>
</summary>
* A full …

AF-2540: Issue re-importing a repository initially created by importing an empty repository in Business Central

---

kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/BaseProjectImportService.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/main/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImpl.java
kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-backend/src/test/java/org/kie/workbench/common/screens/examples/backend/server/ProjectImportServiceImplTest.java

(cherry picked from commit a727da4a504540399767c47d26a776118a488c13)
**AF-2540**: [AF-2540](https://issues.redhat.com/browse/AF-2540)
backport for https://github.com/kiegroup/kie-wb-common/pull/3492
<details>
<summary>
</summary>
</details>

[backport-7.44.x] AF-2540: Issue re-importing a repository initially created by importing an empty repository in Business Central

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSession.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSessionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeViewTest.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/AbstractDiagramEditorCore.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java

The original PR was already tested and merged, but it have some test issues (we didn't waited for the green build).
Then the original PR was reverted.
And this is just the "revert of the revert" with the fixed tests. There's really nothing to test, just asking for @jstastny-cz and @vpellegrino to take a look to see if is ok to merge.
Now we have a green.
ORIGINAL PR MERGED: https://github.com/kiegroup/kie-wb-common/pull/3468
<details>
<summary>
</summary>
</details>

Revert "Revert "DROOLS-5737: [DMN Designer] change in Decision Navigator does not dirty context"

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNDeleteNodeToolboxActionTest.java

<details>
<summary>
</summary>
</details>

Fix failing test in DMNDeleteNodeToolboxActionTest

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeEntriesFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/backward/compatibility/dmn13-expected/0082-feel-coercion.dmn
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/backward/compatibility/dmn13-expected/0085-decision-services.dmn
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/backward/compatibility/dmn13-expected/0087-chapter-11-example.dmn
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/backward/compatibility/dmn13-expected/0088-no-decision-logic.dmn
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/KOGITO-2515 (DMN model with decision services - expected).xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/KOGITO-2515 (DMN model with decision services - fixture).xml

**JIRA**: [KOGITO-2515](https://issues.redhat.com/browse/KOGITO-2515)
This issue is caused due the order of the `DMNShape` nodes in the .dmn files. If the Decision Service is before its children nodes, then it works. Otherwise it happens the scenario described in the JIRA (nodes in wrong position).
This PR ensure that all the Decision Nodes are positioned first when unmarshalling despite the order in the .dmn file.
<details>
<summary>
</summary>
</details>

[KOGITO-2515] DMN Editor decision service wrong layout

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-api/src/main/java/org/kie/workbench/common/screens/server/management/service/ContainerService.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/service/ContainerServiceImpl.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/service/ContainerServiceImplTest.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerView.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/resources/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.properties
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenterTest.java

…e to stop it.
**JIRA**: [JBPM-8153](https://issues.redhat.com/browse/JBPM-8153)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2326
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

JBPM-8153 Container is removed from UI even though it was not possible to stop it.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditBusinessKnowledgeModelToolboxAction.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditDecisionToolboxAction.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/factories/DecisionNavigatorNestedItemFactory.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditBusinessKnowledgeModelToolboxActionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/toolbox/DMNEditDecisionToolboxActionTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/factories/DecisionNavigatorNestedItemFactoryTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeViewTest.java

KOGITO-3905: DMN readonly mode allows clear of decision expression
KOGITO-3906: DMN readonly mode allows changes in Decision Navigator panel
**JIRA**: [KOGITO-3905](https://issues.redhat.com/browse/KOGITO-3905)
**JIRA**: [KOGITO-3906](https://issues.redhat.com/browse/KOGITO-3906)
<details>
<summary>
</summary>
</details>

KOGITO-3905: DMN readonly mode allows clear of decision expression

---

kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/list/ConversionMessageWidget.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/list/ConversionMessageWidget.ui.xml
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/list/MessageType.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/list/PopupListWidget.java
kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/popups/list/PopupListWidget.ui.xml

DROOLS-5807 : GDST to XLS conversion should not convert dialect column
Moving few classes from drools-wb so they can be used by both GDST->XLS and XLS-GDST conversion.
**JIRA**: [DROOLS-5807](https://issues.redhat.com/browse/DROOLS-5807)
**JIRA**: [DROOLS-5808](https://issues.redhat.com/browse/DROOLS-5808)
* https://github.com/kiegroup/kie-wb-common/pull/3495
* https://github.com/kiegroup/drools-wb/pull/1443
<details>
<summary>
</summary>
</details>

DROOLS-5808 : XLS to GDST conversion should ensure types work

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ConnectionAcceptorControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ConnectionAcceptorControlImplTest.java

Model was not being updated after changes were made to the sequence flow.
**JIRA**: [KOGITO-3998](https://issues.redhat.com/browse/KOGITO-3998)
**Business Central**: [WAR file](https://drive.google.com/file/d/1JHgi6W8A3LkALKb64LMSpqcOcBdMhuIs/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1VxptH083cAxu87CXMJ_YdldbE_6WhA3n/view?usp=sharing)

KOGITO-3998 - It's not possible to save arrow edits

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java

Hey @romartin, @inodeman: Please, could you review this PR?
**JIRA**: [JBPM-9511](https://issues.redhat.com/browse/JBPM-9511)
**JIRA**: [RHPAM-3350](https://issues.redhat.com/browse/RHPAM-3350)
**Business Central**: [WAR file](https://drive.google.com/file/d/1TUPhhuz-EwiIOnklK8Mlgi6lt55pRUef/view?usp=sharing)
**VS Code**: [extension_pack_kogito_kie_editors](https://drive.google.com/file/d/1-2j8Eol5aAZIK7SKKr8cXr4hFtNv7LJL/view?usp=sharing)

JBPM-9511: Stunner: Inline Editor doesn't show after morphing a Task to user Task

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/pom.xml

Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>
**JIRA**: (https://issues.redhat.com/browse/RHPAM-3393)
* https://github.com/kiegroup/drools-wb/pull/1454
**Business Central**: n/a
**VS Code**: n/a
<details>
<summary>
</summary>
</details>

Remove Kogito profile to productize required components

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.html
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java

For easier testing of KOGITO-3909 we add some OuiaAttributes into Dmn Data Types list
For more details see: https://issues.redhat.com/browse/KOGITO-3909
- https://github.com/kiegroup/appformer/pull/1090
Prerequisite for:
- https://github.com/kiegroup/kogito-tooling/pull/372

KOGITO-3909: Add OuiaAttributes to Data Type entry

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandalone.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandaloneTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/common/IdUtils.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnector.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/common/IdUtilsTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java

DMN marshallers/unmarshaller were not prepared to handle auto-magnets.
Those will be handled as Double.Nan values (<di:waypoint x="NaN" y="NaN" />).
**JIRA**: [DROOLS-5911](https://issues.redhat.com/browse/DROOLS-5911)
**Business Central**: [WAR file](https://drive.google.com/file/d/1TBt05A-cEfzXN5udnqrv7TLflBK-O_-B/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1o2oWp6z5pW5ObjT7lVciPgWXBqiySq8z/view?usp=sharing)

DROOLS-5911 - It's not possible to save arrow edits on DMN Editor

---

kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-core/src/test/projects/dummy_deps_complex/dummyB/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-maven-plugins-testing/src/test/projects/dummy_deps_complex/dummyB/pom.xml
kie-wb-common-services/kie-wb-common-services-backend/src/test/projects/dummy_deps_complex/dummyB/pom.xml

Use 'version.com.fasterxml.jackson.databind' from https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml to fix issue reproted by dependabot
For more details see: https://issues.redhat.com/browse/AF-2795
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* A full production …

AF-2795: use managed jackson-databind version

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/wildfly-multinode-kie-server.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditor.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/resources/org/kie/workbench/common/stunner/kogito/KogitoBPMNEditor.gwt.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/test/java/org/kie/workbench/common/stunner/kogito/client/editor/BPMNDiagramEditorTest.java

**JIRA**: 
https://issues.redhat.com/browse/KOGITO-3846
* https://github.com/kiegroup/appformer/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/3538
* https://github.com/kiegroup/kogito-tooling/pull/374
**Details:**
This PR adds the Notification API that let GWT send notifications to Channels. There are two main notifications: Alerts and Problems. 
* Alerts: ephemeral notification, i.e: Popup. If the notification contains a non empty path it will display a button to open that path. Alerts severity can be INFO, ERROR or WARNING.
* Problems: Notifications that needs to be informed to the users an keep persisted until the problem is fixed. i.e: Problems tab in VSCode. Problems severity can be INFO, …

KOGITO-3846: Added Notifications API to Editors

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/ActivityDataIOEditorViewImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/ActivityDataIOEditorWidget.html
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValues.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValuesTest.java

Hi @romartin, @domhanak,
I found a root cause. It wasn't the second edit or dot. The issue was in long names. When user added new value which was cut to allowed size, it never displayed "Edit" prefix. Now the issue is fixed and also I expanded combobox as well so to test the fix you need to put a very long expression (66+ symbols).
As already mentioned I updated size of the dialogue as well:
I took the size of the most wide existing property editor (Notifications property of User Task), so the size should be OK, since we never got any complains that editor was too wide. I think it should be enough for most of the cases now, please let me know if more size fixes are required.
**JIRA**: [KOGITO-4328](https://issues.redhat.com/browse/KOGITO-4328)
**Business Central**: …

KOGITO-4155: BPMN Editor - Cannot properly edit Expressions in the Data Assignments

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/expressions/types/dtable/AddOutputClauseCommandTest.java

Due to recent jdk11 support [1] introduced on master we should re-enable few tests [2] not working on jdk 11 previously.
[1] - https://issues.redhat.com/browse/AF-1799
[2] - https://issues.redhat.com/browse/AF-2797
**JIRA**: [AF-2797](https://issues.redhat.com/browse/AF-2797)
No referenced PR
<details>
</details>

AF-2797: Reenable kie-wb-common-dmn tests on jdk 11

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/shapes/bpmn-shapes.css
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/shapes/subprocess.svg

**JIRA**: [JBPM-9598](https://issues.redhat.com/browse/JBPM-9598)
**Business Central**: [tbd](https://donwnload.here/something)
**Standalone version**: [Standalone Editor](https://drive.google.com/file/d/1rt7tpDEfs4sAhLkXwzBmtFr_6_dvZvCZ/view?usp=sharing)
Hi @romartin, @LuboTerifaj, @lazarotti, @lclay2 I made the line bold to follow the spec. However spec doesn't declare how bold should it be. Anyway there is the change, I changed it from 1.5 to 5 pixels (other activities still has 1.5 so you can compare), please tell me if you want to try different sizes or 5 pixels is ok.
To try on your own please download standalone version unzip and open index.html in any browser.
Thank you!
<details>
<summary>
</summary>
* Retest PR: <b>jenkins …

JBPM-9598 - Reusable Subprocess / Call Activity borders does not follow spec

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/EventPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/EventPropertyWriterTest.java

The Structure Ref was changed only when it was empty (when the event had no data ouput).
So after setting it one time, it was not possible to change it anymore.
Now it is possible to clear the value and change it whenever.
**JIRA**: [KOGITO-3932](https://issues.redhat.com/browse/KOGITO-3932)
_This issue does not apply to Business Central, but anyway the artifact is available for any cross-testing._
**Business Central**: [WAR file](https://drive.google.com/file/d/1POW3FP-U3nupKltMG48WOw3dn9WlRhV7/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1Sbap7t83OfYZpyZ6uIxDyT1fom7znaLR/view?usp=sharing)

KOGITO-3932 - Stale itemDefinition after update of Intermediate Message Catch Event

---

kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/main/java/org/kie/workbench/common/services/verifier/reporting/client/panel/IssuePresenter.java
kie-wb-common-services/kie-wb-common-verifier/kie-wb-common-verifier-reporting-client/src/test/java/org/kie/workbench/common/services/verifier/reporting/client/panel/IssuePresenterTest.java

**JIRA**: [DROOLS-5960](https://issues.redhat.com/browse/DROOLS-5960)
This is a complementary PR to have report with sorted line numbers. Imagine there is missing range on lines 1, 2 and 3. Before this PR report contained item:
```
3, 2, 1 - Missing range
```
After this PR
```
1, 2, 3 - Missing range
```
* https://github.com/kiegroup/drools-wb/pull/1457/files
* https://github.com/kiegroup/drools/pull/3333/files

DROOLS-5960: Sort lines of Validation&Verification report

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandalone.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/DMNMarshallerStandaloneTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/common/IdUtils.java

**JIRA**: [KOGITO-4500](https://issues.redhat.com/browse/KOGITO-4500)
This PR fixes a small issue we introduced [here](https://github.com/kiegroup/kie-wb-common/pull/3540).
If we create a model with AUTO-SOURCE or AUTO-TARGET connections and we try to execute it (like this: [learn-dmn-in-15-minutes.com/learn/execution](https://learn-dmn-in-15-minutes.com/learn/execution)) the validation fails, and we can't execute the model.
With this change, users can successfully execute and use AUTO-SOURCE or AUTO-TARGET connections.
**VS Code**: [plugin before this PR](https://www.dropbox.com/s/2o8g1c2y3bm8wop/KOGITO-4500-before.vsix?dl=0) -- [plugin after this PR](https://www.dropbox.com/s/ze4wvpber34jusz/KOGITO-4500-after.vsix?dl=0)
<details>
<summary>
How to retest this PR or trigger a specific …

KOGITO-4500: [DMN Designer] DMN schema/model validation errors when model has AUTO-SOURCE or AUTO-TARGET connections

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-api/src/main/java/org/kie/workbench/common/screens/server/management/service/ContainerService.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/service/ContainerServiceImpl.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/service/ContainerServiceImplTest.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenter.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/container/ContainerView.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/java/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/resources/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants.properties
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/ContainerPresenterTest.java

…e to stop it.
**JIRA**: [JBPM-8153](https://issues.redhat.com/browse/JBPM-8153)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2386
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

[7.48.x]JBPM-8153 Container is removed from UI even though it was not possible to stop it.

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/JavaTypeSystemTranslator.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/JavaTypeSystemTranslatorTest.java

**JIRA**: [DROOLS-6033](https://issues.redhat.com/browse/DROOLS-6033)
* https://github.com/kiegroup/kie-soup/pull/178
* https://github.com/kiegroup/kie-wb-common/pull/3566
<details>
<summary>
</summary>
</details>

DROOLS-6033 : LocaldateTime guided rule presents it incorrectly.

---

kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/main/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/JavaTypeSystemTranslator.java
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/builder/projects/JavaTypeSystemTranslatorTest.java

(cherry picked from commit 00dd1d5469c1f475830dec69c604298ee6b45bcf)
**JIRA**: [DROOLS-6033](https://issues.redhat.com/browse/DROOLS-6033)
* https://github.com/kiegroup/kie-soup/pull/185
* https://github.com/kiegroup/kie-wb-common/pull/3585
<details>
<summary>
</summary>
</details>

[7.48.x] DROOLS-6033 : LocaldateTime guided rule presents it incorrectly.

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenter.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/DecisionNavigatorPresenterTest.java

**JIRA**: [KOGITO-4539](https://issues.redhat.com/browse/KOGITO-4539): [DMN Designer] DMN takes too long to open models with too many nodes
Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/3578
--
**- Business Central war (7.48.x)**: [war file](https://www.dropbox.com/s/urwzxb1h2pdtmdr/KOGITO-4539-7.48.x-business-central.war?dl=0)
**- VS Code plugin (7.48.x)**: [plugin file](https://www.dropbox.com/s/4kjegh5fwp6qqrh/KOGITO-4539-7.48.x-vscode.vsix?dl=0)
--
<details>
<summary>
</summary>
* An upstream build: <b>jenkins …

[7.48.x] KOGITO-4539: [DMN Designer] DMN takes too long to open models with too many nodes

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ProcessPropertyWriter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ProcessPropertyWriterTest.java

Process IDs containing the character "-" will be serialized with the character "_" instead.
Process-test will be serialized as process_test, for example.
**JIRA**: [KOGITO-4078](https://issues.redhat.com/browse/KOGITO-4078)
**Business Central**: Does not apply.
**VS Code**: [plugin](https://drive.google.com/file/d/1PYWB9xxEJaNF_P6yOUxvHFwuncR3Tk6p/view?usp=sharing)

KOGITO-4078 - Creating a new process with "-" in VSCode generates incorrect Process ID

---

kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/resources/StunnerCommonIconsGlyphFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/resources/i18n/StunnerProjectClientConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/util/GraphUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/util/GraphUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-api/src/main/java/org/kie/workbench/common/stunner/bpmn/project/service/ProjectOpenReusableSubprocessService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/ProjectOpenReusableSubprocessServiceImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/project/backend/service/ProjectOpenReusableSubprocessServiceImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/canvas/controls/BPMNProjectActionsToolboxFactory.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/resources/BPMNClientConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/service/ClientProjectOpenReusableSubprocessService.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/java/org/kie/workbench/common/stunner/bpmn/project/client/toolbox/OpenSubprocessToolboxAction.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/project/client/resources/i18n/BPMNClientConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/canvas/controls/BPMNProjectActionsToolboxFactoryTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/project/client/toolbox/OpenSubprocessToolboxActionTest.java

**JIRA**: [[BPMN] Open subprocesses in a new editor (BC only)](https://issues.redhat.com/browse/JBPM-9597)
**Business Central**: [WAR](https://drive.google.com/file/d/1MvUFmtmZWH0Mkq-zHPFYyWxKTCbX3jAm/view?usp=sharing)
**VS Code**: [VSIX](https://drive.google.com/file/d/1W2uR_P-wqx3UxLq4lTQmwRTfK_bpAcOq/view?usp=sharing)
<details>
<summary>
Hi @romartin, @LuboTerifaj, what is done:
* Toolbox button for Reusable sub-process with tool-tip to open Sub-process in Business Central only
* Error notifications
* Sub-process ID is empty
* Sub-process not found
* Open processes by click on the toolbox button, tested for different projects and space as well
* Found a bug that Business Central doesn't update breadcrumbs for spaces/projects, only for process name. I think it is not related to my …

JBPM-9597 - [BPMN] Open subprocesses in a new editor (BC only)

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/workitem/WorkItemDefinitionCacheRegistry.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/workitem/WorkItemDefinitionCacheRegistryTest.java

**JIRA**: [JBPM-9683](https://issues.redhat.com/browse/JBPM-9683)
**Business Central**: [WAR file](https://drive.google.com/file/d/1E_ckj-NpGnp1WJzdvfchgFd-tEOPMwh1/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1svUr2l-gcPdceJaacJIKW8dLMJgSlGm7/view?usp=sharing)
<details>
<summary>
Hi @romartin, @LuboTerifaj,
issue was caused by [this](https://github.com/kiegroup/kie-wb-common/pull/3552/files#diff-f39797a981aba47d2779b5819ef65ab2767d6314f7c14828b645de0b73f74242R39) refactoring. There is the fix, issue is caused by HashMap$Values which doesn't have empty constructor and that's why it can't be initialized during CDI work by Errai. The fix replacing HashMap$Values by ArrayList and now it works as expected.
I think there are no sense to write unit tests to check type …

JBPM-9683 BPMN editor [Business Central]: Work Items not available

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java

**JIRA**: [RHDM-1650](https://issues.redhat.com/browse/RHDM-1650)
**Business Central**: [WAR file](https://drive.google.com/file/d/1a-J-Eh47huKeP0MWpe8NQuJi5NyzAlkc/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1M57RvF9FrucO81GIBuxaa34x_AO6zSN0/view?usp=sharing)
Hi @jomarko, @karreiro, @romartin this is a cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/3604.
VS Code plugin TBD, checking which branch should be used to build Kogito-tooling for 7.52.x. 
Thank you!
<details>
<summary>
</summary>
* …

[7.52.x] JBPM-9695 - DMN - Data Types shortcuts do not work anymore

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/resources/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/util/StringUtils.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/test/java/org/kie/workbench/common/stunner/core/util/StringUtilsTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/validation/BPMNDataObjectValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/validation/BPMNDataObjectClientValidator.java

**JIRA**: [JBPM-9242](https://issues.redhat.com/browse/JBPM-0000)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

[7.52.x] RHPAM-3250: Stunner - Not all illegal characters are removed from Data Object name

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorOptions.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorOptionsTest.java

Hi @romartin can you review this PR? Uploading artifact shortly
JBPM-9689 : Script Editor - Remove use of minimap
**JIRA**: [JBPM-9689](https://issues.redhat.com/browse/JBPM-9689)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

[7.52.x] JBPM-9689 : Script Editor - Remove use of minimap

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java

**JIRA**: [JBPM-9695](https://issues.redhat.com/browse/JBPM-9695)
**Business Central**: [WAR file](https://drive.google.com/file/d/15U_1fxYGVGkSBKTTQnjT7pJJZDdtCUDx/view?usp=sharing)
**VS Code**: [plugin](https://drive.google.com/file/d/1fj9pKYvwAD74al4StaPH0suolOVtaYb4/view?usp=sharing)
<details>
<summary>
Hi @jomarko, @karreiro, @romartin, there is a fix for shortcuts.
Just to double check: I build VS Code extension in this way:
* `mvn clean install -DskipTests -Dgwt.compiler.skip` under `kie-wb-common/kie-wb-common-dmn`
* `mvn clean install` under `kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime`
* `export EXTERNAL_RESOURCE_PATH__dmnEditor=$KIEGROUP/kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/target/kie-wb-common-dmn-webapp-kogito-runt …

JBPM-9695 - DMN - Data Types shortcuts do not work anymore

---

kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/main/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-project-client/src/test/java/org/kie/workbench/common/dmn/project/client/editor/DMNDiagramEditorTest.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/AbstractSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultViewerSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/impl/ManagedSession.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultEditorSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/impl/DefaultViewerSessionTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/impl/ManagedSessionTest.java

Hey  @karreiro @jomarko 
Here is the fix for https://issues.redhat.com/browse/RHDM-1647
I've properly tested kogtio and BC, and both look good to me. In fact in kogtio the issue was not being exposed, user didn't notice about it, although it was some memory leak there anyway, but now everything ok!! :tada: 
Please the deadline for this PR is this Fri, would appreciate en **early review (targeting RHPAM 7.11)**.
Thanks in advance!

[7.52.x] RHDM-1647: DMN - Reopened diagram with DRDs can not be edited

---

kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-api/src/main/java/org/kie/workbench/common/forms/jbpm/service/bpmn/util/BPMNVariableUtils.java
kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-api/src/test/java/org/kie/workbench/common/forms/jbpm/service/bpmn/util/BPMNVariableUnitsTest.java

* Added required and readonly properties to generate variable property
(cherry picked from commit 2199c2b0c102db24053661d3f34ca61a04dcae59)
**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)
Original PR: https://github.com/kiegroup/kie-wb-common/pull/3592
<details>
<summary>
</summary>
</details>

AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java
kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/service/BuildServiceHelper.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/service/BuildServiceHelperTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/screens/ProjectMessagesListener.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/screens/ProjectMessagesListenerTest.java

(cherry picked from commit 93be73cf5bd57f9ace5728635ec16b20641bebf0)
**RHPAM-2647:**: https://issues.redhat.com/browse/RHPAM-2647
original PR: https://github.com/kiegroup/kie-wb-common/pull/3546
<details>
<summary>
</summary>
</details>

[backport-7.52.x] RHPAM-2647 : [GSS](7.z) Errors when building a project are shown to all users

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorOptions.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorOptionsTest.java

JBPM-9689 : Script Editor - Remove use of minimap
**JIRA**: [JBPM-9689](https://issues.redhat.com/browse/JBPM-9689)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

JBPM-9689 : Script Editor - Remove use of minimap

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml

Cherry-pick _only_ the BanDuplicateClasses fix from https://github.com/kiegroup/kie-wb-common/pull/3611 to `7.52.x`.
**JIRA**: [DROOLS-6306](https://issues.redhat.com/browse/DROOLS-6306): JDK 11 build fails on Enforcer Error BanDuplicateClasses in kie-wb-common-dmn-webapp-kogito-runtime
<details>
<summary>
</summary>
</details>

[7.52.x] DROOLS-6306: JDK 11 build fails on Enforcer Error BanDuplicateClasses in kie-wb-common-dmn-webapp-kogito-runtime

---

kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/main/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenter.java
kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/src/test/java/org/kie/workbench/common/screens/datamodeller/client/DataModelerScreenPresenterTest.java

Source content was not being parsed on server, this fixes the problem.
**JIRA**: [JBPM-9715](https://issues.redhat.com/browse/JBPM-9715)
**JIRA**: [RHPAM-3544](https://issues.redhat.com/browse/RHPAM-3544)
* https://github.com/kiegroup/kie-wb-common/pull/3629

JBPM-9715 - Data Object editor removes imports when saving

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/shape/def/CustomTaskShapeDef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/shape/def/CustomTaskShapeDefTest.java

If an item could not be found in the workiItemDefinitionRegistry a null exception was thrown interrupting the load process.
**JIRA**: [RHPAM-3606](https://issues.redhat.com/browse/RHPAM-3606)
* https://github.com/kiegroup/kogito-editors-java/pull/36
**Business Central**: [WAR file - Not generated yet](https://donwnload.here/something)

RHPAM-3606 - Unknown Custom tasks in Designer makes Diagram Explorer empty

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/AbstractSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControl.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControlTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsCanvasSessionHandler.java

Hi @romartin can you review this PR? As discussed, this one from Kogito also needs to be in BC
**JIRA**: [KOGITO-4935](https://issues.redhat.com/browse/KOGITO-4935)
* link 2
* link 3 etc.
**Business Central**: [WAR file]https://drive.google.com/drive/folders/1V4LWrANzCpVTB9RCAgBLGi-LuWx_fXqV?usp=sharing
<details>
<summary>
</summary>
* An upstream build: <b>jenkins …

KOGITO-4935 : [DMN/BPMN editor] Sometimes clicking outside doesn't unselect nodes

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/LibraryPreferences.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferences.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/test/java/org/kie/workbench/common/screens/library/api/preferences/LibraryPreferencesTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/test/java/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferencesTest.java

When running in SUPER DEV MODE calls to System.getProperty using Constants cause GWT Compilation to fail causing the showcases to not load. This is a safe way to call it without breaking the showcases.
**JIRA**: [JBPM-9750](https://issues.redhat.com/browse/JBPM-9750)
**Business Central**: [WAR file](https://drive.google.com/file/d/11iPpccSxwtOpnuARdsWnw3AOUnHO4yCT/view?usp=sharing)

JBPM-9750 - Stunner BPMN Project Showcase and JBPM WB Showcase do not run

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnector.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java

**JIRA**: [KOGITO-5003](https://issues.redhat.com/browse/KOGITO-5003)
This is the backport for kie-wb-common of https://github.com/kiegroup/kogito-editors-java/pull/52
<details>
<summary>
</summary>
</details>

KOGITO-5003: DMN editor removing edges for duplicate Decision Nodes on canvas

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/container/status/ContainerRemoteStatusPresenterTest.java

For more details see:
- https://issues.redhat.com/browse/DROOLS-6436
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

DROOLS-6436: Fix failing ContainerRemoteStatusPresenterTest

---

kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImplTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/PackageDataModelOracleCEPCompletionsTest.java
kie-wb-common-widgets/kie-wb-common-ui/src/test/java/org/kie/workbench/common/widgets/client/datamodel/PackageDataModelOracleCompletionsTest.java

(cherry picked from commit 5c4563d7533cc9eefcad61e9e7387f1c36ffc3f1)
**JIRA**: 
[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)
**referenced Pull Requests**:
* https://github.com/kiegroup/kie-soup/pull/194
* https://github.com/kiegroup/drools/pull/3689
* https://github.com/kiegroup/kie-wb-common/pull/3620
* https://github.com/kiegroup/drools-wb/pull/1483
<details>
<summary>
</summary>
</details>

[7.52.x] DROOLS-6268 : Guided Rule Editor: Add memberOf and not memberOf operators

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnector.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java

This is cherry-pick from 
https://github.com/kiegroup/kie-wb-common/pull/3645
https://github.com/kiegroup/kogito-editors-java/pull/52
<details>
<summary>
</summary>
</details>

[7.52.x] KOGITO-5003: DMN editor removing edges for duplicate Decision Nodes on canvas

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/LibraryPreferences.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferences.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/test/java/org/kie/workbench/common/screens/library/api/preferences/LibraryPreferencesTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/test/java/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferencesTest.java

This is just a backport for 7.52.x branch.
AF-8224: https://github.com/kiegroup/kie-wb-common/pull/3623
JBPM-9750: https://github.com/kiegroup/kie-wb-common/pull/3641
**Merge this after #3656 backport is merged**
**JIRA**: 
[AF-2824](https://issues.redhat.com/browse/AF-2824)
[JBPM-9750](https://issues.redhat.com/browse/JBPM-9750)

AF-2824 - JBPM-9750 - Showcase fix and invalid values check

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/main/java/org/kie/workbench/common/screens/server/management/backend/KieServerStandaloneControllerProducer.java
kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/src/test/java/org/kie/workbench/common/screens/server/management/backend/KieServerStandaloneControllerProducerTest.java

This allows wss:// as well as ws:// connections
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

Allow Secure Web Socket connections to standalone controllers

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/customproperties/VariableDeclarationTest.java

**JIRA**: [JBPM-9822](https://issues.redhat.com/browse/JBPM-9822)
* https://github.com/kiegroup/kie-wb-common/pull/3663
<details>
<summary>
</summary>
</details>
This change should have been added in the pull request linked above, but it was merged sooner than expected. Therefore here is the separate pull request for the change.

JBPM-9822: Change test method name

---

.github/pull_request_template.md

Hi @mbiarnes, @romartin, I removed VS Code plugin mentioning from the template, since this repo doesn't contain VS Code related code anymore.
Thank you!
<details>
<summary>
</summary>
</details>

Remove VSCode plugin reference from new PR request

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpView.html
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenterTest.java

* if the default template is included for a space checkbox will be active.
**JIRA**: 
[AF-2891](https://issues.redhat.com/browse/AF-2891)
[BAPL-1902](https://issues.redhat.com/browse/BAPL-1902)
<details>
<summary>
</summary>
</details>

AF-2891 : Space's default archetype is not respected when creating a new project

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/resources/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants.properties
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/validation/BPMNReusableSubProcessValidator.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/validation/BPMNReusableSubProcessValidatorTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/validation/BPMNReusableSubProcessClientValidator.java

* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

[7.x] RHPAM-3480 : Error logged if reusable subprocess has some dataInput mapping but no dataOutput mapping in stunner

---

kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-svg/kie-wb-common-stunner-svg-gen/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/pom.xml

Hi @mareknovotny, @romartin, @domhanak,
I fixed the dependency, issue was when we compiling with JDK 11 for JDK 8 there are some collisions with XML API names. Since this dependency was used only for Stunner (according to comments into the POM) file, so I updated it directly without adding new dependencies.
Change is for SVG converters code so I just compiled and executed showcase for it, don't expect that Business Central will be any different from it. 
Thank you!
* https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766 …

JBPM-9896 - Fix dependency for compilation on JDK 11 to JRE 8

---

kie-wb-common-dmn/kie-wb-common-dmn-client/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-svg/kie-wb-common-stunner-svg-gen/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/pom.xml

Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685
<details>
<summary>
</summary>
</details>

[7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpView.html

**JIRA**: [AF-2668](https://issues.redhat.com/browse/AF-2668)
When creating a new project in BC, description is optional, therefore the asterisk is misleading - removed.
BEFORE
AFTER
<details>
<summary>
</summary>
</details>

AF-2668: Description is not mandatory

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml

(cherry picked from commit 4f3d828a26babdcd3c6d385daee0ab2bb6aa1cca)
<details>
<summary>
</summary>
</details>

[7.59.x] fix broken gwt:run for dmn-webapp-standalone

---

kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-api/src/main/java/org/kie/workbench/common/stunner/forms/model/ColorPickerFieldDefinition.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/fields/colorpicker/ColorPickerFieldRenderer.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/fields/colorpicker/ColorPickerWidget.html
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/fields/colorpicker/ColorPickerWidget.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/fields/colorpicker/ColorPickerFieldRendererTest.java
kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/test/java/org/kie/workbench/common/stunner/forms/client/fields/colorpicker/ColorPickerWidgetTest.java

For more details see:
- https://issues.redhat.com/browse/KOGITO-6036
This is a backport of:
- kiegroup/kogito-editors-java#147
For 7.x stream `ColorPickerDialog` can not be removed from codebase, as it is used in `appformer` project on other place.

KOGITO-6036: Use html <input type='color'> picker

---

kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClauseUnaryTests.java

This is backport of:
- https://github.com/kiegroup/kogito-editors-java/pull/152
<details>
<summary>
</summary>
</details>

RHPAM-3329: Increase Decision Table Output value length limit

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/events/IntermediateCatchEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/events/IntermediateCatchEventConverterTest.java

The shape was created while the base element ID was null.
The method execution order was changed to ensure the ID is set before use.
**JIRA**: [JBPM-9874](https://issues.redhat.com/browse/JBPM-9874)
**Business Central**: [WAR file](https://drive.google.com/file/d/1C0u_hQ7obj8ZNSZR1i10cRZG1YnPrzuI/view?usp=sharing)

JBPM-9874 - bpmndi:BPMNShape id of intermediateCatchEvent is always set to 'shape_null'

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/builder/core/Builder.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/builder/core/BuilderBatchResourceChangesTest.java

**JIRA**: [DROOLS-6739](https://issues.redhat.com/browse/DROOLS-6739)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be …

DROOLS-6739 : Inaccurate alert about duplicate rule name after copying rule

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/main/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/events/IntermediateCatchEventConverter.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/converters/fromstunner/events/IntermediateCatchEventConverterTest.java

The shape was created while the base element ID was null.
The method execution order was changed to ensure the ID is set before use.
**JIRA**: [RHPAM-3878](https://issues.redhat.com/browse/RHPAM-3878)
**Business Central**: [WAR file](https://drive.google.com/file/d/1Qx_2ci4foEW-Y3ntgcKJQ3r10bDcGOms/view?usp=sharing)

RHPAM-3878 - bpmndi:BPMNShape id of intermediateCatchEvent is always set to 'shape_null

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/pom.xml
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/validation/DMNDomainValidatorImpl.java
kie-wb-common-dmn/kie-wb-common-dmn-backend/src/test/java/org/kie/workbench/common/dmn/backend/validation/DMNDomainValidatorImplTest.java

**JIRA**: [DROOLS-6860](https://issues.redhat.com/browse/DROOLS-6860)
**Business Central**: [WAR file v2](https://drive.google.com/file/d/1R23tTEudOWYJmAenK-qTipoiF53B34ZH/view?usp=sharing)
<details>
<summary>
[DMN Designer] [BC Only] Validating a DMN invoking java function
</summary>
In the original issue by user, it was in fact two issues:
1. As specified in DMN specification, user must use full qualified name for classes AND generics is not supported
2. There was an issue in the `classloader` for DMN validation that was not loading classes created by user to validate the DMN models.
This PR fixes the issue number 2.
**For the full correction of the issue, tthis PR should be applied and the call in the Function in the DMN editor should be changed to:** …

DROOLS-6860: [DMN Designer] [BC Only] Validating a DMN invoking java function

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcess.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcessTest.java

**JIRA**: [KOGITO-6932](https://issues.redhat.com/browse/KOGITO-6932)
This is backport of https://github.com/kiegroup/kie-tools/pull/916
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …

KOGITO-6932: DMN editor: text annotation is not saved correctly when creating it by copy and paste

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml

Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2027
- https://github.com/kiegroup/droolsjbpm-integration/pull/2836
- https://github.com/kiegroup/kie-wb-common/pull/3760
- https://github.com/kiegroup/kie-wb-distributions/pull/1178
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023

[7.67.x] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

---

kie-wb-common-dmn/kie-wb-common-dmn-webapp-standalone/pom.xml

Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2028
- https://github.com/kiegroup/droolsjbpm-integration/pull/2837
- https://github.com/kiegroup/kie-wb-common/pull/3761
- https://github.com/kiegroup/kie-wb-distributions/pull/1179
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023

[7.67.x-blue] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

---

.github/workflows/pull_request.yml

https://github.com/kiegroup/kie-wb-common/pull/3762
https://github.com/kiegroup/droolsjbpm-integration/pull/2840
https://github.com/kiegroup/kie-wb-distributions/pull/1180
and cherry-picked to
7.67.x:
https://github.com/kiegroup/droolsjbpm-integration/pull/2842
https://github.com/kiegroup/kie-wb-common/pull/3764
https://github.com/kiegroup/kie-wb-distributions/pull/1181
7.67.x-blue:
https://github.com/kiegroup/droolsjbpm-integration/pull/2843
https://github.com/kiegroup/kie-wb-common/pull/3765
https://github.com/kiegroup/kie-wb-distributions/pull/1182
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the …

skipped parallel checkouts for build chain

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock

**JIRA**:  https://issues.redhat.com/browse/RHPAM-4530
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command …

RHPAM-4530 handlebars npm library to 4.7.7 due to CVE-2021-23383

---

kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/pom.xml
kie-wb-common-services/kie-wb-common-compiler/kie-wb-common-compiler-distribution/src/test/java/org/kie/workbench/common/services/backend/compiler/rest/client/MavenRestClientTest.java
kie-wb-common-services/kie-wb-common-data-modeller-core/pom.xml
kie-wb-common-services/kie-wb-common-datamodel/kie-wb-common-datamodel-backend/src/test/java/org/kie/workbench/common/services/datamodel/backend/server/ModuleDataModelFactAnnotationsTest.java
kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-project-showcase/pom.xml

https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2097
* https://github.com/kiegroup/appformer/pull/1312
* https://github.com/kiegroup/kie-wb-common/pull/3781
* https://github.com/kiegroup/drools-wb/pull/1558
* https://github.com/kiegroup/jbpm-wb/pull/1572
* https://github.com/kiegroup/optaplanner-wb/pull/413
* https://github.com/kiegroup/kie-wb-distributions/pull/1196

[BXMSPROD-1845] elasticsearch removed from appformer

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/package.json
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock

- https://github.com/kiegroup/appformer/pull/1319
- https://github.com/kiegroup/kie-wb-common/pull/3784
- https://github.com/kiegroup/optaweb-employee-rostering/pull/858
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/775
- https://github.com/kiegroup/process-migration-service/pull/79

[BXMSPROD-1700] @kie/lock-treatment-tool removed from package.json

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/package.json
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock

Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2110
* https://github.com/kiegroup/appformer/pull/1320
* https://github.com/kiegroup/process-migration-service/pull/80
* https://github.com/kiegroup/kie-wb-common/pull/3785

[7.67.x] [BXMSPROD-1700] @kie/lock-treatment-tool removed from package.json

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/package.json
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/pom.xml
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-spaces-screen/yarn.lock

Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2109
* https://github.com/kiegroup/appformer/pull/1321
* https://github.com/kiegroup/process-migration-service/pull/81
* https://github.com/kiegroup/kie-wb-common/pull/3786

[7.67.x-blue] [BXMSPROD-1700] @kie/lock-treatment-tool removed from package.json

---

.github/workflows/pull_request.yml

**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …

[7.67.x-blue][BXMSPROD-2067] Fix PR workflow concurrency group (#3811)

---

.github/workflows/pull_request.yml

**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …

[7.67.x][BXMSPROD-2067] Fix PR workflow concurrency group (#3811)

---

kie-wb-common-services/kie-wb-common-services-backend/src/main/java/org/kie/workbench/common/services/backend/validation/ValidationServiceImpl.java
kie-wb-common-services/kie-wb-common-services-backend/src/test/java/org/kie/workbench/common/services/backend/validation/ValidationServiceImplTest.java

**JIRA**: [RHPAM-4723](https://issues.redhat.com/browse/RHPAM-4723)
* https://github.com/kiegroup/appformer/pull/1393
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …

RHPAM-4723: Creating a branch via BC UI can lead to XSS

---

kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/DescriptionLengthValidator.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/main/java/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferences.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-api/src/test/java/org/kie/workbench/common/screens/library/api/preferences/DescriptionLengthValidatorTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/sections/generalsettings/GeneralSettingsPresenter.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/settings/sections/generalsettings/GeneralSettingsView.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/resources/org/kie/workbench/common/screens/library/client/resources/i18n/LibraryConstants.properties
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/screens/project/AddProjectPopUpPresenterTest.java
kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/test/java/org/kie/workbench/common/screens/library/client/settings/sections/generalsettings/GeneralSettingsPresenterTest.java

**JIRA**: [DROOLS-7618](https://issues.redhat.com/browse/DROOLS-7618)
**Business Central**: [WAR file](https://drive.google.com/file/d/12y3AytIkAophKMxMOaBxbUtd59sGoHzu/view?usp=sharing)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …

DROOLS-7618 : Project Editor: Long description should not freeze the UI

---

kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/validation/DMNDomainValidatorImpl.java

This issue occurs every time the DMN Validator is called (eg. when saving a DMN assets in BC) and the related project doesn't build for any reason.
In that scenario, the ClassLoader's Builder is null, and that doesn't allow the backend service to correctly behave, returning an NPE. 
To fix the issue, when the Builder is null, I initialized the Validator with the default constructor (with no classloader), like it was before this change https://github.com/kiegroup/kie-wb-common/pull/3728
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there …

[7.67.x-blue] Business Central UI gets stuck when saving any project's asset
